### ISSUE TITLE
.net8 ?

### ISSUE THREAD

**Issue by amir-inbar-software** [Mimetis/Dotmim.Sync#1126]
Is it compatible with .net8 ?

Thanks.

**Comment by amir-inbar-software** [comment]
It worked well, but when i did ios TestFlight deployment i got this error:

   [InternalEnsureScopeInfoAsync]..[InternalExistsScopeInfoAsync]..Attempting to JIT compile method '(wrapper dynamic-method) object object:Thunk1ret_Object_CallSite_Object_Object (System.Func`2<object[], object>,System.Runtime.CompilerServices.CallSite,object,object)' while running in aot-only mode. See https://docs.microsoft.com/xamarin/ios/internals/limitations for more information.

at Dotmim.Sync.LocalOrchestrator.InternalEnsureScopeInfoAsync(SyncContext context, DbConnection connection, DbTransaction transaction, CancellationToken cancellationToken, IProgress`1 progress)
   at Dotmim.Sync.SyncAgent.SynchronizeAsync(String scopeName, SyncSetup setup, SyncType syncType, SyncParameters parameters, CancellationToken cancellationToken, IProgress`1 progress)
   at Dotmim.Sync.SyncAgent.SynchronizeAsync(String scopeName, SyncSetup setup, SyncType syncType, SyncParameters parameters, CancellationToken cancellationToken, IProgress`1 progress)
   at AirCo365.Services.AirCoDataAndSyncService.SyncLocalDB()
   
Any Clue?

**Comment by amir-inbar-software** [comment]
Hi, found it on google:

https://learn.microsoft.com/en-us/dotnet/maui/macios/interpreter?view=net-maui-8.0

i had to enable this interperter and now it's working.

So i don't think that it was related to the .net8 issue.

Thanks.
