### ISSUE TITLE
Synchronization Not Working in Release Mode with Dotmim.Sync on MAUI App (AOT Compilation Error)

### ISSUE THREAD

**Issue by JustAnotherLars** [Mimetis/Dotmim.Sync#1268]
**Description:**

I'm using Dotmim.Sync as a singleton service in a .NET MAUI app to handle data synchronization. The issue I’m experiencing is that synchronization works perfectly in Debug mode but fails in Release mode.
In Release mode, no synchronized objects are visible in the app, though the app itself doesn't crash. The following error message appears in the logs during synchronization attempts:

The error seems related to JIT compilation, which is restricted in AOT-only environments. I've tried enabling the Mono Interpreter for Release builds as a workaround:

`<PropertyGroup Condition="$(TargetFramework.Contains('-ios')) and '$(Configuration)' == 'Release'">
    <UseInterpreter>true</UseInterpreter>
</PropertyGroup>
`
However, with this setting, the app fails to start entirely in Release mode.

Hier ist ein möglicher GitHub-Issue für das Problem:

Title: Synchronization Not Working in Release Mode with Dotmim.Sync on MAUI App (AOT Compilation Error)

Description:

I'm using Dotmim.Sync as a singleton service in a .NET MAUI app to handle data synchronization. The issue I’m experiencing is that synchronization works perfectly in Debug mode but fails in Release mode.

In Release mode, no synchronized objects are visible in the app, though the app itself doesn't crash. The following error message appears in the logs during synchronization attempts:
```2024-10-30 14:15:43.489 +01:00 [ERR] An error occured during synchronization.
Dotmim.Sync.SyncException: [InternalEnsureScopeInfoAsync]..[InternalExistsScopeInfoAsync]..Attempting to JIT compile method '(wrapper dynamic-method) object object:Thunk1ret_Object_CallSite_Object_Object (System.Func`2<object[], object>,System.Runtime.CompilerServices.CallSite,object,object)' while running in aot-only mode. See https://docs.microsoft.com/xamarin/ios/internals/limitations for more information.

 ---> System.ExecutionEngineException: 

   at System.Delegate.CreateDelegate(Type , Object , MethodInfo , Boolean , Boolean )
   at System.Reflection.Emit.DynamicMethod.CreateDelegate(Type , Object )
   at System.Dynamic.Utils.DelegateHelpers.CreateObjectArrayDelegateRefEmit(Type , Func`2 )
   at System.Dynamic.Utils.DelegateHelpers.CreateObjectArrayDelegate(Type , Func`2 )
   at System.Linq.Expressions.Interpreter.LightLambda.MakeDelegate(Type )
   at System.Linq.Expressions.Interpreter.LightDelegateCreator.CreateDelegate(IStrongBox[] )
   at System.Linq.Expressions.Expression`1[[System.Func`4[[System.Runtime.CompilerServices.CallSite, System.Linq.Expressions, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a],[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Compile()
   at System.Runtime.CompilerServices.CallSite`1[[System.Func`4[[System.Runtime.CompilerServices.CallSite, System.Linq.Expressions, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a],[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].CreateCustomNoMatchDelegate(MethodInfo )
   at System.Runtime.CompilerServices.CallSite`1[[System.Func`4[[System.Runtime.CompilerServices.CallSite, System.Linq.Expressions, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a],[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MakeUpdateDelegate()
   at System.Runtime.CompilerServices.CallSite`1[[System.Func`4[[System.Runtime.CompilerServices.CallSite, System.Linq.Expressions, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a],[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].GetUpdateDelegate(Func`4& )
   at System.Runtime.CompilerServices.CallSite`1[[System.Func`4[[System.Runtime.CompilerServices.CallSite, System.Linq.Expressions, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a],[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].GetUpdateDelegate()
   at System.Runtime.CompilerServices.CallSite`1[[System.Func`4[[System.Runtime.CompilerServices.CallSite, System.Linq.Expressions, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a],[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]..ctor(CallSiteBinder )
   at System.Runtime.CompilerServices.CallSite`1[[System.Func`4[[System.Runtime.CompilerServices.CallSite, System.Linq.Expressions, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a],[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Create(CallSiteBinder binder)
   at Dotmim.Sync.SyncTypeConverter.TryConvertTo[String](Object value, CultureInfo provider)
   at Dotmim.Sync.SyncTypeConverter.TryConvertFromDbType(Object value, DbType typeOfT, CultureInfo provider)
   at Dotmim.Sync.BaseOrchestrator.InternalSetParameterValue(DbCommand command, String parameterName, Object value)
   at Dotmim.Sync.BaseOrchestrator.InternalExistsScopeInfoAsync(String scopeName, SyncContext context, DbConnection connection, DbTransaction transaction, CancellationToken cancellationToken, IProgress`1 progress)
   at Dotmim.Sync.BaseOrchestrator.InternalExistsScopeInfoAsync(String scopeName, SyncContext context, DbConnection connection, DbTransaction transaction, CancellationToken cancellationToken, IProgress`1 progress)
   Exception_EndOfInnerExceptionStack
   at Dotmim.Sync.LocalOrchestrator.InternalEnsureScopeInfoAsync(SyncContext context, DbConnection connection, DbTransaction transaction, CancellationToken cancellationToken, IProgress`1 progress)
   at Dotmim.Sync.SyncAgent.SynchronizeAsync(String scopeName, SyncSetup setup, SyncType syncType, SyncParameters parameters, CancellationToken cancellationToken, IProgress`1 progress)
   at DigitalMeasurementProtocol.MAUI.Services.SyncService.Sync()

```

The error seems related to JIT compilation, which is restricted in AOT-only environments. I've tried enabling the Mono Interpreter for Release builds as a workaround:
```
<PropertyGroup Condition="$(TargetFramework.Contains('-ios')) and '$(Configuration)' == 'Release'">
    <UseInterpreter>true</UseInterpreter>
</PropertyGroup>
```

However, with this setting, the app fails to start entirely in Release mode.

Steps to Reproduce:
    Configure Dotmim.Sync as a singleton in a .NET MAUI app.
    Run the synchronization in Debug mode - it works as expected.
    Deploy the app in Release mode on an iOS device.
    Observe the error in the log file.

**Expected Behavior:** 
    Synchronization should work in both Debug and Release modes without needing JIT compilation.

**Actual Behavior:**
    In Debug mode, synchronization works as expected.
    In Release mode, the synchronization fails due to the AOT restriction, and enabling the Mono Interpreter prevents the app from starting.

**Version Information:**
    Dotmim.Sync.Core: 1.2.0
    Dotmim.Sync.Sqlite: 1.2.0
    Dotmim.Sync.Web.Client: 1.2.0
    .NET MAUI: net8.0
    Platform: iOS (Release mode)

**Workarounds Attempted:**
    Enabled Mono Interpreter for Release builds (<UseInterpreter>true</UseInterpreter>), but the app fails to start.

**Additional Context:** Any advice on using Dotmim.Sync in AOT environments like iOS in Release mode, or if alternative configuration settings could resolve the AOT compilation issues, would be appreciated.

**Comment by JustAnotherLars** [comment]
By the way, this function causes the error.

```
        public async Task Sync()
        {
            if(Connectivity.NetworkAccess != NetworkAccess.Internet)
            {
                _logger.LogInformation("No Internetconnection available. Sync aborted.");
                return;
            }
            try
            {
                var token = await _authorizationService.GetAuthenticationTokenAsync();
                var httpHandler = new HttpClientHandler
                {
                    AutomaticDecompression = System.Net.DecompressionMethods.GZip
                };
                HttpClient httpClient = new HttpClient(httpHandler);
                httpClient.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", token.Token);
                httpClient.DefaultRequestHeaders.AcceptEncoding.Add(new System.Net.Http.Headers.StringWithQualityHeaderValue("gzip"));
                var dbFile = Helpers.Constants.DbPath;
                if(dbFile is null)
                {
                    _logger.LogInformation("No database file found.");
                    return; 
                }
                _remoteOrchestrator = new WebRemoteOrchestrator(Constants.ServerAdr, client: httpClient);
                _syncProvider = new SqliteSyncProvider(dbFile);
                _syncAgent = new SyncAgent(_syncProvider, _remoteOrchestrator);
                var setup = new SyncSetup(new string[] { "User", "Project", "Measurement", "AbstractBaseEquipement", "Media", "AbstractBaseShape", "MeasurementLocation", "ProjectUser", "Line" });
                var result = await _syncAgent.SynchronizeAsync(setup);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "An error occured during synchronization.");
                throw;
            }
        }
```

**Comment by generic823** [comment]
@JustAnotherLars, Did you ever figure out a workaround? I am having the same issue with my project.

**Comment by generic823** [comment]
@Mimetis I wanted to ask if the Dotmim framework supports MAUI on iOS. I have been using this framework for the past six months to build my application, and I am close to completion. However, I am encountering the same error that JustAnotherLars mentioned, and I haven't seen a response addressing this issue yet. I thought it would be best to reach out and inquire whether this issue has been resolved or if there are plans to resolve it before making any further plans for my app. Thank you!

**Comment by Mimetis** [comment]
I have no idea, I never tried or used AOT compilation

**Comment by mpnow** [comment]
@JustAnotherLars @generic823 I asked Claude about the above error and it returned the following info - is this helpful?
_________________________________

This error occurs because Dotmim.Sync is using dynamic code generation/reflection (specifically trying to JIT compile a dynamic method) which isn't supported in iOS AOT mode.

To fix:

1. Add relevant types to linker configuration:

<linker>
  <assembly fullname="Dotmim.Sync">
    <type fullname="Dotmim.Sync.SyncTypeConverter" preserve="all"/>
  </assembly>
</linker>

2. Or disable AOT for problematic assemblies in iOS project settings:

<MtouchExtraArgs>--linkskip=Dotmim.Sync</MtouchExtraArgs>

Choose option 1 for better performance, option 2 for simpler implementation.

**Comment by mpnow** [comment]
I tried both of Claude's suggestions and unfortunately neither of them fixed the error. @Mimetis do you have any more thoughts/suggestions? Alas at this point it appears I'm going to have to go find another sync solution to use.

**Comment by Mimetis** [comment]
Can you share a sample (a really simple sample that highlight the failure), preferably a GitHub repository, I can use to reproduce the error ?

**Comment by mpnow** [comment]
No, it's specifically an iOS issue. So a small sample won't do you any good. Not to be a negative nellie but it seems unlikely you'll be able to repro the error without an iOS device to deploy to. @JustAnotherLars or @generic823, do you have any other ideas?

**Comment by mentezam-jacobs** [comment]
Hello @mpnow , was wondering if this issue was resolved for you?  
We are also investigating the usage of Dotmim.Sync for offline syncing and we have users on iOS as well.  Thank you.

**Comment by mentezam-jacobs** [comment]
> [@mentezam-jacobs](https://github.com/mentezam-jacobs) No, I ended up not using DMS so I never implemented the fix documented in the link above.

Thank you @mpnow for the info.  Out of curiosity, did you end up implementing a custom sync solution or did you go with something like like _**DataSync Toolkit**_ (which had reported similar issue though)?

**Comment by mpnow** [comment]
After going down A LOT of different paths, I ended up going in a completely different direction and using Couchbase Server and Couchbase Lite.

EDIT: For completeness sake, amending this post: I actually did not end up using Couchbase but went with Powersync.

**Comment by anfenx** [comment]
I’m experiencing the same issue in my C# MAUI .NET 10 app when using a Release build instead of Debug.
Would it be possible to eliminate the use of dynamic code?
I asked ChatGPT about this and received the following response:

I get the following exception in my C# MAUI APP under iOS. What could be the problem and how can I solve it?

27.12.25 08:56:25,186 ERROR Dotmim.Sync.SyncException: [NeedsToUpgradeAsync]..[InternalExistsScopeInfoTableAsync].ScopeType:ScopeInfo..Attempting to JIT compile method '(wrapper dynamic-method) object object:Thunk1ret_Object_CallSite_Object_Object (System.Func2<object[], object>,System.Runtime.CompilerServices.CallSite,object,object)' while running in aot-only mode. See https://learn.microsoft.com/xamarin/ios/internals/limitations for more information. ---> System.ExecutionEngineException: Attempting to JIT compile method '(wrapper dynamic-method) object object:Thunk1ret_Object_CallSite_Object_Object (System.Func2<object[], object>,System.Runtime.CompilerServices.CallSite,object,object)' while running in aot-only mode. See https://learn.microsoft.com/xamarin/ios/internals/limitations for more information. at System.Delegate.CreateDelegate(Type , Object , MethodInfo , Boolean , Boolean ) at System.Reflection.Emit.DynamicMethod.CreateDelegate(Type , Object ) at System.Dynamic.Utils.DelegateHelpers.CreateObjectArrayDelegateRefEmit(Type , Func2 ) at System.Dynamic.Utils.DelegateHelpers.CreateObjectArrayDelegate(Type , Func2 ) at System.Linq.Expressions.Interpreter.LightLambda.MakeDelegate(Type ) at System.Linq.Expressions.Interpreter.LightDelegateCreator.CreateDelegate(IStrongBox[] ) at System.Linq.Expressions.Expression1[[System.Func4[[System.Runtime.CompilerServices.CallSite, System.Linq.Expressions, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a],[System.Object, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Object, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Object, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Compile() at System.Runtime.CompilerServices.CallSite1[[System.Func4[[System.Runtime.CompilerServices.CallSite, System.Linq.Expressions, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a],[System.Object, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Object, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Object, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].CreateCustomNoMatchDelegate(MethodInfo ) at System.Runtime.CompilerServices.CallSite1[[System.Func4[[System.Runtime.CompilerServices.CallSite, System.Linq.Expressions, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a],[System.Object, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Object, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Object, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MakeUpdateDelegate() at System.Runtime.CompilerServices.CallSite1[[System.Func4[[System.Runtime.CompilerServices.CallSite, System.Linq.Expressions, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a],[System.Object, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Object, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Object, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].GetUpdateDelegate(Func4& ) at System.Runtime.CompilerServices.CallSite1[[System.Func4[[System.Runtime.CompilerServices.CallSite, System.Linq.Expressions, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a],[System.Object, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Object, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Object, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].GetUpdateDelegate() at System.Runtime.CompilerServices.CallSite1[[System.Func4[[System.Runtime.CompilerServices.CallSite, System.Linq.Expressions, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a],[System.Object, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Object, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Object, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]..ctor(CallSiteBinder ) at System.Runtime.CompilerServices.CallSite1[[System.Func4[[System.Runtime.CompilerServices.CallSite, System.Linq.Expressions, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a],[System.Object, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Object, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Object, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Create(CallSiteBinder binder) at Dotmim.Sync.SyncTypeConverter.TryConvertTo[Int32](Object value, CultureInfo provider) at Dotmim.Sync.BaseOrchestrator.InternalExistsScopeInfoTableAsync(SyncContext context, DbScopeType scopeType, DbConnection connection, DbTransaction transaction, IProgress1 progress, CancellationToken cancellationToken) at Dotmim.Sync.BaseOrchestrator.InternalExistsScopeInfoTableAsync(SyncContext context, DbScopeType scopeType, DbConnection connection, DbTransaction transaction, IProgress1 progress, CancellationToken cancellationToken) Exception_EndOfInnerExceptionStack at Dotmim.Sync.LocalOrchestrator.NeedsToUpgradeAsync(SyncContext context) at Dotmim.Sync.SyncAgent.SynchronizeAsync(String scopeName, SyncSetup setup, SyncType syncType, SyncParameters parameters, IProgress1 progress, CancellationToken cancellationToken) at FLGeneral.FLDatabase.UseNewSyncFramework(SyncOrigin syncOrigin, DateTime dtStart) [00:00:00.364][ 3] FLGeneral.FLDatabase+<UseNewSyncFramework>d__60.MoveNext:0
✅ Short answer
This is not a MAUI bug and not your code.
Your app crashes because Dotmim.Sync uses runtime code generation (JIT / Expression.Compile / DynamicMethod), which is forbidden on iOS, because iOS runs .NET in AOT-only mode.
________________________________________
🔴 What exactly is the problem?
The key part of the exception is:
Attempting to JIT compile method ... while running in aot-only mode
On iOS:
•	❌ JIT (Just-In-Time compilation) is not allowed
•	❌ Reflection.Emit
•	❌ DynamicMethod
•	❌ Expression.Compile()
•	❌ dynamic / CallSite
Your stack trace clearly shows this chain:
System.Reflection.Emit.DynamicMethod
System.Linq.Expressions.Expression.Compile()
System.Runtime.CompilerServices.CallSite
Dotmim.Sync.SyncTypeConverter.TryConvertTo<Int32>
➡️ Dotmim.Sync dynamically builds and compiles delegates at runtime
➡️ iOS blocks this by design
➡️ Result: ExecutionEngineException
________________________________________
🎯 Why it happens in NeedsToUpgradeAsync
This code path runs when Dotmim.Sync:
•	checks or upgrades the ScopeInfo table
•	inspects database schema / metadata
•	converts DB values dynamically (object → int, etc.)
That conversion uses Expression Trees + Compile(), which works on:
•	Windows ✔️
•	Android ✔️
•	macOS Catalyst ✔️
…but never on iOS ❌
________________________________________
❗ Important: This cannot be fixed by configuration
Things that will NOT help:
•	Changing linker settings
•	Turning off trimming
•	Using Debug vs Release
•	Any Entitlements or plist setting
•	Any MAUI / iOS option
Apple does not allow JIT. Period.
________________________________________
✅ Real solutions (from practice)
✅ Solution 1 (recommended): Do NOT use Dotmim.Sync on iOS
This is what most production apps do.
if (DeviceInfo.Platform == DevicePlatform.iOS)
{
    throw new PlatformNotSupportedException(
        "Dotmim.Sync is not supported on iOS due to AOT limitations.");
}
Then:
•	Use REST / API sync for iOS
•	Keep Dotmim.Sync for:
o	Windows
o	Android
o	Server
➡️ Stable, supported, future-proof
________________________________________
⚠️ Solution 2: Try older Dotmim.Sync versions (not reliable)
Some older versions had fewer dynamic paths, but:
•	❌ not officially supported
•	❌ can break on any update
•	❌ still unsafe for App Store releases
I do not recommend this for production.
________________________________________
❌ Solution 3: Enable JIT on iOS
Impossible.
Apple forbids it.
There is no workaround.
________________________________________
🔁 Solution 4: Replace local DB sync on iOS
Common alternatives:
•	REST-based delta sync (timestamps / rowversion)
•	Backend-driven sync (API returns changes)
•	GraphQL subscriptions
•	Azure App Services / custom sync logic
•	SQLite + server reconciliation
Yes, Dotmim.Sync is great — but iOS is a hard blocker.
________________________________________
🧪 Quick proof (if you want to confirm)
Temporarily skip sync on iOS:
if (DeviceInfo.Platform == DevicePlatform.iOS)
    return;
➡️ The crash will disappear immediately.
________________________________________
🧠 Why it may appear “suddenly”
Because NeedsToUpgradeAsync only runs when:
•	the app runs the first time
•	the local DB was reset
•	the schema changed
•	the scope table does not exist yet
So it may work until that moment, then crash.
________________________________________
✅ Final conclusion
Root cause
Dotmim.Sync relies on runtime code generation
→ forbidden on iOS (AOT only)
Status
Structural platform limitation, not a bug
Best practice
✔️ Do not use Dotmim.Sync on iOS
✔️ Use API-based sync for iOS
✔️ Keep Dotmim.Sync for other platforms
________________________________________
If you want, I can help you:
•	design an iOS-safe sync architecture
•	split sync strategies per platform
•	migrate Dotmim.Sync → REST delta sync
Just tell me 👍
