### ISSUE TITLE
timout period error

### ISSUE THREAD

**Issue by mdonogma** [Mimetis/Dotmim.Sync#196]
Populated db with approx 30 tables and 10 000 rows per table.
Run sync
 at Dotmim.Sync.Web.Client.HttpRequestHandler.HandleSyncError(HttpResponseMessage response, ISerializerFactory serializerFactory) in /Users/mdo/Documents/git/Dotmim.Sync/Projects/Dotmim.Sync.Web.Client/HttpRequestHandler.cs:line 210
   at Dotmim.Sync.Web.Client.HttpRequestHandler.ProcessRequestAsync[U](HttpClient client, String baseUri, Byte[] data, HttpStep step, Guid sessionId, ISerializerFactory serializerFactory, IConverter converter, Int32 batchSize, CancellationToken cancellationToken) in /Users//Documents/git/Dotmim.Sync/Projects/Dotmim.Sync.Web.Client/HttpRequestHandler.cs:line 120
   at Dotmim.Sync.Web.Client.WebClientOrchestrator.ApplyThenGetChangesAsync(SyncContext context, ScopeInfo scope, SyncSet schema, BatchInfo clientBatchInfo, Boolean disableConstraintsOnApplyChanges, Boolean useBulkOperations, Boolean cleanMetadatas, Int32 clientBatchSize, String batchDirectory, ConflictResolutionPolicy policy, CancellationToken cancellationToken, IProgress`1 progress) in /Users/Documents/git/Dotmim.Sync/Projects/Dotmim.Sync.Web.Client/WebClientOrchestrator.cs:line 270
   at Dotmim.Sync.SyncAgent.SynchronizeAsync(SyncType syncType, CancellationToken cancellationToken, IProgress`1 progress) in /Users/mdo/Documents/git/Dotmim.Sync/Projects/Dotmim.Sync.Core/SyncAgent.cs:line 260

How do we increase timeout?

**Comment by Mimetis** [comment]
## Increasing timeout

By default, `Timeout` is fixed to 2 minutes.
To increase the overall timeout, you will have to work on both side: 
- Your web server api project 
- Your client application

### Server side
There is no way to increase the `Timeout` period on your web api, with **.Net Core**   
The only solution is to provide a `web.config`, that you add manually to your project.  
More information here : [increase-the-timeout-of-asp-net-core-application](https://medium.com/aspnetcore/increase-the-timeout-of-asp-net-core-application-9a7b4f6deebf)

Here is a `web.config` example where `requestTimeout` is fixed to 20 minutes:
``` xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <handlers>
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified"/>
    </handlers>
    <aspNetCore requestTimeout="00:20:00"  processPath="%LAUNCHER_PATH%" arguments="%LAUNCHER_ARGS%" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" forwardWindowsAuthToken="false"/>
  </system.webServer>
</configuration>
```

### Client side

On the client side, the web orchestrator `WebClientOrchestrator` instance uses its own `HttpClient` instance unless you specify your own `HttpClient` instance.

So far, to increase the timeout, you can either:

* Provide your own `HttpClient` instance with the `Timeout` property correctly set:
``` cs
var handler = new HttpClientHandler { AutomaticDecompression = DecompressionMethods.GZip };
var client = new HttpClient(handler) { Timeout = TimeSpan.FromMinutes(20) };
var proxyClientProvider = new WebClientOrchestrator("http://localhost:52288/api/Sync", null, null, client);
```
* Increase the existing `HttpClient` instance, created by `WebClientOrchestrator`:
``` cs
var proxyClientProvider = new WebClientOrchestrator("http://localhost:52288/api/Sync");
proxyClientProvider.HttpClient.Timeout = TimeSpan.FromMinutes(20);

```
 
> I've just resolved a small issue on the first solution, where you provide your own client.
> So far, use the second solution, if you're not working with the source code, but from nuget packages

**Comment by Mimetis** [comment]
No answer from you, I guess it's ok

**Comment by jaimelahoz** [comment]
Hi,

I have the same issue. The synchronization works perfectly, but I create a function that check if scheme is equal as before, if this is the case then I call DropAll and Provision for re-create "scheme configuration". Is in Provision function when occur this problem. I should fix this problem increasing timeout? If is the case I should say I'm not working with ASP.Net Core, I'm working with .NET 6 and Windows Forms because is a desktop application. The remote database is hosted in a server in local net.

I should do it as documentation or this post suggest or other way? Any suggestions?

Thanks in advance.
