### ISSUE TITLE
.4 Web sync TimeDateOffset not supported

### ISSUE THREAD

**Issue by dgrothman** [Mimetis/Dotmim.Sync#226]
I am looking at migrating from .3 to .4, but when I run the new .4 webproxyserverorchestrator I get an error when trying to send changes. I have sqlite running on the client side and sql on the server side

```
Dotmim.Sync.FormatTypeException: The type DateTimeOffset is not supported 
   at Dotmim.Sync.SyncTypeConverter.TryConvertTo(Object value, Type typeOfT)
   at Dotmim.Sync.SyncRows.ImportContainerTable(ContainerTable containerTable, Boolean checkType)
   at Dotmim.Sync.SyncSet.ImportContainerSet(ContainerSet containerSet, Boolean checkType)
   at Dotmim.Sync.Batch.BatchPartInfo.LoadBatchAsync(SyncSet schema, String directoryFullPath)
   at Dotmim.Sync.Web.Server.WebServerOrchestrator.GetChangesResponseAsync(SyncContext syncContext, Int64 remoteClientTimestamp, BatchInfo serverBatchInfo, DatabaseChangesSelected serverChangesSelected, Int32 batchIndexRequested, ConflictResolutionPolicy policy)
   at Dotmim.Sync.Web.Server.WebServerOrchestrator.ApplyThenGetChangesAsync(HttpMessageSendChangesRequest httpMessage, SessionCache sessionCache, Int32 clientBatchSize, CancellationToken cancellationToken)
   at Dotmim.Sync.Web.Server.WebProxyServerOrchestrator.HandleRequestAsync(HttpContext context, Action`1 action, CancellationToken cancellationToken)
```

**Comment by Mimetis** [comment]
Can you try with the source code instead of the nuget package?

**Comment by Mimetis** [comment]
Hum, got it, I think I found the issue.
Can you try with the last commit on the `master` branch ?

**Comment by dgrothman** [comment]
I am trying it now, I will let you know.

**Comment by dgrothman** [comment]
That fixed the DateTimeOffset error, now I am getting the following error.
```
Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot implicitly convert type 'decimal' to 'float'. An explicit conversion exists (are you missing a cast?)
   at CallSite.Target(Closure , CallSite , Object )
   at Dotmim.Sync.SyncTypeConverter.TryConvertTo[T](Object value)
   at Dotmim.Sync.SyncTypeConverter.TryConvertTo(Object value, Type typeOfT)
   at Dotmim.Sync.SyncRows.ImportContainerTable(ContainerTable containerTable, Boolean checkType)
   at Dotmim.Sync.SyncSet.ImportContainerSet(ContainerSet containerSet, Boolean checkType)
   at Dotmim.Sync.Batch.BatchPartInfo.LoadBatchAsync(SyncSet schema, String directoryFullPath)
   at Dotmim.Sync.Web.Server.WebServerOrchestrator.GetChangesResponseAsync(SyncContext syncContext, Int64 remoteClientTimestamp, BatchInfo serverBatchInfo, DatabaseChangesSelected serverChangesSelected, Int32 batchIndexRequested, ConflictResolutionPolicy policy)
   at Dotmim.Sync.Web.Server.WebServerOrchestrator.ApplyThenGetChangesAsync(HttpMessageSendChangesRequest httpMessage, SessionCache sessionCache, Int32 clientBatchSize, CancellationToken cancellationToken)
   at Dotmim.Sync.Web.Server.WebProxyServerOrchestrator.HandleRequestAsync(HttpContext context, Action`1 action, CancellationToken cancellationToken)
```

**Comment by Mimetis** [comment]
can you share the schema you re using ?

**Comment by dgrothman** [comment]
This is the data going into the function when it crashes: 

```
typeOfT: "System.Single"
typeOfU: "System.Double"
value: {double} -16.013369999999998
```

<img width="325" alt="Screen Shot 2020-02-22 at 1 26 03 PM" src="https://user-images.githubusercontent.com/10801916/75099495-2943cd80-5577-11ea-9cab-2e82f71c7dde.png">

**Comment by Mimetis** [comment]
Ok, is it the schema from SQL Server or SQLite ?
ideally, I need both schema, the one from server and the one generated on SQLite

**Comment by dgrothman** [comment]
Okay that was the sql server side, here is the sqlite
<img width="540" alt="Screen Shot 2020-02-22 at 3 48 52 PM" src="https://user-images.githubusercontent.com/10801916/75100992-dd028880-558a-11ea-8c4d-cb95bae148fb.png">

**Comment by dgrothman** [comment]
It is in the Bias Column when it crashes

**Comment by Mimetis** [comment]
Ok, got it.

Sorry for this regression, should be fine now on the master branch.
Let me know

**Comment by dgrothman** [comment]
Okay great I will check it out today. Thanks

**Comment by dgrothman** [comment]
Yes that fixed it. Thank you again.
