### ISSUE TITLE
Conflict fails when Primary Key is not index 0

### ISSUE THREAD

**Issue by joseavilees** [Mimetis/Dotmim.Sync#273]
Hello Sebastien,
You are doing a great job with this lib, thank you very much!

I get an error when I edit the same row from the client and then from the server.

```
System.AggregateException: One or more errors occurred. (Index was outside the bounds of the array.)
 ---> Dotmim.Sync.SyncException: Index was outside the bounds of the array.
 ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Dotmim.Sync.SyncRow.get_Item(Int32 index)
   at Dotmim.Sync.SyncRow.get_Item(String columnName)
   at Dotmim.Sync.SyncRows.<>c__DisplayClass13_0.<GetRowsByPrimaryKeys>b__0(SyncRow itemRow)
   at System.Linq.Enumerable.WhereListIterator`1.GetCount(Boolean onlyIfCheap)
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)
   at Dotmim.Sync.DbSyncAdapter.ApplyBulkChangesAsync(Guid localScopeId, Guid senderScopeId, SyncTable changesTable, Int64 lastTimestamp, List`1 conflicts)
   at Dotmim.Sync.CoreProvider.ApplyChangesInternalAsync(SyncTable schemaTable, SyncContext context, MessageApplyChanges message, DbConnection connection, DbTransaction transaction, DataRowState applyType, DatabaseChangesApplied changesApplied, CancellationToken cancellationToken, IProgress`1 progress)
   at Dotmim.Sync.CoreProvider.ApplyChangesAsync(SyncContext context, MessageApplyChanges message, DbConnection connection, DbTransaction transaction, CancellationToken cancellationToken, IProgress`1 progress)
   at Dotmim.Sync.RemoteOrchestrator.ApplyThenGetChangesAsync(ScopeInfo clientScope, BatchInfo clientBatchInfo, CancellationToken cancellationToken, IProgress`1 progress)
   --- End of inner exception stack trace ---
   at Dotmim.Sync.BaseOrchestrator.RaiseError(Exception exception)
   at Dotmim.Sync.RemoteOrchestrator.ApplyThenGetChangesAsync(ScopeInfo clientScope, BatchInfo clientBatchInfo, CancellationToken cancellationToken, IProgress`1 progress)
   at Dotmim.Sync.SyncAgent.SynchronizeAsync(SyncType syncType, CancellationToken cancellationToken, IProgress`1 progress)
```

Steps to reproduce the error:
- Create a table with at least a row on the server.
- Invokes synchronization with the SyncAgent.
- Once the table and row is created on the client, edit a row.
- Edit that same row from the server.

Running the SyncAgent again will throw an exception.

I am using the same instance of SQL Server 2019 with different databases for the client and the server. My application works on ASP.NET Core 3.1 .

Thanks.

**Comment by Mimetis** [comment]
Can you share the table schema ?
The table is already created on the client, or you let `DMS` do it ?
Are you using a Web api or is it a direct link ?

Why are you saying "different" databases for client and server ?

**Comment by joseavilees** [comment]
Schema: 
![image](https://user-images.githubusercontent.com/57925314/81487607-0ca66000-925f-11ea-813b-662644fb8993.png)

I let DSM create the table.

I wanted to say that since I am using SQL Server on both the client and the server, the client has one database, and the server has another, although both databases have the same schema.

**Comment by ProblemSolved** [comment]
Does it make a difference if you move your primary key to to first position in your table?
So its index will be 0.

**Comment by ProblemSolved** [comment]
This is the workaround that solved the problem for me:
![image](https://user-images.githubusercontent.com/5349088/81491298-3f3c7100-92d0-11ea-90d9-cf9752f71d0d.png)

Not really a proper solution, but still, it might help for the interim.

**Comment by Mimetis** [comment]
Ok, I've found the bug.
You are right.
It was coming from the primary key position, when a conflict occurs.

I'm submitting a fix, If all tests are good, I will push a new beta version.

**Comment by Mimetis** [comment]
I've published an update, can you try the last pre-release version `0.5.5-beta-0408` ?

https://www.nuget.org/packages/Dotmim.Sync.Core/0.5.5-beta-0408
