### ISSUE TITLE
Error when registering a custom scope name

### ISSUE THREAD

**Issue by lordofffarm** [Mimetis/Dotmim.Sync#286]
In the version 0.5.5 and in the master branch, when I add a sync server like this
```
services.AddSyncServer<MySqlSyncProvider>(
                            connectionString,
                            "customScopeName1",
                            syncSetup);
```
And try to synchronize like this:
```
var serverOrchestrator = new WebClientOrchestrator("http://localhost:5050/api/Sync");
var clientProvider = new SqliteSyncProvider(newDbImageFilePath);
var agent = new SyncAgent(clientProvider, serverOrchestrator);
agent.ScopeName = "customScopeName1";
serverOrchestrator.ScopeName = "customScopeName1";

do
{
     // Launch the sync process
     var s1 = await agent.SynchronizeAsync();
     // Write results
     Console.WriteLine(s1);
} while (Console.ReadKey().Key != ConsoleKey.Escape);
Console.WriteLine("End");
```
I get this error:
```
HEADERS
=======
Content-Type: application/json
Accept-Encoding: gzip, deflate
Host: localhost:5050
Content-Length: 273
dotmim-sync-session-id: e15e736f-0b3e-4697-8d69-a92f070dccf0
dotmim-sync-scope-name: DefaultScope
dotmim-sync-step: 3
dotmim-sync-serialization-format: {"f":"json","s":0}
dotmim-sync-hash: WHGAM9wW7BMlYS/pUyZ+xqLpDB8RDajhIYSippSKeTY=

 ---> Dotmim.Sync.UnknownException: Dotmim.Sync.HttpScopeNameInvalidException: The scope DefaultScope does not exist on the server side. Please provider a correct scope name
   at Dotmim.Sync.Web.Server.WebServerManager.GetOrchestrator(String scopeName)
   at Dotmim.Sync.Web.Server.WebServerManager.GetOrchestrator(HttpContext context)
```

In the first 2 steps the header `dotmim-sync-scope-name` is set correctly to `customScopeName1`,
but something goes wrong in the third step.

**Comment by Mimetis** [comment]
Change

``` cs
var agent = new SyncAgent(clientProvider, serverOrchestrator);
agent.ScopeName = "customScopeName1";
serverOrchestrator.ScopeName = "customScopeName1";
```
To

``` cs
var agent = new SyncAgent(clientProvider, serverOrchestrator, "customScopeName1");
```
The `agent.ScopeName` setter will be removed in the next release.

I close the issue. Let me know if it's working correctly. If not, I will reopen this issue.
