### ISSUE TITLE
Dotmim.Sync.SyncException: Format of the initialization string does not conform to specification starting at index 0

### ISSUE THREAD

**Issue by akema-trebla** [Mimetis/Dotmim.Sync#317]
**Description**

I've been following the documentation and I've been able to test the bidirectional sync using a server and a client on the same network. However, when I moved to try it out with my online server (Azure), I get the following error:
Dotmim.Sync.SyncException: Format of the initialization string does not conform to specification starting at index 0

Searching on Google, the problem seems to point to a connecting string issue. The connection to the database seems to be fine from accessing the api/sync endpoint.

Can someone help me format my azure connection string to work with Dotmim?

**StackTrace**
at Microsoft.Data.Common.DbConnectionOptions.GetKeyValuePair(String connectionString, Int32 currentPosition, StringBuilder buffer, Boolean useOdbcRules, String& keyname, String& keyvalue)
   at Microsoft.Data.Common.DbConnectionOptions.ParseInternal(Dictionary`2 parsetable, String connectionString, Boolean buildChain, Dictionary`2 synonyms, Boolean firstKey)
   at Microsoft.Data.Common.DbConnectionOptions..ctor(String connectionString, Dictionary`2 synonyms)
   at Microsoft.Data.SqlClient.SqlConnectionString..ctor(String connectionString)
   at Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnectionOptions(String connectionString, DbConnectionOptions previous)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.GetConnectionPoolGroup(DbConnectionPoolKey key, DbConnectionPoolGroupOptions poolOptions, DbConnectionOptions& userConnectionOptions)
   at Microsoft.Data.SqlClient.SqlConnection.ConnectionString_Set(DbConnectionPoolKey key)
   at Microsoft.Data.SqlClient.SqlConnection.set_ConnectionString(String value)
   at Microsoft.Data.SqlClient.SqlConnection..ctor(String connectionString)
   at Dotmim.Sync.SqlServer.SqlSyncProvider.CreateConnection()
   at Dotmim.Sync.LocalOrchestrator.<GetClientScopeAsync>d__5.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Dotmim.Sync.SyncAgent.<SynchronizeAsync>d__54.MoveNext()

**Information**
IDE and IDE version: Visual Studio 2019 v8.7.4 (Community Edition) MAC (macOS Catalina, version 10.15.6 on a MacBook Pro)
Platform with the issue:
.Net Core Console Application

**Comment by Mimetis** [comment]
closed ?

**Comment by akema-trebla** [comment]
For some strange reason I had the SqlSyncProvider instead of the SqliteSyncProvider on the client
