### ISSUE TITLE
Send is not supported in the Windows Runtime SynchronizationContext

### ISSUE THREAD

**Issue by akema-trebla** [Mimetis/Dotmim.Sync#327]
**Description**
Trying to sync my local sqlite database on Windows UWP throws the error: Send is not supported in the Windows Runtime SynchronizationContext. 

**StackTrace**
`Dotmim.Sync.SyncException: Send is not supported in the Windows Runtime SynchronizationContext ---> System.NotSupportedException: Send is not supported in the Windows Runtime SynchronizationContext
   at System.Threading.WinRTSynchronizationContextBase.Send(SendOrPostCallback d, Object state)
   at Dotmim.Sync.SynchronousProgress`1.OnReport(T value)
   at Dotmim.Sync.SynchronousProgress`1.System.IProgress<T>.Report(T value)
   at Dotmim.Sync.BaseOrchestrator.ReportProgress(SyncContext context, IProgress`1 progress, ProgressArgs args, DbConnection connection, DbTransaction transaction)
   at Dotmim.Sync.LocalOrchestrator.BeginSessionAsync(CancellationToken cancellationToken, IProgress`1 progress)
   at Dotmim.Sync.SyncAgent.SynchronizeAsync(SyncType syncType, CancellationToken cancellationToken, IProgress`1 progress)`

**Extra Info**
I found this in the Microsoft Docs.

```
Exceptions
NotSupportedException
The method was called in a Windows Store app. The implementation of SynchronizationContext for Windows Store apps does not support the Send(SendOrPostCallback, Object) method.
```

https://docs.microsoft.com/en-us/dotnet/api/system.threading.synchronizationcontext.send?view=netcore-3.1

It appears using POST instead of SEND may solve the problem.

https://docs.microsoft.com/en-us/dotnet/api/system.threading.synchronizationcontext.post?view=netcore-3.1

**Information**
IDE and IDE version: Visual Studio 2019 v16.4.4 Windows (Windows 10 Pro, version 1903)
Platform with the issue:
Windows UWP

**Comment by Mimetis** [comment]
Do not use `SynchronousProgress`. It's only used for console application
Use a simple `Progress` instead

**Comment by akema-trebla** [comment]
That solved it. Thanks. I'm really grateful. Keep up the good work.
