### ISSUE TITLE
Microsoft.Data.SqlClient.SqlException (0x80131904): Execution Timeout Expired.

### ISSUE THREAD

**Issue by satpal123** [Mimetis/Dotmim.Sync#334]
Hi,
I'm getting the following error when using batch mode. The batchsize i tried is 2000 and 5000 but I still randomly get the error.

Any suggestion would be appreciated .

Microsoft.Data.SqlClient.SqlException (0x80131904): Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.
 ---> System.ComponentModel.Win32Exception (258): The wait operation timed out.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__164_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Dotmim.Sync.SqlServer.Builders.SqlSyncAdapter.ExecuteBatchCommandAsync(DbCommand cmd, Guid senderScopeId, IEnumerable`1 applyRows, SyncTable schemaChangesTable, SyncTable failedRows, Int64 lastTimestamp, DbConnection connection, DbTransaction transaction)
   at Dotmim.Sync.SyncAdapter.ApplyBulkChangesAsync(Guid localScopeId, Guid senderScopeId, SyncTable changesTable, Int64 lastTimestamp, List`1 conflicts, DbConnection connection, DbTransaction transaction)
   at Dotmim.Sync.CoreProvider.ApplyChangesInternalAsync(SyncTable schemaTable, SyncContext context, MessageApplyChanges message, DbConnection connection, DbTransaction transaction, DataRowState applyType, DatabaseChangesApplied changesApplied, CancellationToken cancellationToken, IProgress`1 progress)
   at Dotmim.Sync.CoreProvider.ApplyChangesAsync(SyncContext context, MessageApplyChanges message, DbConnection connection, DbTransaction transaction, CancellationToken cancellationToken, IProgress`1 progress)
   at Dotmim.Sync.LocalOrchestrator.ApplyChangesAsync(ScopeInfo scope, SyncSet schema, BatchInfo serverBatchInfo, Int64 clientTimestamp, Int64 remoteClientTimestamp, ConflictResolutionPolicy policy, CancellationToken cancellationToken, IProgress`1 progress)

**Comment by Mimetis** [comment]
Is it during the first sync of your client database ?

If yes, you may need to use [Snapshot](https://dotmimsync.readthedocs.io/Snapshot.html) and [Increase your timeout](https://dotmimsync.readthedocs.io/Timeout.html)

**Comment by satpal123** [comment]
> Is it during the first sync of your client database ?
> 
> If yes, you may need to use [Snapshot](https://dotmimsync.readthedocs.io/Snapshot.html) and [Increase your timeout](https://dotmimsync.readthedocs.io/Timeout.html)

Yes its during the first sync. OK thanks I will try the Snapshot and let you know if the issue is resolved. For now i will close this issue.

**Comment by satpal123** [comment]
Ok I tried with the Snapshot which is around 7GB but when its applying to local DB the memory consumption goes sky rocketing and the sync eventually slows down drastically half way. Below is the laptop with 8GB memory 

![image](https://user-images.githubusercontent.com/710270/92717997-83d23900-f3a4-11ea-8b39-9161534de7db.png)

**Comment by Mimetis** [comment]
you have to specify a batch size on both side, for the snapshot size on the server and for the client 

Be sure both have a batchsize set

**Comment by satpal123** [comment]
Yes, the Batch size is specified on both sides. I can see the batch files downloading on the local pc in the temp folder but when it starts applying to the local DB, then it slows downs after 70-80% progress. Then it times out. 

So not sure if anyone else has tried out with a huge database? Now both sides the batch size is 3000. Should I further reduce it?

![image](https://user-images.githubusercontent.com/710270/92727545-a3705e00-f3b2-11ea-8097-7cfcf96c8d24.png)

**Comment by Mimetis** [comment]
That's a huge database :)
Never tested it...
Are you using on both side Sql Server (or are using Sqlite / Mysql) somewhere ?

**Comment by satpal123** [comment]
Both Side is SQL server. Local client has SQL express installed and we have approx 100 Databases and a user can download a database to their local DB for offline usage.

**Comment by captmomo** [comment]
we had a similar issue. the work around was to break up the sync for a database into multiple scopes.

**Comment by satpal123** [comment]
> we had a similar issue. the work around was to break up the sync for a database into multiple scopes.

We have already broken down out 500GB database into approx 100 databases based on different sites. I will look into on how to break it down further.

**Comment by Mimetis** [comment]
Thx @captmomo  & @satpal123  for your feebacks
I will still let this issue opened, because I want to test this scenario deeper

**Comment by satpal123** [comment]
@Mimetis The issue usually happens when the Database have Varbinary data. In our case the table which takes time for initial sync have 2 varbinary columns and if the rows are less than 300,000, then it has no issue. 

I have also noted this happens with laptops having 8GB ram. My laptop has 16gb ram so the initial sync takes approx 10mins to download where as other laptops take more than 6hrs.

**Comment by satpal123** [comment]
@Mimetis I got another test laptop and I did a test using the `IAsyncEnumerable_NetStandard20 ` branch code and below is the time it took

![image](https://user-images.githubusercontent.com/710270/95160552-9d707000-07ec-11eb-9fd1-b396f659916b.png)

With the current 0.5.7 version the result is as below

![Uploading image.png…]()
