### ISSUE TITLE
Force update should always work.. contact the author :)

### ISSUE THREAD

**Issue by anthtoonaing** [Mimetis/Dotmim.Sync#357]
Hi,  what to do with this exception?

this is the log.
```
ChangesSelected:4:00:24 PM.471	 [xxxx] upserts:7389 deletes:2103 total:9492
Force update should always work.. contact the author :)
```

**Comment by Mimetis** [comment]
Well you are facing an issue that ... should never happen actually.
This exception is occurring after a conflict is resolved, and a loosing row is overriden with the winner row

I need more info to help you.
Are you able to reproduce this bug easily ?

**Comment by anthtoonaing** [comment]
I got this error the whole day (my sync service run in every hours). But after network team restarted server for other reason, the error was gone. When I checked the log, I saw timeout issue in one round of sync and I got this error in subsequence rounds.
I am syncing one direction from MsSqlServer to MySql 8.0

```
ChangesSelected:8:17:11 AM.957	 [xxxx] upserts:8177 deletes:2120 total:10297
The Command Timeout expired before the operation completed.
```

**Exception**
```
Dotmim.Sync.SyncException: The Command Timeout expired before the operation completed.
 ---> MySql.Data.MySqlClient.MySqlException (0x80004005): The Command Timeout expired before the operation completed.
 ---> System.IO.IOException: Unable to read data from the transport connection: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond..
 ---> System.Net.Sockets.SocketException (10060): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.Security.SslStream.FillBufferAsync[TReadAdapter](TReadAdapter adapter, Int32 minSize)
   at System.Net.Security.SslStream.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)
   at System.Net.Security.SslStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.Read(Span`1 buffer)
   at MySqlConnector.Protocol.Serialization.StreamByteHandler.<ReadBytesAsync>g__DoReadBytesSync|6_0(Memory`1 buffer_) in C:\projects\mysqlconnector\src\MySqlConnector\Protocol\Serialization\StreamByteHandler.cs:line 50
   at MySqlConnector.Protocol.Serialization.BufferedByteReader.ReadBytesAsync(IByteHandler byteHandler, ArraySegment`1 buffer, Int32 totalBytesToRead, IOBehavior ioBehavior) in C:\projects\mysqlconnector\src\MySqlConnector\Protocol\Serialization\BufferedByteReader.cs:line 36
   at MySqlConnector.Protocol.Serialization.ProtocolUtility.ReadPacketAfterHeader(ReadOnlySpan`1 headerBytes, BufferedByteReader bufferedByteReader, IByteHandler byteHandler, Func`1 getNextSequenceNumber, ProtocolErrorBehavior protocolErrorBehavior, IOBehavior ioBehavior) in C:\projects\mysqlconnector\src\MySqlConnector\Protocol\Serialization\ProtocolUtility.cs:line 434
   at MySqlConnector.Protocol.Serialization.ProtocolUtility.ReadPacketAsync(BufferedByteReader bufferedByteReader, IByteHandler byteHandler, Func`1 getNextSequenceNumber, ProtocolErrorBehavior protocolErrorBehavior, IOBehavior ioBehavior) in C:\projects\mysqlconnector\src\MySqlConnector\Protocol\Serialization\ProtocolUtility.cs:line 409
   at MySqlConnector.Protocol.Serialization.ProtocolUtility.DoReadPayloadAsync(BufferedByteReader bufferedByteReader, IByteHandler byteHandler, Func`1 getNextSequenceNumber, ArraySegmentHolder`1 previousPayloads, ProtocolErrorBehavior protocolErrorBehavior, IOBehavior ioBehavior) in C:\projects\mysqlconnector\src\MySqlConnector\Protocol\Serialization\ProtocolUtility.cs:line 467
   at MySqlConnector.Protocol.Serialization.ProtocolUtility.ReadPayloadAsync(BufferedByteReader bufferedByteReader, IByteHandler byteHandler, Func`1 getNextSequenceNumber, ArraySegmentHolder`1 cache, ProtocolErrorBehavior protocolErrorBehavior, IOBehavior ioBehavior) in C:\projects\mysqlconnector\src\MySqlConnector\Protocol\Serialization\ProtocolUtility.cs:line 462
   at MySqlConnector.Protocol.Serialization.StandardPayloadHandler.ReadPayloadAsync(ArraySegmentHolder`1 cache, ProtocolErrorBehavior protocolErrorBehavior, IOBehavior ioBehavior) in C:\projects\mysqlconnector\src\MySqlConnector\Protocol\Serialization\StandardPayloadHandler.cs:line 42
   at MySqlConnector.Core.ServerSession.ReceiveReplyAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ServerSession.cs:line 736
--- End of stack trace from previous location where exception was thrown ---
   at MySqlConnector.Core.ServerSession.ReceiveReplyAsyncAwaited(ValueTask`1 task) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ServerSession.cs:line 764
   at MySqlConnector.Core.ResultSet.<ScanRowAsync>g__ScanRowAsyncAwaited|9_0(ResultSet this_, Task`1 payloadTask, Row row_, CancellationToken token) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ResultSet.cs:line 246
   at MySqlConnector.Core.ResultSet.BufferReadAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ResultSet.cs:line 221
   at MySqlConnector.Core.ResultSet.get_HasRows() in C:\projects\mysqlconnector\src\MySqlConnector\Core\ResultSet.cs:line 397
   at MySql.Data.MySqlClient.MySqlDataReader.get_HasRows() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 199
   at Dotmim.Sync.MySql.MySqlScopeInfoBuilder.GetAllServerScopesAsync(String scopeName, DbConnection connection, DbTransaction transaction) in C:\projs\DataSync\Libraries\Dotmim.Sync\Dotmim.Sync.MySql\Builders\MySqlScopeInfoBuilder.cs:line 202
   at Dotmim.Sync.CoreProvider.GetServerScopeAsync(SyncContext context, String scopeInfoTableName, String scopeName, DbConnection connection, DbTransaction transaction, CancellationToken cancellationToken, IProgress`1 progress) in C:\projs\DataSync\Libraries\Dotmim.Sync\Dotmim.Sync.Core\CoreProvider.Scopes.cs:line 235
   at Dotmim.Sync.RemoteOrchestrator.ApplyThenGetChangesAsync(ScopeInfo clientScope, BatchInfo clientBatchInfo, CancellationToken cancellationToken, IProgress`1 progress) in C:\projs\DataSync\Libraries\Dotmim.Sync\Dotmim.Sync.Core\Orchestrators\RemoteOrchestrator.cs:line 575
   --- End of inner exception stack trace ---
   at Dotmim.Sync.BaseOrchestrator.RaiseError(Exception exception) in C:\projs\DataSync\Libraries\Dotmim.Sync\Dotmim.Sync.Core\Orchestrators\BaseOrchestrator.cs:line 208
   at Dotmim.Sync.RemoteOrchestrator.ApplyThenGetChangesAsync(ScopeInfo clientScope, BatchInfo clientBatchInfo, CancellationToken cancellationToken, IProgress`1 progress) in C:\projs\DataSync\Libraries\Dotmim.Sync\Dotmim.Sync.Core\Orchestrators\RemoteOrchestrator.cs:line 677
   at Dotmim.Sync.SyncAgent.SynchronizeAsync(SyncType syncType, CancellationToken cancellationToken, IProgress`1 progress) in C:\projs\DataSync\Libraries\Dotmim.Sync\Dotmim.Sync.Core\SyncAgent.cs:line 541
   at DataSync.Service.DataSynchronizer.Run() in C:\projs\DataSync\DataSync.Service\DataSynchronizer.cs:line 46
```

**Comment by anthtoonaing** [comment]
I have monitored last 10 days and it won't happen again. Not able to reproduce that error.
