### ISSUE TITLE
Error "Source array was not long enough"

### ISSUE THREAD

**Issue by UweKeim** [Mimetis/Dotmim.Sync#361]
Currently doing my first steps with Dotmin.Sync, I'm doing a sync via ASP.NET Core WebApi.

Some tables sync successfully, even with conflicts (that get resolved automatically), but one table, as soon as there are changes on both sides, there comes up an error:

> Error: Source array was not long enough. Check the source index, length, and the array's lower bounds. (Parameter 'sourceArray') 

With this call stack:

```
Dotmim.Sync.SyncException: Source array was not long enough. Check the source index, length, and the array's lower bounds. (Parameter 'sourceArray')
   at Dotmim.Sync.Web.Client.HttpRequestHandler.HandleSyncError(HttpResponseMessage response, ISerializerFactory serializerFactory)
   at Dotmim.Sync.Web.Client.HttpRequestHandler.ProcessRequestAsync[U](HttpClient client, String baseUri, Byte[] data, HttpStep step, Guid sessionId, String scopeName, ISerializerFactory serializerFactory, IConverter converter, Int32 batchSize, CancellationToken cancellationToken)
   at Dotmim.Sync.Web.Client.WebClientOrchestrator.ApplyThenGetChangesAsync(ScopeInfo scope, BatchInfo clientBatchInfo, CancellationToken cancellationToken, IProgress`1 progress)
   at Dotmim.Sync.SyncAgent.SynchronizeAsync(SyncType syncType, CancellationToken cancellationToken, IProgress`1 progress)
```

I hope I do did not do a configuration error.

### My question

Any Idea what could cause this error and how to resolve this?

**Comment by Mimetis** [comment]
No idea, can you share a simple repro ?

**Comment by UweKeim** [comment]
Thanks, @Mimetis. I've postponed my work with your library a little bit, until #354 is fixed to allow me to work with this in my real environment.

Maybe I'm simply using it wrong. I better close this issue for now.

**Comment by Mimetis** [comment]
I'm working on it today.
I will let you know once I've pushed a beta version of it
