### ISSUE TITLE
SqlVariant type syncronize exception

### ISSUE THREAD

**Issue by tothmartonjeno** [Mimetis/Dotmim.Sync#380]
Hi!

I have the following problem when I try synchronize from sql server to sqlite client with snapshot in http mode:
SQLServer database
table def:
`CREATE TABLE [dbo].[KuldemenyLogDetails](
	[KuldemenyLogDetailsID] [uniqueidentifier] NOT NULL,
	[KuldemenyLogHeaderID] [uniqueidentifier] NOT NULL,
	[KuldemenyLogDataID] [int] NOT NULL,
	[OldValue] [sql_variant] NOT NULL,
	[NewValue] [sql_variant] NOT NULL,
 CONSTRAINT [PK_KuldemenyLogDetails] PRIMARY KEY CLUSTERED 
(
	[KuldemenyLogDetailsID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO`

SyncSetup: uploadonly
SyncOptions: snapshot
mode: http

On the client side call:
`var s = await agent.SynchronizeAsync(progress);`

throws an exception:
`ChangesSelected:        17:57:49.746     [main] upserts:0 deletes:0 total:0
ERROR MESSAGE: The type Object is not supported
TRACE:   at Dotmim.Sync.Web.Client.HttpRequestHandler.HandleSyncError(HttpResponseMessage response, ISerializerFactory serializerFactory)
   at Dotmim.Sync.Web.Client.HttpRequestHandler.ProcessRequestAsync[U](HttpClient client, String baseUri, Byte[] data, HttpStep step, Guid sessionId, String scopeName, ISerializerFactory serializerFactory, IConverter converter, Int32 batchSize, CancellationToken cancellationToken)
   at Dotmim.Sync.Web.Client.WebClientOrchestrator.GetSnapshotAsync(SyncSet schema, CancellationToken cancellationToken, IProgress`1 progress)
   at Dotmim.Sync.SyncAgent.SynchronizeAsync(SyncType syncType, CancellationToken cancellationToken, IProgress`1 progress)`

Without snapshot + http + sql variant type -> o.k.
snapshot + tcp + sql variant type -> o.k.
snapshot + http + not sql variant tpye -> o.k.

**Comment by Mimetis** [comment]
Thanks for this issue report @tothmartonjeno, will look into it asap

**Comment by Mimetis** [comment]
Hey @tothmartonjeno, this issue will be fixed in the next release `v0.6`
Yo may expect to have a beta version to test really soon, hopefully :)
