### ISSUE TITLE
MariaDB SQL syntax error near INTO sync_row_count

### ISSUE THREAD

**Issue by CodingTarik** [Mimetis/Dotmim.Sync#395]
Hello✋

I have a MariaDB Database that I want to sync with a SQLite database. 

I have the following SyncMethod
```csharp
public static async Task<string> SyncAsync(IProgress<ProgressArgs> progress)
{
            // Create serverprovider and sync agent
            LogManager.log("Creating server provider and synchronization provider for synchronization", LogCategory.info, LogTopic.Database);
            CoreProvider serverProvider;
            if(Settings.Settings.useMariaDB)
            {
                LogManager.log("Using MariaDB Provider", LogCategory.info, LogTopic.Database);
                serverProvider = new MariaDBSyncProvider(Settings.Settings.MYSQLConnectionString);
            }
            else
            {
                LogManager.log("Using MySQL Provider", LogCategory.info, LogTopic.Database);
                serverProvider = new MySqlSyncProvider(Settings.Settings.MYSQLConnectionString);
            }   
            SyncAgent agent = new SyncAgent(clientProvider, serverProvider, tables);
            SyncResult result = null;
            // Synchronize
            LogManager.log("Synchronizing data with sync agent", LogCategory.info, LogTopic.Database);
            if (progress != null)
            {
                result = await agent.SynchronizeAsync(progress);
            }
            else
            {
                result = await agent.SynchronizeAsync();
            }
            LogManager.log("Sync-Result: " + result.ToString());
            return result.ToString();
}
```

As you can see I tried both the MySQLSyncProvider and MariaDBSyncProvider. Both with the same Exception "SQL Syntax Error"
Here is the Stackstace

```
[21:43:02][ERROR][Login][LoginButton_Click]:Error synchronizing database at login
 ---> You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'INTO sync_row_count;
IF (sync_row_count = 0) THEN
	INSERT  INTO `Pangolins`...' at line 56
-Stacktrace-
   at Dotmim.Sync.BaseOrchestrator.RaiseError(Exception exception)
   at Dotmim.Sync.BaseOrchestrator.RunInTransactionAsync[T](SyncStage stage, Func`4 actionTask, CancellationToken cancellationToken)
   at Dotmim.Sync.BaseOrchestrator.RunInTransactionAsync[T](SyncStage stage, Func`4 actionTask, CancellationToken cancellationToken)
   at Dotmim.Sync.SyncAgent.SynchronizeAsync(SyncType syncType, CancellationToken cancellationToken, IProgress`1 progress)
   at Pangolin_Database_App.Database.DatabaseSync.SyncAsync(IProgress`1 progress) in D:\Programmierprojekte\Pangolin\Pangolin Database-App\Database\DatabaseSync.cs:line 61
   at Pangolin_Database_App.User_Controls.Login.PasswordView.LoginButton_Click(Object sender, RoutedEventArgs e) in D:\Programmierprojekte\Pangolin\Pangolin Database-App\User Controls\Login\PasswordView.xaml.cs:line 57
Called in D:\Programmierprojekte\Pangolin\Pangolin Database-App\User Controls\Login\PasswordView.xaml.cs at line 62
```

I couldn't figure out why and how this error happens, so I think it is probably an issue with the sync framework itself.

Many thanks in advance.

**Comment by Mimetis** [comment]
Can you share the `Pangolins` schema ?

**Comment by CodingTarik** [comment]
Here is the Panngolins schema:

```SQL
CREATE TABLE `Pangolins` (
 `PangolinID` int(11) NOT NULL AUTO_INCREMENT,
 `ReferenceNumber` varchar(255) NOT NULL,
 `OfficialDocumentReference` longtext NOT NULL,
 `Name` longtext NOT NULL,
 `Gender` int(11) NOT NULL,
 `Weight` double NOT NULL,
 `ParasitesPresent` tinyint(1) NOT NULL,
 `ApproxAge` longtext DEFAULT NULL,
 `HealthState` int(11) NOT NULL,
 `DetailsOfReceiving` longtext DEFAULT NULL,
 `AreaOriginallyFrom` longtext DEFAULT NULL,
 `TimeInCaptivity` double NOT NULL,
 `ModeOfTransport` longtext DEFAULT NULL,
 `AuhtoritivePointOfContact` longtext DEFAULT NULL,
 `DistinguishingMarks` longtext DEFAULT NULL,
 `CriminalCase` tinyint(1) NOT NULL,
 `Date` datetime(6) NOT NULL,
 `Time` datetime(6) NOT NULL,
 PRIMARY KEY (`PangolinID`),
 UNIQUE KEY `IX_Pangolins_ReferenceNumber` (`ReferenceNumber`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
````

**Comment by Mimetis** [comment]
Which version of MariaDB are you using ?

**Comment by CodingTarik** [comment]
That was the mistake. The Debian repository didn't seem to have the latest version of MariaDB, so I still had 10.3.27. I then manually added the MariaDB repository and updated to 10.4.17. Now everything works. Thanks for the help.👍

**Comment by Mimetis** [comment]
Nice !
