### ISSUE TITLE
HTTP Error 413.1 - Request Entity Too Large

### ISSUE THREAD

**Issue by VagueGit** [Mimetis/Dotmim.Sync#398]
Initial sync of a 500mb SQLite database to an Azure SQL Database. All data going up, none down. I seem to be able to sync a few hundred rows, but with ~30k rows, `HTTP Error 413.1 - Request Entity Too Large` throws intermittently from the sync rest api when I call
`SyncResult syncResult = await syncAgent.SynchronizeAsync();`

On the client I have 
```
SyncOptions syncOptions = new SyncOptions();
syncOptions.CleanMetadatas = true; 
syncOptions.BatchSize = 2000; 
syncOptions.UseBulkOperations = true;
clientProvider.Options = syncOptions;
```
I'm trying to enable large requests every which way on the server:
in `Web.Config`
```
<security>
  <requestFiltering>
    <!-- This will handle requests up to 50MB -->
    <requestLimits maxAllowedContentLength="52428800" />
  </requestFiltering>
</security>
</system.webServer>

```

and `SyncController`
```
[HttpPost]
[RequestSizeLimit(52428800)]
public async Task Post(string databaseName)

```

The first large table sync fails on is Customers with 15 columns and 35k rows. On some tests this syncs successfully. The Orders table sometimes syncs successfully 89k rows, sometimes not.

What else do I need to configure to make sync of large tables more robust?

EDIT 1: The rest api is a NET 5 Azure web app.

EDIT 2: Another sync exception that sometimes throws when there are many rows is `The page was not displayed because the request entity is too large.`

Stack trace:
```
   at Dotmim.Sync.Web.Client.HttpRequestHandler.<HandleSyncError>d__12.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dotmim.Sync.Web.Client.HttpRequestHandler.<ProcessRequestAsync>d__10`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dotmim.Sync.Web.Client.WebClientOrchestrator.<ApplyThenGetChangesAsync>d__34.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Dotmim.Sync.SyncAgent.<SynchronizeAsync>d__54.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Wbl.Services.DataService.<SyncNowAsync>d__30.MoveNext() in C:\Repos\v11\Wbl\Services\DataService.cs:line 150
```

**Comment by Mimetis** [comment]
It will be quite hard for me to test your use case.
Are you able to share a really simple repro project that trigger the problem ?

**Comment by VagueGit** [comment]
I don't know how to share a repo without exposing credentials.

Are there known circumstances where DMS can send a request that is too large for a web api?

Is there anything I can do to reduce the size of the request by DMS, or anything more I can do to make the api more resilient to DMS requests?

**Comment by Mimetis** [comment]
The only thing that can prevent DMS to send a request is IF ONE row is bigger than the max request size
`DMS` can't go less than 1 full row.

Yo have the code here, where `DMS` tries to ensure that the row is always less then the `BatchSsize` size.

https://github.com/Mimetis/Dotmim.Sync/blob/83295ee889351e8fe4e7b286cab8bdbf4cc8bcd0/Projects/Dotmim.Sync.Core/CoreProvider.GetChanges.cs#L128-L132

**Comment by VagueGit** [comment]
Thanks for the tip. Getting very late here so will post back tmw.

**Comment by VagueGit** [comment]
I have changed my code to call
`SyncAgent syncAgent = new SyncAgent(clientProvider, webClientOrchestrator,clientProvider.Options);` Which correctly returns `syncAgent.Options.BatchSize=2000`

This seems to have fixed the issue. Thank you for your assistance.

**Comment by Mimetis** [comment]
oh wow, so I guess the problem is coming from `clientProvider.Options = syncOptions;`
The `SyncAgent` will override the `Options` on each provider / orchestrators.
Maybe I should do something to not allow passing a syncoptions, other than in the SyncAgent

Thanks @VagueGit for the feedback !
