### ISSUE TITLE
SynchronizeAsync trying to insert null in non nullable column 

### ISSUE THREAD

**Issue by radulacatus** [Mimetis/Dotmim.Sync#425]
Setup:
- download only
- source db SqlServer
- destination db Sqlite
- initial sync (empty destination db)

Other details
- Could not reproduce on other environments/databases.
- On the same environment, i could reproduce it also for SqlServer destination db

Issue:
- When triggering the initial sync, schema is correctly replicated on destination db
- When trying to sync the rows, an insert statement runs trying to insert a NULL value in a non nullable column (which obviously has value on the source db (column type: bit not null)
- Call stack:
Unhandled exception. Dotmim.Sync.SyncException: SQLite Error 19: 'NOT NULL constraint failed: <not nullable column>'.
 ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'NOT NULL constraint failed: <not nullable column>'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at System.Data.Common.DbCommand.ExecuteNonQueryAsync(CancellationToken cancellationToken)
   
  Mitigation:
  - I tried clearing the change tracking cache on the source db => did not work
  - i tried disabling and enabling change tracking on the source db => did not work
  - i updated the dotmim nuget packages from 0.5.7 to 0.6.0 => problem stopped reproducing
  - i downgraded again (just for testing purposes) from 0.6.0 to  0.5.7 => problem stopped reproducing (issue did not come back)
  
  We could not identify a root cause.
  We are currently running with 0.6.0 and the issue is not reproducing anymore, but still it would be nice to identify/reproduce the issue in order to lower the stability concerns.

**Comment by Mimetis** [comment]
Thanks for the report.
As you say, will be hard to debug if you are not able to reproduce it.
If you find a way to create a simple repro, let me know !

**Comment by mrtncls** [comment]
Hello, I'm a collegue of Radu.

The issue appeared again after a migraton on our source db.

Our scenario:
 - Both db's use ChangeTracking
 - In case of a db migration, we want to drop the target db and reinitialize the target db (like downloading a copy with latest schema).

Thoughts:
 - The record causing the exception is using the previous schema. So, the record was stored somewhere. Probably in the changetracking cache? How can we clear it?
 - Shouldn't a SyncType.Reinitialize do this clearing for us?

Here are the steps to reproduce the issue on the sample database:

1. Run sql script on SQL server https://raw.githubusercontent.com/Mimetis/Dotmim.Sync/master/CreateAdventureWorks.sql
1. Enable ChangeTracking
    ```sql
    Alter database AdventureWorks SET CHANGE_TRACKING = ON (CHANGE_RETENTION = 14 DAYS, AUTO_CLEANUP = ON)
    Alter database Client SET CHANGE_TRACKING = ON (CHANGE_RETENTION = 14 DAYS, AUTO_CLEANUP = ON)
    ```
1. Run demo app with ChangeTracking providers
    ```c#
    // Sql Server provider, the "server" or "hub".
    SqlSyncChangeTrackingProvider serverProvider = new SqlSyncChangeTrackingProvider("Data Source=(LocalDb)\\MSSQLLocalDb;Initial Catalog=AdventureWorks;User ID=user;Password=user;");

    // Sqlite Client provider acting as the "client"
    SqlSyncChangeTrackingProvider clientProvider = new SqlSyncChangeTrackingProvider("Data Source=(LocalDb)\\MSSQLLocalDb;Initial Catalog=Client;User ID=user;Password=user;");

    // Tables involved in the sync process:
    var tables = new string[] {"ProductCategory", "ProductDescription", "ProductModel", "Product", "ProductModelProductDescription",
                    "Address", "Customer", "CustomerAddress", "SalesOrderHeader", "SalesOrderDetail" };

    // Sync agent
    SyncAgent agent = new SyncAgent(clientProvider, serverProvider, tables);

    Console.WriteLine("Initial sync...");
    var result = await agent.SynchronizeAsync(SyncType.Reinitialize);
    Console.WriteLine(result);

    Console.WriteLine("Sleep 10s...");
    await Task.Delay(TimeSpan.FromSeconds(10));

    Console.WriteLine("Normal sync...");
    await agent.SynchronizeAsync(SyncType.Normal);
    Console.WriteLine(result);

    Console.WriteLine("Done. Press enter to quit");
    Console.ReadLine();
    ```
    Sync will run fine and produces this output:
    ```log
    Initial sync...
    Synchronization done.
            Total changes  uploaded: 0
            Total changes  downloaded: 4276
            Total changes  applied: 4276
            Total resolved conflicts: 0
            Total duration :0:0:7.732
    Sleep 10s...
    Normal sync...
    Synchronization done.
            Total changes  uploaded: 0
            Total changes  downloaded: 4276
            Total changes  applied: 4276
            Total resolved conflicts: 0
            Total duration :0:0:7.732
    Done. Press enter to quit
    ```
1. Add record and apply migration (add a column)
    ```sql
    USE [AdventureWorks]
    INSERT INTO [dbo].[Address]
            ([AddressLine1]
            ,[AddressLine2]
            ,[City]
            ,[StateProvince]
            ,[CountryRegion]
            ,[PostalCode]
            ,[rowguid]
            ,[ModifiedDate])
        VALUES
            ('L1'
            ,'L2'
            ,'City'
            ,'State'
            ,'Country'
            ,'1111'
            ,'BAD7B2CE-078F-4D5A-8A1A-C8FDC5A6D5BD'
            ,CAST('2007-05-08 12:35:29.123' AS datetime))


    ALTER TABLE [dbo].[Address] ADD NewColumn int NOT NULL DEFAULT 0
    ```    
1. After the migration, we want to start the sync on the client from scratch. So, we drop the client db, reset ChangeTracking on source and drop the scopeinfo tables.
    ```sql
    -- Client database. No need to create the schema, Dotmim.Sync will do
    if (exists (select * from sys.databases where name = 'Client'))
    begin
        ALTER DATABASE [Client] SET  SINGLE_USER WITH ROLLBACK IMMEDIATE;
        DROP DATABASE [Client]
    End
    Create database [Client]
    GO

    USE [AdventureWorks]
    ALTER TABLE ProductCategory DISABLE CHANGE_TRACKING;
    ALTER TABLE ProductDescription DISABLE CHANGE_TRACKING;
    ALTER TABLE ProductModel DISABLE CHANGE_TRACKING;
    ALTER TABLE Product DISABLE CHANGE_TRACKING;
    ALTER TABLE ProductModelProductDescription DISABLE CHANGE_TRACKING;
    ALTER TABLE Address DISABLE CHANGE_TRACKING;
    ALTER TABLE Customer DISABLE CHANGE_TRACKING;
    ALTER TABLE CustomerAddress DISABLE CHANGE_TRACKING;
    ALTER TABLE SalesOrderHeader DISABLE CHANGE_TRACKING;
    ALTER TABLE SalesOrderDetail DISABLE CHANGE_TRACKING;

    Alter database AdventureWorks SET CHANGE_TRACKING = OFF;

    DROP TABLE scope_info_history;
    DROP TABLE scope_info_server;
    ```
1. Run activate ChangeTracking script again
1. Run application again. The following exception will be thrown from the initial sync.
    ```exception
    Cannot insert the value NULL into column 'NewColumn', table 'Client.dbo.Address'; column does not allow nulls. UPDATE fails.
    The statement has been terminated.
    at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__188_0(Task`1 result)
    at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at Dotmim.Sync.SqlServer.Builders.SqlSyncAdapter.<ExecuteBatchCommandAsync>d__5.MoveNext()
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    at Dotmim.Sync.BaseOrchestrator.<>c__DisplayClass5_0.<<InternalApplyChangesBatchAsync>b__0>d.MoveNext()
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at Dotmim.Sync.BaseOrchestrator.<InternalApplyChangesBatchAsync>d__5.MoveNext()
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    at Dotmim.Sync.BaseOrchestrator.<InternalApplyTableChangesAsync>d__4.MoveNext()
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    at Dotmim.Sync.BaseOrchestrator.<InternalApplyChangesAsync>d__0.MoveNext()
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
    at Dotmim.Sync.LocalOrchestrator.<>c__DisplayClass7_0.<<ApplyChangesAsync>b__0>d.MoveNext()
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
    at Dotmim.Sync.BaseOrchestrator.<RunInTransactionAsync>d__67`1.MoveNext()
    ```

**Comment by mrtncls** [comment]
We've added a Deprovision step before recreating the client db.
We no longer manually disable changetracking per table any longer (deprovision is doing this).
And we no longer drop the scope info tables (but are nulled by the deprovision).
Is this the correct approach?
Can you explain what the difference is between the deprovision and the manual steps we did?

The deprovision code:

```c#
            var serverScope = await agent.RemoteOrchestrator.GetServerScopeAsync();

            await agent.RemoteOrchestrator.DeprovisionAsync(SyncProvision.StoredProcedures | SyncProvision.Triggers | SyncProvision.TrackingTable);

            serverScope.Setup = null;
            serverScope.Schema = null;

            await agent.RemoteOrchestrator.SaveServerScopeAsync(serverScope);
```

**Comment by Mimetis** [comment]
Deprovision drop the objects you mentioned in the args : Stored Proc, Triggers and Tracking tables
Since you are using change tracking, there is no trigger and no tracking table

So far your code ` await agent.RemoteOrchestrator.DeprovisionAsync(SyncProvision.StoredProcedures | SyncProvision.Triggers | SyncProvision.TrackingTable);` will just remove the stored procs.

It will not remove the Change Tracking

**Comment by mrtncls** [comment]
So, it were the stored procedures that were left behind and not overwritten on the next reinitialize sync.
Thanks for clarifying.

**Comment by mrtncls** [comment]
When doing a sync after deprovisioning, we get this exception:

```
   Table {tablename} has no columns.

      at Dotmim.Sync.BaseOrchestrator.<InternalCreateTrackingTableAsync>d__141.MoveNext() in C:\src\Capacity\DotMimSync\Dotmim.Sync\Projects\Dotmim.Sync.Core\Orchestrators\BaseOrchestrator.TrackingTable.cs:line 203
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Dotmim.Sync.BaseOrchestrator.<InternalProvisionAsync>d__86.MoveNext() in C:\src\Capacity\DotMimSync\Dotmim.Sync\Projects\Dotmim.Sync.Core\Orchestrators\BaseOrchestrator.Provision.cs:line 187
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Dotmim.Sync.RemoteOrchestrator.<>c__DisplayClass3_0.<<EnsureSchemaAsync>b__0>d.MoveNext() in C:\src\Capacity\DotMimSync\Dotmim.Sync\Projects\Dotmim.Sync.Core\Orchestrators\RemoteOrchestrator.cs:line 86
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Dotmim.Sync.BaseOrchestrator.<RunInTransactionAsync>d__67`1.MoveNext() in C:\src\Capacity\DotMimSync\Dotmim.Sync\Projects\Dotmim.Sync.Core\Orchestrators\BaseOrchestrator.cs:line 470
```

Issue comes from the tableBuilders static cache. Because it's already cached and the key is the same, the same builder will be used (which doens't have columns loaded).

As a workaround, we've appended a semicolon to the connectionstring to produce a different key in the cache. This resolves the exception when we call the syncAgent.SynchronizeAsync.

Example code:

```c#
            SyncAgent agent = new SyncAgent(clientProvider, serverProvider, tables);

            // Deprovision
            var ochestrator = agent.RemoteOrchestrator;
            var serverScope = await ochestrator.GetServerScopeAsync();
            await ochestrator.DeprovisionAsync(SyncProvision.StoredProcedures | SyncProvision.Triggers | SyncProvision.TrackingTable);
            serverScope.Setup = null;
            serverScope.Schema = null;
            await ochestrator.SaveServerScopeAsync(serverScope);

            // workaround for "Table {tablename} has no columns" exception
            serverProvider = new SqlSyncChangeTrackingProvider(serverProvider.ConnectionString + ";");
            agent = new SyncAgent(clientProvider, serverProvider, tables);

            Console.WriteLine("Initial sync...");
            var result = await agent.SynchronizeAsync(SyncType.Reinitialize);
            Console.WriteLine(result);
```

Is this a bug?

**Comment by Mimetis** [comment]
Yes, it's a bug, the table builders cache have been removed in the next upcoming version (`v0.6.2`) to avoid this kind of issue
