### ISSUE TITLE
Unable to StrongName the package since version 0.6.3-beta-0587

### ISSUE THREAD

**Issue by MaTToX3** [Mimetis/Dotmim.Sync#508]
In our solution we have to strongly name every 3rd-party package we use. For that, we use another [Nuget package](https://www.nuget.org/packages/strongnamer). Since the version **0.6.3-beta-0587**, we can no longer use your package in our solution since we are getting the following exception when building:

```
Failed to write signed assembly to 'PROJECT_PATH\obj\Debug\net5.0\SignedAssemblies\Dotmim.Sync.Core.dll'. Mono.Cecil.ResolutionException: Failed to resolve System.Reflection.BindingFlags
   at Mono.Cecil.Mixin.CheckedResolve(TypeReference self)
   at Mono.Cecil.MetadataBuilder.GetConstantType(TypeReference constant_type, Object constant)
   at Mono.Cecil.MetadataBuilder.AddConstant(IConstantProvider owner, TypeReference type)
   at Mono.Cecil.MetadataBuilder.AddParameter(UInt16 sequence, ParameterDefinition parameter, ParamTable table)
   at Mono.Cecil.MetadataBuilder.AddParameters(MethodDefinition method)
   at Mono.Cecil.MetadataBuilder.AddMethod(MethodDefinition method)
   at Mono.Cecil.MetadataBuilder.AddMethods(TypeDefinition type)
   at Mono.Cecil.MetadataBuilder.AddType(TypeDefinition type)
   at Mono.Cecil.MetadataBuilder.AddTypes()
   at Mono.Cecil.MetadataBuilder.BuildTypes()
   at Mono.Cecil.MetadataBuilder.BuildModule()
   at Mono.Cecil.MetadataBuilder.BuildMetadata()
   at Mono.Cecil.ModuleWriter.<>c.<BuildMetadata>b__2_0(MetadataBuilder builder, MetadataReader _)
   at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TItem item, Func`3 read)
   at Mono.Cecil.ModuleWriter.BuildMetadata(ModuleDefinition module, MetadataBuilder metadata)
   at Mono.Cecil.ModuleWriter.Write(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
   at Mono.Cecil.ModuleWriter.WriteModule(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
   at Mono.Cecil.ModuleDefinition.Write(String fileName, WriterParameters parameters)
   at StrongNamer.AddStrongName.ProcessAssembly(ITaskItem assemblyItem, Byte[] keyBytes, StrongNamerAssemblyResolver resolver)
```

The exception is probably irrelevant for you, however I would like to identify, what causes the exception in our solution.
The last version, that works normally, is version 0.6.3-beta-0540. I went trough commits that were done 20 or more days ago to see, what has changed but was unable to find anything, that could help me solve our issue. Any ideas on your side maybe?

Also, it would be great, if you would tag the releases. :)

Repository: 
[WebApplication1.zip](https://github.com/Mimetis/Dotmim.Sync/files/6188721/WebApplication1.zip)

Thanks in advance!

**Comment by Mimetis** [comment]
Can I do something to help you ?

**Comment by MaTToX3** [comment]
Don't know, is there any specific change after the version 0.6.3-beta-0540 that could trigger such behavior? I could not find anything.

**Comment by Mimetis** [comment]
maybe mutli platform compilation ? (to be compatible with .net5, .net core 3.1 and .net standard 2.0)

**Comment by MaTToX3** [comment]
Closing as it's not really the issue for the library. Will re-open if I find anything new. Thank you!
