### ISSUE TITLE
The stream does not support writing

### ISSUE THREAD

**Issue by VagueGit** [Mimetis/Dotmim.Sync#538]
This exception has popped up beginning a sync to a new device. `The stream does not support writing`.

The stack trace
```
   at Dotmim.Sync.Web.Client.HttpRequestHandler.<HandleSyncError>d__15.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dotmim.Sync.Web.Client.HttpRequestHandler.<SendAsync>d__14.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Dotmim.Sync.SyncPolicy.<InternalExecuteAsync>d__17`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dotmim.Sync.Web.Client.HttpRequestHandler.<ProcessRequestAsync>d__12.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dotmim.Sync.Web.Client.WebClientOrchestrator.<EnsureSchemaAsync>d__35.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dotmim.Sync.SyncAgent.<>c__DisplayClass53_0.<<SynchronizeAsync>b__0>d.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dotmim.Sync.SyncAgent.<SynchronizeAsync>d__53.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Wbl.Services.DataService.<SyncNowAsync>d__28.MoveNext() in C:\Repos\FREE\Wbl\Services\DataService.cs:line 128
```

DMS creates the local SQLite database, usually as a copy of the SQL Server database, over http. In this case the local SQLite database is not completed by DMS. It has only a single table `scope_info` showing the value `DefaultScope`, then it throws this exception.

We have `DMS 0.8.0` on the client and the web server. Rebooting the client PC didn't help. We've also cleaned up and restarted the web server in case there were resource issues there. This issue has since been replicated on another machine trying to do a new install.

Where do we look next?

**Comment by Mimetis** [comment]
The `EnsureSchema` method is the first method called by DMS using a http connection.

Not, sure but I guess you do not have access to your server from your device.

Are you able to reach the sync endpoint from your device ?

**Comment by VagueGit** [comment]
Using Postman Post to https://mysite/api/sync returns 200 OK

**Comment by VagueGit** [comment]
We're getting the same issue from offices in different parts of the world

**Comment by Mimetis** [comment]
are you using interceptors or any custom code when initializing a new client ?

**Comment by VagueGit** [comment]
No we just sync all tables. Our sync setup hasn't changed. It now seems it isn't only when initialising new clients; Sync generally is failing.

I thought maybe it was to do with upgrading to DMS 0.8

**Comment by Mimetis** [comment]
are you able to reproduce this issue with a sample ?

**Comment by Mimetis** [comment]
Are you on `v0.8.0` on the server as well ?
Can you check the content of `[scope_info_server]` on the server and `[scope_info]` on the client ?

**Comment by VagueGit** [comment]
Same version on the client and the web server. The web server also has `Dotmim.Sync.SqlServer.ChangeTracking 0.8.0`

But there is no `[scope_info_server]` table on the server and the tables don't have any triggers. Database properties show change tracking is on.

**Comment by Mimetis** [comment]
NO Table `[scope_info_server]` on the server ???

In any sync, on the server side, you MUST have these tables `scope_info_history` and `scope_info_server` (even if you are on change tracking mode) : 

It's nearly impossible (at least i never tried) to make DMS works without these tables.

![image](https://user-images.githubusercontent.com/4592555/115233958-d0d77400-a118-11eb-8aa0-aac6f6caa3fb.png)

**Comment by VagueGit** [comment]
I'll wind back DMS on the client and server when I get into work today and post back here.

**Comment by VagueGit** [comment]
I have exciting news! I wound back to `DMS 0.7.3`. The first sync threw an exception with the message `trigger table_name_Update already exists`.

The test database I use has update triggers using the convention `table_name_Update`.

It seems DMS naming for triggers conflicts with this convention. The problem went away when I changed the naming convention for triggers on this test database. I was then able to upgrade to `DMS 0.8.0` without issue.

It is interesting that `DMS 0.7.3` returned a more helpful message for this exception than `DMS 0.8.0`.

I'll close this issue. Thank you for your assistance @Mimetis

**Comment by Mimetis** [comment]
That's strange...
I will try to make more tests on this particular situation.

good job
