### ISSUE TITLE
SqlSyncChangeTrackingProvider using on SQLServer 2019 cause table lock with _bulkdelete procedure

### ISSUE THREAD

**Issue by tamdtvn** [Mimetis/Dotmim.Sync#577]
Hi,

Recently, I test applying Change Tracking of SQL Server 2019 by using SqlSyncChangeTrackingProvider as the document. But  **_bulkdelete** causes table locking and sometimes DMS throws exception 'Invalid Object ... _tracking table'. Here is my case in **_bulkdelete** procedure:
`SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[TopssPartBoFollowUpSync_bulkdelete]
	@sync_min_timestamp bigint,
	@sync_scope_id uniqueidentifier,
	@changeTable [dbo].[TopssPartBoFollowUpSync_BulkType] READONLY
AS
BEGIN
-- use a temp table to store the list of PKs that successfully got deleted
declare @dms_changed TABLE ([Id] [bigint],  PRIMARY KEY ( [Id]));

DECLARE @var_sync_scope_id varbinary(128) = cast(@sync_scope_id as varbinary(128));

;WITH 
  CHANGE_TRACKING_CONTEXT(@var_sync_scope_id),
  **[TopssPartBoFollowUpSync_tracking]** AS (
	SELECT [p].[Id], 
	CAST([CT].[SYS_CHANGE_CONTEXT] as uniqueidentifier) AS [update_scope_id], 
	[CT].[SYS_CHANGE_VERSION] as [timestamp],
	CASE WHEN [CT].[SYS_CHANGE_OPERATION] = 'D' THEN 1 ELSE 0 END AS [sync_row_is_tombstone]
	FROM @changeTable AS [p] 
	LEFT JOIN CHANGETABLE(CHANGES [TopssPartBoFollowUpSync], @sync_min_timestamp) AS [CT] ON [p].[Id] = [CT].[Id]
	)
DELETE [TopssPartBoFollowUpSync]
OUTPUT  DELETED.[Id]
INTO @dms_changed 
FROM [TopssPartBoFollowUpSync] [base]
**JOIN [TopssPartBoFollowUpSync_tracking] [changes] ON [changes].[Id] = [base].[Id]**
WHERE [changes].[timestamp] <= @sync_min_timestamp OR [changes].[timestamp] IS NULL OR [changes].[update_scope_id] = @sync_scope_id;

--Select all ids not inserted / deleted / updated as conflict
SELECT  [Id]
FROM @changeTable [t]
WHERE NOT EXISTS (
	 SELECT  [Id]	 FROM @dms_changed [i]
	 WHERE  [t].[Id] = [i].[Id]	)

END
GO`

**and .NetCore code, I set SyncOptions as below:**
 `SyncOptions syncOption = new SyncOptions
   {
             ConflictResolutionPolicy = ConflictResolutionPolicy.ClientWins
   };`

![image](https://user-images.githubusercontent.com/75124167/126603235-6dbeb4f9-9c16-4e4b-ac8e-5b02c60f96c8.png)

What is the solution to this issue?
Thanks

**Comment by Mimetis** [comment]
In your delete query, the TopssPartBoFollowUpSync_tracking is just an alias coming from previous lines

``` sql
;WITH
CHANGE_TRACKING_CONTEXT(@var_sync_scope_id),
[TopssPartBoFollowUpSync_tracking] AS
```
It takes the change tracking stuff and make a temp table to work with, later.

On your scenario, did you try to:
- Use a regular `SqlSyncProvider`
- Make syncs
- Change to `SqlSyncChangeTrackingProvider` ?

If it's the case, you need to deprovision then provision again all your schema, to benefits of the change tracking stuff.

What I don't understand, is why you have some many `Create Procedure` statements executed.
These commands should be done on the first run (or on a provision step) only.
It should not be executed every time.

Can you explain a little bit more what you are actually doing here ?

**Comment by tamdtvn** [comment]
Yes, TopssPartBoFollowUpSync_tracking is just an alias only. I'm sorry for my mistake and already updated the issue.

"On your scenario, did you try to:
Use a regular SqlSyncProvider
Make syncs
Change to SqlSyncChangeTrackingProvider ?"
=> No, I used SqlSyncChangeTrackingProvider from the beginning.

"What I don't understand, is why you have some many Create Procedure statements executed.
These commands should be done on the first run (or on a provision step) only.
It should not be executed every time."
=> Yes, I don't understand also.

"Can you explain a little bit more what you are actually doing here?"
=> in .NetCore code, I set SyncOptions:
SyncOptions syncOption = new SyncOptions { ConflictResolutionPolicy = ConflictResolutionPolicy.ClientWins };

I tested with 2 SQL Server Databases. I want to get data from Client to Server, if the Client changes data then it will be applied to Server. So I try to set SyncOptions like above in .NetCore code.

Do you have any idea?

**Comment by tamdtvn** [comment]
I will do deprovision then provision again all my schema first. Then let you know the result.

**Comment by Mimetis** [comment]
Try your tests with an empty database on the client, and a database without any sync provisioned stuff on server

**Comment by tamdtvn** [comment]
I did deprovision then provision again and run the test:
+ 1st time sync with 69,000 records on the Client (insert new): OK
+ 2nd time sync with 69,000 deleted records (old record at the 1st time) and 69,000 new records: OK
+ 3rd time sync with  69,000 deleted records (old record at the 2nd time) and 69,000 new records: OK

**Comment by tamdtvn** [comment]
I accidentally pressed the Close button, so I reopen it.

**Comment by Mimetis** [comment]
I need more info about the exception raised 
Do you have any exception details ? (from server or client) ?

**Comment by tamdtvn** [comment]
I only got the locked table so far. I will try to get more exception info and let you know if any.

**Comment by tamdtvn** [comment]
Hi @Mimetis,

This is the exception:
`Dotmim.Sync.SyncException
Invalid object name 'TopssPartBoFollowUpSync_tracking'. Statement(s) could not be prepared.

Dotmim.Sync.SyncException: Invalid object name 'TopssPartBoFollowUpSync_tracking'.
Statement(s) could not be prepared.
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid object name 'TopssPartBoFollowUpSync_tracking'.
Statement(s) could not be prepared.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.CompleteAsyncExecuteReader(Boolean isInternal, Boolean forDescribeParameterEncryption)
   at Microsoft.Data.SqlClient.SqlCommand.InternalEndExecuteNonQuery(IAsyncResult asyncResult, Boolean isInternal, String endMethod)
   at Microsoft.Data.SqlClient.SqlCommand.EndExecuteNonQueryInternal(IAsyncResult asyncResult)
   at Microsoft.Data.SqlClient.SqlCommand.EndExecuteNonQueryAsync(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Dotmim.Sync.BaseOrchestrator.InternalUpdateMetadatasAsync(SyncContext context, DbSyncAdapter syncAdapter, SyncRow row, Nullable`1 senderScopeId, Boolean forceWrite, DbConnection connection, DbTransaction transaction)
   at Dotmim.Sync.BaseOrchestrator.HandleConflictAsync(Guid localScopeId, Guid senderScopeId, DbSyncAdapter syncAdapter, SyncContext context, SyncRow conflictRow, SyncTable schemaChangesTable, ConflictResolutionPolicy policy, Nullable`1 lastTimestamp, DbConnection connection, DbTransaction transaction)
   at Dotmim.Sync.BaseOrchestrator.InternalApplyChangesBatchAsync(SyncContext context, Boolean useBulkOperation, SyncTable changesTable, MessageApplyChanges message, DataRowState applyType, DbConnection connection, DbTransaction transaction, CancellationToken cancellationToken)
   at Dotmim.Sync.BaseOrchestrator.InternalApplyTableChangesAsync(SyncContext context, SyncTable schemaTable, MessageApplyChanges message, DbConnection connection, DbTransaction transaction, DataRowState applyType, DatabaseChangesApplied changesApplied, CancellationToken cancellationToken, IProgress`1 progress)
   at Dotmim.Sync.BaseOrchestrator.InternalApplyChangesAsync(SyncContext context, MessageApplyChanges message, DbConnection connection, DbTransaction transaction, CancellationToken cancellationToken, IProgress`1 progress)
   at Dotmim.Sync.RemoteOrchestrator.ApplyThenGetChangesAsync(ScopeInfo clientScope, BatchInfo clientBatchInfo, CancellationToken cancellationToken, IProgress`1 progress)
ClientConnectionId:7d0c0595-9a1b-4baf-8afa-f11ae8f29b75`

**Comment by Mimetis** [comment]
Is it possible for you to create a sample repro of that issue ?

**Comment by Mimetis** [comment]
Can you make a try with the last master branch code ?
It's not released yet, but I think I know where the bug is coming from (and is probably already resolved)

Just clone the master branch, recompile the code, and make a test ?

**Comment by tamdtvn** [comment]
Yes, I'll try.

**Comment by tamdtvn** [comment]
I already tested OK following your suggestion. When is version 0.8.1 release? I'm looking forward to applying this.

**Comment by Mimetis** [comment]
I'm currently in vacation, but I guess, the next release will be released in early September
