### ISSUE TITLE
Cannot add scope to server

### ISSUE THREAD

**Issue by VagueGit** [Mimetis/Dotmim.Sync#607]
Having a bit of bother adding a scope to a new SQL Server database via a web api using `DMS 0.8.1-beta-0687`

Cutting to the chase, in `ConfigureServices` I have
```
string scope = "Numbers";
tables = new string[] { "JobNrs", "OrderNrs" };
services.AddSyncServer<SqlSyncChangeTrackingProvider>(connectionString, scope, tables, syncOptions);
```

After the webserver starts I view `scope_info_server` in the SQL Server database but it only has the default scope.

The default scope is syncing just fine, but it would be nice to get other scopes happening. What am I missing?

**Comment by Mimetis** [comment]
Usually, the scope is created on the first sync.
Did you tried a first sync from a test client ?

**Comment by VagueGit** [comment]
Thank you for the prompt response. Here is how I configure the client for the Numbers scope
```
syncScope="Numbers";
string[] tables = DownScopes.SyncTables(syncScope);
agent = new SyncAgent(clientProvider, webClientOrchestrator, syncOptions, tables, scopeName: syncScope);
```

Even though I haven't yet tried to sync with `DefaultScope`, only `Numbers` I see
In the output for the webserver
`DefaultScope`
In the output for the client
```
Provisioning	 Schema Loaded For 42 Tables.
DefaultScope
```

Then on the client this exception message
```
Schema does not exists yet in your remote database. You must make a first sync with your server, to initialize everything required locally.
-----------------------
   at Dotmim.Sync.BaseOrchestrator.RaiseError(Exception exception)
   at Dotmim.Sync.RemoteOrchestrator.ApplyThenGetChangesAsync(ScopeInfo clientScope, BatchInfo clientBatchInfo, CancellationToken cancellationToken, IProgress`1 progress)
   at Dotmim.Sync.RemoteOrchestrator.ApplyThenGetChangesAsync(ScopeInfo clientScope, BatchInfo clientBatchInfo, CancellationToken cancellationToken, IProgress`1 progress)
   at Dotmim.Sync.Web.Server.WebServerOrchestrator.ApplyThenGetChangesAsync2(HttpContext httpContext, HttpMessageSendChangesRequest httpMessage, SessionCache sessionCache, Int32 clientBatchSize, CancellationToken cancellationToken, IProgress`1 progress)
   at Dotmim.Sync.Web.Server.WebServerOrchestrator.HandleRequestAsync(HttpContext httpContext, Action`1 action, CancellationToken cancellationToken, IProgress`1 progress)
-----------------------
-----------------------
INNER EXCEPTION
-----------------------
Schema does not exists yet in your remote database. You must make a first sync with your server, to initialize everything required locally.
-----------------------
   at Dotmim.Sync.RemoteOrchestrator.ApplyThenGetChangesAsync(ScopeInfo clientScope, BatchInfo clientBatchInfo, CancellationToken cancellationToken, IProgress`1 progress)
-----------------------
```

Sync for `DefaultScope` works fine

**Comment by Mimetis** [comment]
Can you have a look on this sample : [Multi Scopes Web Sample](https://github.com/Mimetis/Dotmim.Sync/tree/master/Samples/MutliOrchestratorsWebSync)

I guess your error is that you are not injected all the orchestrators available for sync:

``` cs
        public IEnumerable<WebServerOrchestrator> WebServerOrchestrators { get; }

        // Injected thanks to Dependency Injection
        public SyncController(IEnumerable<WebServerOrchestrator> webServerOrchestrators) 
            => this.WebServerOrchestrators = webServerOrchestrators;
```
The new method to handle several scopes is a little bit different from the method we have in version <= `v0.8.0`, but it allows us to have more control, and will give us the opportunity to use the user session in a better way.

Let me know if it's working, using the sample code
