### ISSUE TITLE
Dotmim.Sync.Web.Client

### ISSUE THREAD

**Issue by Hardshop18** [Mimetis/Dotmim.Sync#610]
hi, I'm using the latest version beta Dotmim.Sync.

I created a snapshot, and I'm using a webservice. I check that the WebServerManager has been removed. I made the change to use the WebServerOrchestrator, but when I do, it's showing me the following message:

`InvalidOperationException
Dotmim.Sync.Web.Client.HttpSyncWebException: Session has not been configured for this application or request.
-----------------------

-----------------------
-----------------------
INNER EXCEPTION
-----------------------
Session has not been configured for this application or request.
-----------------------
   at Microsoft.AspNetCore.Http.DefaultHttpContext.get_Session()
   at Dotmim.Sync.Web.Server.WebServerOrchestrator.HandleRequestAsync(HttpContext httpContext, Action`1 action, CancellationToken cancellationToken, IProgress`1 progress)
-----------------------

   at Dotmim.Sync.Web.Client.HttpRequestHandler.HandleSyncError(HttpResponseMessage response)
   at Dotmim.Sync.Web.Client.HttpRequestHandler.SendAsync(HttpClient client, String requestUri, String sessionId, String scopeName, HttpStep step, Byte[] data, String ser, IConverter converter, String hashString, String contentType, CancellationToken cancellationToken)
   at Dotmim.Sync.SyncPolicy.InternalExecuteAsync[TResult](Func`1 operation, CancellationToken cancellationToken, Object arg)
   at Dotmim.Sync.Web.Client.HttpRequestHandler.ProcessRequestAsync(HttpClient client, String baseUri, Byte[] data, HttpStep step, Guid sessionId, String scopeName, ISerializerFactory serializerFactory, IConverter converter, Int32 batchSize, SyncPolicy policy, CancellationToken cancellationToken, IProgress`1 progress)
   at Dotmim.Sync.Web.Client.WebClientOrchestrator.EnsureSchemaAsync(DbConnection connection, DbTransaction transaction, CancellationToken cancellationToken, IProgress`1 progress)
   at Dotmim.Sync.SyncAgent.<>c__DisplayClass53_0.<<SynchronizeAsync>b__0>d.MoveNext()`

What configuration do I need to inform to solve this problem?

**Comment by Mimetis** [comment]
Can you take a look here, and see if you did not forgot to add session ?

https://github.com/Mimetis/Dotmim.Sync/blob/daa10c3232160426cbd5710638c0fe9ce0d173d0/Samples/HelloWebSync/HelloWebSyncServer/Startup.cs#L31-L47

**Comment by Hardshop18** [comment]
I wasn't putting the command:
services.AddSession(options => options.IdleTimeout = TimeSpan.FromMinutes(30));

I will do a test here. Thanks

**Comment by Hardshop18** [comment]
I set up the server like this in the test, but when synchronizing I was not successful in synchronizing. I'm finding that something is missing on the client side.

**Comment by Mimetis** [comment]
Can you make a sample repro ? Will be easier to debug
