### ISSUE TITLE
MariaDB on AWS

### ISSUE THREAD

**Issue by Hardshop18** [Mimetis/Dotmim.Sync#613]
I'm using MariaDB on AWS, and I have a user who has permission to use only one database, he has all permissions. But trying to take a snapshot this is the message that is returning to me (This user does not have root permission):

``` cs
Unhandled exception. System.AggregateException: One or more errors occurred. (Access denied; you need (at least one of) the SUPER privilege(s) for this operation)
 ---> Dotmim.Sync.SyncException: Access denied; you need (at least one of) the SUPER privilege(s) for this operation
 ---> MySqlConnector.MySqlException (0x80004005): Access denied; you need (at least one of) the SUPER privilege(s) for this operation
 ---> MySqlConnector.MySqlException (0x80004005): Access denied; you need (at least one of) the SUPER privilege(s) for this operation
   at MySqlConnector.Core.ServerSession.ReceiveReplyAsyncAwaited(ValueTask`1 task) in /_/src/MySqlConnector/Core/ServerSession.cs:line 815
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in /_/src/MySqlConnector/Core/ResultSet.cs:line 49
   at MySqlConnector.MySqlDataReader.ActivateResultSet(CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 131
   at MySqlConnector.MySqlDataReader.CreateAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 436
   at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList`1 commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/CommandExecutor.cs:line 60
   at MySqlConnector.MySqlCommand.ExecuteNonQueryAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 264
   at Dotmim.Sync.MySql.Builders.MySqlBuilder.EnsureDatabaseAsync(DbConnection connection, DbTransaction transaction)
   at Dotmim.Sync.BaseOrchestrator.InternalProvisionAsync(SyncContext ctx, Boolean overwrite, SyncSet schema, SyncSetup setup, SyncProvision provision, Object scope, DbConnection connection, DbTransaction transaction, CancellationToken cancellationToken, IProgress`1 progress)
   at Dotmim.Sync.RemoteOrchestrator.<>c__DisplayClass19_0.<<CreateSnapshotAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Dotmim.Sync.BaseOrchestrator.RunInTransactionAsync[T](SyncStage stage, Func`4 actionTask, DbConnection connection, DbTransaction transaction, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Dotmim.Sync.BaseOrchestrator.RaiseError(Exception exception)
   at Dotmim.Sync.BaseOrchestrator.RunInTransactionAsync[T](SyncStage stage, Func`4 actionTask, DbConnection connection, DbTransaction transaction, CancellationToken cancellationToken)
   at Dotmim.Sync.BaseOrchestrator.RunInTransactionAsync[T](SyncStage stage, Func`4 actionTask, DbConnection connection, DbTransaction transaction, CancellationToken cancellationToken)
   at HardShop.Snapshot.Program.<>c__DisplayClass0_0.<<Main>b__0>d.MoveNext() in D:\Desenvolvimento-DDD\HardShop.Snapshot\Program.cs:line 43
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAllCore(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks)
   at HardShop.Snapshot.Program.Main(String[] args) in D:\Desenvolvimento-DDD\HardShop.Snapshot\Program.cs:line 44

```

**Comment by Mimetis** [comment]
Can you look at #443 and see if it resolves your issue ?
I don't have access to any AWS subscription, so it's complicated for me to test.

That being said, the snapshot is writing files to a folder, are you sure you have the permissions to do so ?

**Comment by Hardshop18** [comment]
I can simulate the problem in a database other than AWS, I created a user who is allowed to see only the database I'm going to sync, and when trying to sync or snapshot, it shows the error message I posted in the comment above.

**Comment by Hardshop18** [comment]
I identified the problem, when I am using a user without SUPER permission and I try to run the SQL command "set global innodb_stats_on_metadata=0;" he's showing that error message.
