### ISSUE TITLE
SyncException HttpResponseContextException

### ISSUE THREAD

**Issue by wTechnoo** [Mimetis/Dotmim.Sync#622]
### Screenshot
![image](https://user-images.githubusercontent.com/71846381/138566194-803a39bf-a0ed-49aa-8a89-79715b7be7ae.png)

### Stack trace: 
```
at Dotmim.Sync.SyncAgent.SynchronizeAsync (Dotmim.Sync.Enumerations.SyncType syncType, System.Threading.CancellationToken cancellationToken, System.IProgress`1[T] progress) [0x00d4c] in <7fa78ca1d5e24d4992dbd8446123f706>:0 
  at AppTechForms.MySQLiteCon.SyncDB () [0x00096] in C:\Users\Technoo\Downloads\AppTechForms\AppTechForms\AppTechForms\MySQLCon.cs:1163 
  at AppTechForms.MainPage.<SyncButton_OnClicked>b__10_0 () [0x00025] in C:\Users\Technoo\Downloads\AppTechForms\AppTechForms\AppTechForms\MainPage.xaml.cs:66 
  at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) [0x00000] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:1021 
  at Android.App.SyncContext+<>c__DisplayClass2_0.<Post>b__0 () [0x00000] in /Users/builder/azdo/_work/278/s/xamarin-android/src/Mono.Android/Android.App/SyncContext.cs:36 
  at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in /Users/builder/azdo/_work/278/s/xamarin-android/src/Mono.Android/Java.Lang/Thread.cs:36 
  at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00008] in /Users/builder/azdo/_work/278/s/xamarin-android/src/Mono.Android/obj/Release/monoandroid10/android-30/mcw/Java.Lang.IRunnable.cs:84 
  at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.57(intptr,intptr)
```

I'm already using the WebApi, sample code and etc but i'm unable to sync, had to put the sync code on the android main thread, otherwise I wouldn't get any errors (don't sync)

**Comment by Mimetis** [comment]
Can you share a sample repro ?

**Comment by wTechnoo** [comment]
Hello, what does repro means? It means project? If so, it's a private project, I can't share it, but it has a very big database with lots of data

**Comment by Mimetis** [comment]
share something i can test and debug :)

**Comment by wTechnoo** [comment]
**Syncing code ( CLIENT )**
```
        public async Task<string> SyncDB()
        {
            Batteries_V2.Init();
            MySQLCon mySqlCon = new MySQLCon();
            // Database script used for this sample : https://github.com/Mimetis/Dotmim.Sync/blob/master/CreateAdventureWorks.sql 

            var serverOrchestrator = new WebClientOrchestrator("MYWEBHERE");
            //var mysqlProvider = new MySqlSyncProvider();
            // Second provider is using plain old Sql Server provider, relying on triggers and tracking tables to create the sync environment
            var clientProvider = new SqliteSyncProvider(connectionPath);

            // Creating an agent that will handle all the process
            string[] tables = mySqlCon.CarregaTabelas().ToArray();
            string[] filtered = tables.Where(x => !x.Contains("_tracking") && x != "TEMPPRODUTOS").ToArray();
            var agent = new SyncAgent(clientProvider, serverOrchestrator, filtered);
            
            var s1 = await agent.SynchronizeAsync();

            return s1.ToString();
        }
```

**Syncing code ( SERVER )**
```
         // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddControllers();

            // [Required]: Handling multiple sessions
            services.AddMemoryCache();

            // [Required]: Get a connection string to your server data source
            //var connectionString = Configuration.GetSection("ConnectionStrings")["SqlConnection"];
            var connectionString = Configuration.GetSection("ConnectionStrings")["MySqlConnection"];

            // [Required] Tables involved in the sync process:
            var tables = new string[] { "ALL MY TABLES HERE" };

            // [Required]: Add a SqlSyncProvider acting as the server hub.
            //services.AddSyncServer<SqlSyncChangeTrackingProvider>(connectionString, tables);
            services.AddSyncServer<MySqlSyncProvider>(connectionString, tables);
        }
```

Picture of my MYSQL database:
![image](https://user-images.githubusercontent.com/71846381/139947660-b7f4101c-030e-419a-a369-be2e8f654cfe.png)

**Comment by Mimetis** [comment]
Do u know which table makes the code failing ?
One test you can do, if u don't know, try to implement a sync with only one table, and see if it's working
If it's working, add another table
On each test, be sure the database is not provisionned with DMS metadatas (like stored proc, triggers etc ...)

Once you know which table is making the whole sync failing, let me know

I cant' do nothing for now with what you provided here

**Comment by wTechnoo** [comment]
Ok thanks, I'll try out what you said and post my results here.

**Comment by wTechnoo** [comment]
Hello there Mimetis, I tried it with one table (My users table) and got the following error:
**Dotmim.Sync.SyncException: Required property 'schema' not found in JSON. Path 'bi', line 1, position 161.**

Stack trace:
```
Dotmim.Sync.SyncException: Required property 'schema' not found in JSON. Path 'bi', line 1, position 161.
 ---> Newtonsoft.Json.JsonSerializationException: Required property 'schema' not found in JSON. Path 'bi', line 1, position 161.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EndProcessProperty(Object newObject, JsonReader reader, JsonObjectContract contract, Int32 initialDepth, JsonProperty property, PropertyPresence presence, Boolean setDefaultValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject[T]()
   at Dotmim.Sync.Serialization.JsonConverter`1.DeserializeAsync(Stream ms)
   at Dotmim.Sync.Web.Client.WebClientOrchestrator.ApplyThenGetChangesAsync(ScopeInfo scope, BatchInfo clientBatchInfo, CancellationToken cancellationToken, IProgress`1 progress)
   at Dotmim.Sync.SyncAgent.<>c__DisplayClass53_0.<<SynchronizeAsync>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
   at Dotmim.Sync.SyncAgent.<>c__DisplayClass53_0.<<SynchronizeAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Dotmim.Sync.SyncAgent.SynchronizeAsync(SyncType syncType, CancellationToken cancellationToken, IProgress`1 progress)
   at TesteSYNC.SQL.SyncDB(String[] tabelas) in C:\Users\Technoo\TesteSYNC\SQL.cs:line 39
   at TesteSYNC.Program.Main(String[] args) in C:\Users\Technoo\TesteSYNC\Program.cs:line 24
   at TesteSYNC.Program.<Main>(String[] args)
```

**Comment by Mimetis** [comment]
I dont know.
I need a repro samp'e

**Comment by wTechnoo** [comment]
You can't tell what may be the error with this stack trace? I legit have no idea of what may be causing those errors, i'll try out another table here and send results.
I'm currenly using a aspnet server to host the sync server, and trying to sync between sqlite and mysql with it

**Comment by Mimetis** [comment]
Share the table schéma, ill try it

**Comment by wTechnoo** [comment]
Here is the schema for the table I tried syncing:
![image](https://user-images.githubusercontent.com/71846381/142260332-b6262e9e-8e09-4880-956a-6878690ea5dc.png)

**Comment by Mimetis** [comment]
I need something like this : [AdventureWorks MySql script](https://github.com/Mimetis/Dotmim.Sync/blob/master/CreateMySqlAdventureWorks.sql), that I can execute in **MySql Workbench**
Not a screenshot please

**Comment by wTechnoo** [comment]
Oh, I'm sorry, here you go:

```
CREATE DATABASE IF NOT EXISTS `minhaDatabase`

USE `minhaDatabase`

DROP TABLE IF EXISTS `NomeRotas`
CREATE TABLE `NomeRotas` (
 `id` int NOT NULL AUTO_INCREMENT,
 `NRotas` text NOT NULL,
 PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=latin1

INSERT INTO `NomeRotas` VALUES (0, 'Las Vegas')

DROP TABLE IF EXISTS `Clientes`
CREATE TABLE `Clientes` (
 `id` int NOT NULL AUTO_INCREMENT,
 `Nome` text NOT NULL,
 `Endereço` text NOT NULL,
 `Bairro` text NOT NULL,
 `vidrao` text NOT NULL,
 `Telefone` text NOT NULL,
 `idRota` int NOT NULL,
 `Pos` int NOT NULL,
 `Observaçao` text NOT NULL,
 `referencia` text NOT NULL,
 `LatitudeELongitude` text NOT NULL,
 PRIMARY KEY (`id`),
 KEY `idRota` (`idRota`),
 CONSTRAINT `Clientes_ibfk_1` FOREIGN KEY (`idRota`) REFERENCES `NomeRotas` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=latin1

INSERT INTO `Clientes` VALUES (0, 'Mimetis', 'address', 'address', '', '+49 0000-0000', 0, 0, '', '', '0,0')
```

**Comment by Mimetis** [comment]
I test your script with the [Xamarin Sample](https://github.com/Mimetis/Dotmim.Sync/tree/master/Samples/XamAppSync)

Here is the script I used:

``` mysql
DROP DATABASE  IF EXISTS `minhaDatabase`;
CREATE DATABASE  IF NOT EXISTS `minhaDatabase`;

USE `minhaDatabase`;

DROP TABLE IF EXISTS `NomeRotas`;
CREATE TABLE `NomeRotas` (
 `id` int NOT NULL AUTO_INCREMENT,
 `NRotas` text NOT NULL,
 PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=latin1;

INSERT INTO `NomeRotas` (`id`, `NRotas`) VALUES (1, 'Las Vegas');

DROP TABLE IF EXISTS `Clientes`;
CREATE TABLE `Clientes` (
 `id` int NOT NULL AUTO_INCREMENT,
 `Nome` text NOT NULL,
 `Endereço` text NOT NULL,
 `Bairro` text NOT NULL,
 `vidrao` text NOT NULL,
 `Telefone` text NOT NULL,
 `idRota` int NOT NULL,
 `Pos` int NOT NULL,
 `Observaçao` text NOT NULL,
 `referencia` text NOT NULL,
 `LatitudeELongitude` text NOT NULL,
 PRIMARY KEY (`id`),
 KEY `idRota` (`idRota`),
 CONSTRAINT `Clientes_ibfk_1` FOREIGN KEY (`idRota`) REFERENCES `NomeRotas` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=latin1;

INSERT INTO `Clientes` VALUES (1, 'Mimetis', 'address', 'address', '', '+49 0000-0000', 1, 0, '', '', '0,0');
```
Server Side:
![image](https://user-images.githubusercontent.com/4592555/142274166-e48586d4-9abc-457f-87e5-5d2b4a09ba62.png)

``` cs
public void ConfigureServices(IServiceCollection services)
{
    services.AddControllers();

    services.AddDistributedMemoryCache();
    services.AddSession(options => options.IdleTimeout = TimeSpan.FromMinutes(30));

    // [Required]: Get a connection string to your server data source
    //var connectionString = Configuration.GetSection("ConnectionStrings")["SqlConnection"];

    var connectionString = "Server=127.0.0.1;Port=3307;Database=minhaDatabase;Uid=.............";

    var tables = new string[] { "NomeRotas", "Clientes" };

    var setup = new SyncSetup(tables);

    // add a SqlSyncProvider acting as the server hub
    services.AddSyncServer<MySqlSyncProvider>(connectionString, setup);
}
```

Client side is the [xamarin client application](https://github.com/Mimetis/Dotmim.Sync/tree/master/Samples/XamAppSync/XamSyncSample) with no changes.

It seems to work for me:

![image](https://user-images.githubusercontent.com/4592555/142271896-4fe50883-e131-4f44-959e-346bcf8220bc.png)

**Comment by wTechnoo** [comment]
Hey, thanks for testing it, what I did was REUPLOAD everything fresh to my ASP.NET server and it seems to fix the other bugs but now I'm getting SQLite errors about foreign keys

Dotmim.Sync.SyncException: SQLite Error 19: 'FOREIGN KEY constraint failed'.
 ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'FOREIGN KEY constraint failed'.

Stack trace
```
Dotmim.Sync.SyncException: SQLite Error 19: 'FOREIGN KEY constraint failed'.
 ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'FOREIGN KEY constraint failed'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at System.Data.Common.DbCommand.ExecuteNonQueryAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location ---
   at Dotmim.Sync.BaseOrchestrator.InternalApplyChangesBatchAsync(SyncContext context, Boolean useBulkOperation, SyncTable changesTable, MessageApplyChanges message, DataRowState applyType, DbConnection connection, DbTransaction transaction, CancellationToken cancellationToken)
   at Dotmim.Sync.BaseOrchestrator.InternalApplyTableChangesAsync(SyncContext context, SyncTable schemaTable, MessageApplyChanges message, DbConnection connection, DbTransaction transaction, DataRowState applyType, DatabaseChangesApplied changesApplied, CancellationToken cancellationToken, IProgress`1 progress)
   at Dotmim.Sync.BaseOrchestrator.InternalApplyChangesAsync(SyncContext context, MessageApplyChanges message, DbConnection connection, DbTransaction transaction, CancellationToken cancellationToken, IProgress`1 progress)
   at Dotmim.Sync.LocalOrchestrator.<>c__DisplayClass7_0.<<ApplyChangesAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Dotmim.Sync.BaseOrchestrator.RunInTransactionAsync[T](SyncStage stage, Func`4 actionTask, DbConnection connection, DbTransaction transaction, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Dotmim.Sync.BaseOrchestrator.RaiseError(Exception exception)
   at Dotmim.Sync.BaseOrchestrator.RunInTransactionAsync[T](SyncStage stage, Func`4 actionTask, DbConnection connection, DbTransaction transaction, CancellationToken cancellationToken)
   at Dotmim.Sync.BaseOrchestrator.RunInTransactionAsync[T](SyncStage stage, Func`4 actionTask, DbConnection connection, DbTransaction transaction, CancellationToken cancellationToken)
   at Dotmim.Sync.SyncAgent.<>c__DisplayClass53_0.<<SynchronizeAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Dotmim.Sync.SyncAgent.SynchronizeAsync(SyncType syncType, CancellationToken cancellationToken, IProgress`1 progress)
   at TesteSYNC.SQL.SyncDB(String[] tabelas) in C:\Users\Technoo\TesteSYNC\SQL.cs:line 39
   at TesteSYNC.Program.Main(String[] args) in C:\Users\Technoo\TesteSYNC\Program.cs:line 24
   at TesteSYNC.Program.<Main>(String[] args)
```

**Comment by wTechnoo** [comment]
FINALLY, I got, just had to disable some failing foreign key and now it syncs correctly, thanks once again Mimetis.
