### ISSUE TITLE
SendAsync: Unexpected end of content while loading JObject

### ISSUE THREAD

**Issue by AlfaGTA** [Mimetis/Dotmim.Sync#624]
I trying to send 2 records to server, but when I try to sync, the server returns following exception: Unexpected end of content while loading JObject. Path 's', line 1, position 275.

Here the complete stack:

26/10/2021 10:47:41 0.00%:	Session Begins.
26/10/2021 10:47:41 0.00%:	Getting Server Scope. Scope Name:DefaultScope.
26/10/2021 10:47:41 18.57%:	[Incassi] [Total] Upserts:2. Deletes:0. Total:2.
26/10/2021 10:47:41 30.00%:	[Total] Upserts:2. Deletes:0. Total:2
26/10/2021 10:47:41 50.00%:	Sending Batch Changes. Batches: (1/1). Rows: (2/2). Waiting Server Response...
26/10/2021 10:47:41 50.00%:	Retry Sending Http Request (1/10. Waiting 500ms... )
26/10/2021 10:47:42 50.00%:	Retry Sending Http Request (2/10. Waiting 1000ms... )
26/10/2021 10:47:43 50.00%:	Retry Sending Http Request (3/10. Waiting 1500ms... )
26/10/2021 10:47:44 50.00%:	Retry Sending Http Request (4/10. Waiting 2000ms... )
26/10/2021 10:47:46 50.00%:	Retry Sending Http Request (5/10. Waiting 2500ms... )
26/10/2021 10:47:49 50.00%:	Retry Sending Http Request (6/10. Waiting 3000ms... )
26/10/2021 10:47:52 50.00%:	Retry Sending Http Request (7/10. Waiting 3500ms... )
26/10/2021 10:47:55 50.00%:	Retry Sending Http Request (8/10. Waiting 4000ms... )
26/10/2021 10:47:59 50.00%:	Retry Sending Http Request (9/10. Waiting 4500ms... )
26/10/2021 10:48:04 50.00%:	Retry Sending Http Request (10/10. Waiting 5000ms... )
26/10/2021 10:48:11 (099) Unexpected end of content while loading JObject. Path 's', line 1, position 275.
26/10/2021 10:48:11 (099)    at Dotmim.Sync.Web.Client.HttpRequestHandler.HandleSyncError(HttpResponseMessage response)
   at Dotmim.Sync.Web.Client.HttpRequestHandler.SendAsync(HttpClient client, String requestUri, String sessionId, String scopeName, HttpStep step, ByteArrayContent arrayContent, String ser, IConverter converter, String hashString, String contentType, CancellationToken cancellationToken)
   at Dotmim.Sync.SyncPolicy.InternalExecuteAsync[TResult](Func`1 operation, CancellationToken cancellationToken, Object arg)
   at Dotmim.Sync.Web.Client.HttpRequestHandler.ProcessRequestAsync(HttpClient client, String baseUri, Byte[] data, HttpStep step, Guid sessionId, String scopeName, ISerializerFactory serializerFactory, IConverter converter, Int32 batchSize, SyncPolicy policy, CancellationToken cancellationToken, IProgress`1 progress)
   at Dotmim.Sync.Web.Client.WebClientOrchestrator.ApplyThenGetChangesAsync(ScopeInfo scope, BatchInfo clientBatchInfo, CancellationToken cancellationToken, IProgress`1 progress)
   at Dotmim.Sync.SyncAgent.<>c__DisplayClass53_0.<<SynchronizeAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Dotmim.Sync.SyncAgent.SynchronizeAsync(SyncType syncType, CancellationToken cancellationToken, IProgress`1 progress)
   at MySyncService.Tests.Tests.TestInsertAsync() in C:\Projects\MySyncService\MySyncService.Tests\UnitTest1.cs:line 703

I'm using Dotmim.Sync.Sqlite ver. 0.8.0

**Comment by Mimetis** [comment]
Can you share a sample repro ?
