### ISSUE TITLE
Could Not Load Assembly 'System.Threading.Tasks.Extension, Version 4.2.0.0

### ISSUE THREAD

**Issue by josephorjinta** [Mimetis/Dotmim.Sync#63]
Hi @Mimetis ,
I am trying to implement a ASP.NET Core 2.0 Web Proxy for Sync between SQL Server Database  on Server and SQLite Db meant to be persisted on a mobile device using Cross Platform (Xamarin Forms )Template,  Visual Studio 2017 Community Version 15.6.4. I have created the Web Proxy App using ASP.NET Core Web App (2.0), but when i  to implement the Sync function on .NET Standard Shared Code Project by typing

`public static async Task Sync`
`{`
 ` SqliteSyncProvider clientProvider = new SqliteSyncProvider("GasMobile.db");`
  ` var proxyClientProvider = new Dotmim.Sync.Web.WebProxyClientProvider(new Uri("http://localhost:54593/api/values"));`

    ` var agent = new SyncAgent(clientProvider, proxyClientProvider);`

     `var s = await agent.SynchronizeAsync();`
`}`

I had to add  Dotmim.Sync.Web NuGet Package to the SolidChain .Net Standard Code Sharing Project , On running the SolidChainGas.Android project on Visual Studio, It came up with the following error:

	Exception while loading assemblies: System.IO.FileNotFoundException: Could not load assembly 'System.Threading.Tasks.Extensions, Version=4.2.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. Perhaps it doesn't exist in the Mono for Android profile?
File name: 'System.Threading.Tasks.Extensions.dll'
   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference, ReaderParameters parameters) in /Users/builder/data/lanes/5809/a7829590/source/monodroid/external/xamarin-android/external/Java.Interop/src/Java.Interop.Tools.Cecil/Java.Interop.Tools.Cecil/DirectoryAssemblyResolver.cs:line 229
   at Xamarin.Android.Tasks.ResolveAssemblies.AddAssemblyReferences(DirectoryAssemblyResolver resolver, ICollection`1 assemblies, AssemblyDefinition assembly, Boolean topLevel)
   at Xamarin.Android.Tasks.ResolveAssemblies.AddAssemblyReferences(DirectoryAssemblyResolver resolver, ICollection`1 assemblies, AssemblyDefinition assembly, Boolean topLevel)
   at Xamarin.Android.Tasks.ResolveAssemblies.Execute(DirectoryAssemblyResolver resolver)	SolidChainGas.Android			

I noticed that System.Threading.Tasks.Extensions, Version=4.5.1 was required while adding Dotmim.Sync.Web NuGet for  with .net standard project,  I tried to add the System.Threading.Tasks.Extensions, Version=4.5.1 Nuget to SolidChain.Android  Project but i get the same error when i run the app on Android,

Please how can i resolve this.

**Comment by Mimetis** [comment]
Hi @josephorjinta.

I'm still try to find a solution.
For now, I think a good workaround is to NOT having a shared library between the server and the client project.
Is it working like this ?

**Comment by Mimetis** [comment]
This should be resolved now, as we have now a dedicated **Client** project to reference on Xamarin devices (`Dotmim.Sync.Web.Client`) thanks to the PR #75 

The new nuget package will be available soon, but for now, you can use the source code.

Thx for the feedback all !
