### ISSUE TITLE
The multi-part identifier could not be bound error when trying to sync with filters

### ISSUE THREAD

**Issue by Menci77** [Mimetis/Dotmim.Sync#638]
I am trying to sync an mssql database with my xamarin android app's sqlite database using web proxy. I want to synchronize only the data of a specific customer, for this I created three filters on the Customer, Invoice, InvoiceItem tables based on the CustomerId field.
But the sync method gives this error: 
```
The multi-part identifier "Invoice.CustomerId" could not be bound.
-----------------------
   at Dotmim.Sync.BaseOrchestrator.RaiseError(Exception exception)
   at Dotmim.Sync.BaseOrchestrator.RunInTransactionAsync[T](SyncStage stage, Func`4 actionTask, DbConnection connection, DbTransaction transaction, CancellationToken cancellationToken)
   at Dotmim.Sync.BaseOrchestrator.RunInTransactionAsync[T](SyncStage stage, Func`4 actionTask, DbConnection connection, DbTransaction transaction, CancellationToken cancellationToken)
   at Dotmim.Sync.Web.Server.WebServerOrchestrator.EnsureSchemaAsync(HttpContext httpContext, HttpMessageEnsureScopesRequest httpMessage, SessionCache sessionCache, CancellationToken cancellationToken, IProgress`1 progress)
   at Dotmim.Sync.Web.Server.WebServerOrchestrator.HandleRequestAsync(HttpContext httpContext, Action`1 action, CancellationToken cancellationToken, IProgress`1 progress)
-----------------------
-----------------------
INNER EXCEPTION
-----------------------
The multi-part identifier "Invoice.CustomerId" could not be bound.
-----------------------
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlCommand.InternalEndExecuteNonQuery(IAsyncResult asyncResult, Boolean isInternal, String endMethod)
   at Microsoft.Data.SqlClient.SqlCommand.EndExecuteNonQueryInternal(IAsyncResult asyncResult)
   at Microsoft.Data.SqlClient.SqlCommand.EndExecuteNonQueryAsync(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Dotmim.Sync.BaseOrchestrator.InternalCreateStoredProcedureAsync(SyncContext ctx, DbTableBuilder tableBuilder, DbStoredProcedureType storedProcedureType, DbConnection connection, DbTransaction transaction, CancellationToken cancellationToken, IProgress`1 progress)
   at Dotmim.Sync.BaseOrchestrator.InternalCreateStoredProceduresAsync(SyncContext ctx, Boolean overwrite, DbTableBuilder tableBuilder, DbConnection connection, DbTransaction transaction, CancellationToken cancellationToken, IProgress`1 progress)
   at Dotmim.Sync.BaseOrchestrator.InternalMigrationAsync(SyncContext context, SyncSet schema, SyncSetup oldSetup, SyncSetup newSetup, DbConnection connection, DbTransaction transaction, CancellationToken cancellationToken, IProgress`1 progress)
   at Dotmim.Sync.RemoteOrchestrator.<>c__DisplayClass3_0.<<EnsureSchemaAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Dotmim.Sync.BaseOrchestrator.RunInTransactionAsync[T](SyncStage stage, Func`4 actionTask, DbConnection connection, DbTransaction transaction, CancellationToken cancellationToken)
-----------------------
```

The stack trace:
```
  at Dotmim.Sync.Web.Client.HttpRequestHandler.HandleSyncError (System.Net.Http.HttpResponseMessage response) [0x002b2] in <55a6ba406ad4451d837e2d32b183ba62>:0 
  at Dotmim.Sync.Web.Client.HttpRequestHandler.SendAsync (System.Net.Http.HttpClient client, System.String requestUri, System.String sessionId, System.String scopeName, Dotmim.Sync.Web.Client.HttpStep step, System.Byte[] data, System.String ser, Dotmim.Sync.Serialization.IConverter converter, System.String hashString, System.String contentType, System.Threading.CancellationToken cancellationToken) [0x0036e] in <55a6ba406ad4451d837e2d32b183ba62>:0 
  at Dotmim.Sync.SyncPolicy.InternalExecuteAsync[TResult] (System.Func`1[TResult] operation, System.Threading.CancellationToken cancellationToken, System.Object arg) [0x00103] in <41fc39d200444af2a919390a606774d3>:0 
  at Dotmim.Sync.Web.Client.HttpRequestHandler.ProcessRequestAsync (System.Net.Http.HttpClient client, System.String baseUri, System.Byte[] data, Dotmim.Sync.Web.Client.HttpStep step, System.Guid sessionId, System.String scopeName, Dotmim.Sync.Serialization.ISerializerFactory serializerFactory, Dotmim.Sync.Serialization.IConverter converter, System.Int32 batchSize, Dotmim.Sync.SyncPolicy policy, System.Threading.CancellationToken cancellationToken, System.IProgress`1[T] progress) [0x0037c] in <55a6ba406ad4451d837e2d32b183ba62>:0 
  at Dotmim.Sync.Web.Client.WebClientOrchestrator.EnsureSchemaAsync (System.Data.Common.DbConnection connection, System.Data.Common.DbTransaction transaction, System.Threading.CancellationToken cancellationToken, System.IProgress`1[T] progress) [0x0023c] in <55a6ba406ad4451d837e2d32b183ba62>:0 
  at Dotmim.Sync.SyncAgent+<>c__DisplayClass53_0.<SynchronizeAsync>b__0 () [0x00df7] in <41fc39d200444af2a919390a606774d3>:0 
  at Dotmim.Sync.SyncAgent.SynchronizeAsync (Dotmim.Sync.Enumerations.SyncType syncType, System.Threading.CancellationToken cancellationToken, System.IProgress`1[T] progress) [0x00185] in <41fc39d200444af2a919390a606774d3>:0 
  at MediaStore.DatabaseHelper.SyncDatabase (System.String connString, Android.Content.Context context, System.Int32 custId) [0x000de] in C:\_Menci\7.felev\szakdoga\dotmim\MediaStore\DatabaseHelper.cs:53 
```

My schema
![schema](https://user-images.githubusercontent.com/61515787/142670965-b8a0d795-6a73-48a3-bc83-70595b09d2d8.png)

The web server code:
```
public void ConfigureServices(IServiceCollection services)
        {
            services.AddControllers();

            services.AddDistributedMemoryCache();
            services.AddSession(options => options.IdleTimeout = TimeSpan.FromMinutes(30));

            var connectionString = Configuration.GetSection("ConnectionStrings")["SqlConnection"];

            var options = new SyncOptions
            {
                SnapshotsDirectory = Path.Combine(SyncOptions.GetDefaultUserBatchDiretory(), "Snapshots"),
                BatchSize = 2000,
            };

            var tables = new string[] { "media.Album", "media.Artist", "media.Customer", "media.Invoice", "media.InvoiceItem", "media.Track" };

            var setup = new SyncSetup(tables);

            var customerFilter = new SetupFilter("Customer", "media");
            customerFilter.AddParameter("CustomerId", "Customer", "media", false);
            customerFilter.AddWhere("CustomerId", "Customer", "CustomerId", "media");
            setup.Filters.Add(customerFilter);

            var invoiceCustomerFilter = new SetupFilter("Invoice", "media");
            invoiceCustomerFilter.AddParameter("CustomerId", "Customer", "media", false);
            invoiceCustomerFilter.AddJoin(Join.Inner, "Customer").On("Invoice", "CustomerId", "Customer", "CustomerId");
            invoiceCustomerFilter.AddWhere("CustomerId", "Customer", "CustomerId", "media");
            setup.Filters.Add(invoiceCustomerFilter);

            var invoiceItemCustomerFilter = new SetupFilter("InvoiceItem", "media");
            invoiceItemCustomerFilter.AddParameter("CustomerId", "Customer", "media", false);
            invoiceItemCustomerFilter.AddJoin(Join.Inner, "Invoice").On("InvoiceItem", "InvoiceId", "Invoice", "InvoiceId");
            invoiceItemCustomerFilter.AddJoin(Join.Inner, "Customer").On("Invoice", "CustomerId", "Customer", "CustomerId");
            invoiceCustomerFilter.AddWhere("CustomerId", "Customer", "CustomerId", "media");
            setup.Filters.Add(invoiceItemCustomerFilter);

            services.AddSyncServer<SqlSyncChangeTrackingProvider>(connectionString, setup, options);
        }
```
The client side:
```
var handler = HttpClientHandlerService.GetInsecureHandler();

            HttpClient httpClient = new HttpClient(handler);
            httpClient.DefaultRequestHeaders.Host = $"localhost:44302";   

            var serverOrchestrator = new WebClientOrchestrator("https://10.0.2.2:44302/api/sync", client: httpClient); 

            var clientProvider = new SqliteSyncProvider(connString);

            var agent = new SyncAgent(clientProvider, serverOrchestrator);

            if (!agent.Parameters.Contains("CustomerId"))
            {
                agent.Parameters.Add("CustomerId", custId);
            }

            try
            {
                var result = await agent.SynchronizeAsync();

                var output = result.ToString();
                output = output.Replace("\n", " ").Replace("\t", " ").Replace("\r", " ");
                Toast.MakeText(context, output, ToastLength.Long).Show();
            }
            catch (Exception e)
            {
                Toast.MakeText(context, e.Message, ToastLength.Long).Show();
            }
```

The sync worked before the filters, so the problem is there, but I don't understand why doesn't is recognize the Invoice.CustomerId column.
Let me know what further information should I supply to solve this.
Thanks.

**Comment by Mimetis** [comment]
Can you share your sql schema ? 
something like this [Adventureworks Schema Sample](https://github.com/Mimetis/Dotmim.Sync/blob/master/CreateAdventureWorks.sql)
Then I will be able with your code (and a sample database) to reproduce your issue

**Comment by Mimetis** [comment]
Oh I have it, already :)
OK i will make some tests

**Comment by Mimetis** [comment]
``` cs
 var options = new SyncOptions
 {
     DisableConstraintsOnApplyChanges = true
 };

 var tables = new string[] { "media.Album", "media.Artist", "media.Customer", "media.Invoice", "media.InvoiceItem", "media.Track" };

 var setup = new SyncSetup(tables);

 var customerFilter = new SetupFilter("Customer", "media");
 customerFilter.AddParameter("CustomerId", "Customer", "media", false);
 customerFilter.AddWhere("CustomerId", "Customer", "CustomerId", "media");
 setup.Filters.Add(customerFilter);

 var invoiceCustomerFilter = new SetupFilter("Invoice", "media");
 invoiceCustomerFilter.AddParameter("CustomerId", "Customer", "media", false);
 invoiceCustomerFilter.AddJoin(Join.Inner, "Customer").On("media.Invoice", "CustomerId", "media.Customer", "CustomerId");
 invoiceCustomerFilter.AddWhere("CustomerId", "Customer", "CustomerId", "media");
 setup.Filters.Add(invoiceCustomerFilter);

 var invoiceItemCustomerFilter = new SetupFilter("InvoiceItem", "media");
 invoiceItemCustomerFilter.AddParameter("CustomerId", "Customer", "media", false);
 invoiceItemCustomerFilter.AddJoin(Join.Inner, "Invoice").On("media.InvoiceItem", "InvoiceId", "media.Invoice", "InvoiceId");
 invoiceItemCustomerFilter.AddJoin(Join.Inner, "Customer").On("media.Invoice", "CustomerId", "media.Customer", "CustomerId");
 invoiceCustomerFilter.AddWhere("CustomerId", "Customer", "CustomerId", "media");
 setup.Filters.Add(invoiceItemCustomerFilter);

```

**Comment by Menci77** [comment]
I tried with your code, and now it gives 'Foreign key constraint failed' error.
```
{Dotmim.Sync.SyncException: SQLite Error 19: 'FOREIGN KEY constraint failed'. ---> Microsoft.Data.Sqlite.SqliteException: SQLite Error 19: 'FOREIGN KEY constraint failed'.
  at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC (System.Int32 rc, SQLitePCL.sqlite3 db) [0x0006d] in <9137b1fd3b934c07b5094254ba6599c7>:0 
  at Microsoft.Data.Sqlite.SqliteDataReader.NextResult () [0x0017b] in <9137b1fd3b934c07b5094254ba6599c7>:0 
  at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader (System.Data.CommandBehavior behavior) [0x000d4] in <9137b1fd3b934c07b5094254ba6599c7>:0 
  at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader () [0x00000] in <9137b1fd3b934c07b5094254ba6599c7>:0 
  at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery () [0x00047] in <9137b1fd3b934c07b5094254ba6599c7>:0 
  at System.Data.Common.DbCommand.ExecuteNonQueryAsync (System.Threading.CancellationToken cancellationToken) [0x00049] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/corefx/src/System.Data.Common/src/System/Data/Common/DbCommand.cs:136 
--- End of stack trace from previous location where exception was thrown ---

  at Dotmim.Sync.BaseOrchestrator.InternalApplyChangesBatchAsync (Dotmim.Sync.SyncContext context, System.Boolean useBulkOperation, Dotmim.Sync.SyncTable changesTable, Dotmim.Sync.MessageApplyChanges message, System.Data.DataRowState applyType, System.Data.Common.DbConnection connection, System.Data.Common.DbTransaction transaction, System.Threading.CancellationToken cancellationToken) [0x004d3] in <41fc39d200444af2a919390a606774d3>:0 
  at Dotmim.Sync.BaseOrchestrator.InternalApplyTableChangesAsync (Dotmim.Sync.SyncContext context, Dotmim.Sync.SyncTable schemaTable, Dotmim.Sync.MessageApplyChanges message, System.Data.Common.DbConnection connection, System.Data.Common.DbTransaction transaction, System.Data.DataRowState applyType, Dotmim.Sync.DatabaseChangesApplied changesApplied, System.Threading.CancellationToken cancellationToken, System.IProgress`1[T] progress) [0x0036a] in <41fc39d200444af2a919390a606774d3>:0 
  at Dotmim.Sync.BaseOrchestrator.InternalApplyChangesAsync (Dotmim.Sync.SyncContext context, Dotmim.Sync.MessageApplyChanges message, System.Data.Common.DbConnection connection, System.Data.Common.DbTransaction transaction, System.Threading.CancellationToken cancellationToken, System.IProgress`1[T] progress) [0x0040d] in <41fc39d200444af2a919390a606774d3>:0 
  at Dotmim.Sync.LocalOrchestrator+<>c__DisplayClass7_0.<ApplyChangesAsync>b__0 (Dotmim.Sync.SyncContext ctx, System.Data.Common.DbConnection connection, System.Data.Common.DbTransaction transaction) [0x00167] in <41fc39d200444af2a919390a606774d3>:0 
  at Dotmim.Sync.BaseOrchestrator.RunInTransactionAsync[T] (Dotmim.Sync.Enumerations.SyncStage stage, System.Func`4[T1,T2,T3,TResult] actionTask, System.Data.Common.DbConnection connection, System.Data.Common.DbTransaction transaction, System.Threading.CancellationToken cancellationToken) [0x0028a] in <41fc39d200444af2a919390a606774d3>:0 
   --- End of inner exception stack trace ---
  at Dotmim.Sync.BaseOrchestrator.RaiseError (System.Exception exception) [0x00046] in <41fc39d200444af2a919390a606774d3>:0 
  at Dotmim.Sync.BaseOrchestrator.RunInTransactionAsync[T] (Dotmim.Sync.Enumerations.SyncStage stage, System.Func`4[T1,T2,T3,TResult] actionTask, System.Data.Common.DbConnection connection, System.Data.Common.DbTransaction transaction, System.Threading.CancellationToken cancellationToken) [0x003cd] in <41fc39d200444af2a919390a606774d3>:0 
  at Dotmim.Sync.BaseOrchestrator.RunInTransactionAsync[T] (Dotmim.Sync.Enumerations.SyncStage stage, System.Func`4[T1,T2,T3,TResult] actionTask, System.Data.Common.DbConnection connection, System.Data.Common.DbTransaction transaction, System.Threading.CancellationToken cancellationToken) [0x00488] in <41fc39d200444af2a919390a606774d3>:0 
  at Dotmim.Sync.SyncAgent+<>c__DisplayClass53_0.<SynchronizeAsync>b__0 () [0x00df7] in <41fc39d200444af2a919390a606774d3>:0 
  at Dotmim.Sync.SyncAgent.SynchronizeAsync (Dotmim.Sync.Enumerations.SyncType syncType, System.Threading.CancellationToken cancellationToken, System.IProgress`1[T] progress) [0x00185] in <41fc39d200444af2a919390a606774d3>:0 
  at MediaStore.DatabaseHelper.SyncDatabase (System.String connString, Android.Content.Context context, System.Int32 custId) [0x000de] in C:\_Menci\7.felev\szakdoga\dotmim\MediaStore\DatabaseHelper.cs:53 }
```

**Comment by Mimetis** [comment]
Add on both side (client / server) :
``` cs
 var options = new SyncOptions
 {
     DisableConstraintsOnApplyChanges = true
 };
```

Because you did not declare your tables in the right order

**Comment by Menci77** [comment]
Thanks, it's working now!
So you mean here ``` var tables = new string[] { "media.Album", "media.Artist", "media.Customer", "media.Invoice", "media.InvoiceItem", "media.Track" };``` the order of the table names matter?
Although, can I ask the ```DisableConstraintsOnApplyChanges``` option's default value is true, so why do I have to specify it?
![image](https://user-images.githubusercontent.com/61515787/143228760-e1cfac6e-2487-4cf8-bed6-ab093da6cd75.png)

**Comment by Mimetis** [comment]
The last version set `DisableConstraintsOnApplyChanges` to `false` by default.

And yes, order is important
- The order of your tables is used for Insert / update
- Reverse order is used for deleting

In your case, I guess `Artist` should be before `Album` in your tables array, just because you can't create an album if you don't have an artist created before.

So, you can use `DisableConstraintsOnApplyChanges` if you're not sure of your tables order (or if you have any circular references)
Or you can use a good table orders to prevent using this property (that could be potentially slower because it requires to lock the entire table)
