### ISSUE TITLE
MariaDB : SQL syntax error on initial sync 

### ISSUE THREAD

**Issue by Varamil** [Mimetis/Dotmim.Sync#674]
I have mariaDB on a local network and when I try to perform my first sync I get this exception:

> You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'WHERE (IFNULL(NULLIF(`old`.`Name`, `new`.`Name`), NULLIF(`new`.`Name`,...' at line 31

The version of mariaDB is 10.3.29 and here is the initial table structure:

> CREATE TABLE `test` (
  `guid` binary(16) NOT NULL,
  `Name` text NOT NULL,
  `guidSomething` binary(16) DEFAULT NULL,
  `Value` text DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
>
> ALTER TABLE `test`
  ADD PRIMARY KEY (`guid`);
COMMIT;

Is there something wrong in my structure or it's a bug into the maria provider ?

**Comment by Mimetis** [comment]
Thanks @Varamil for the report issue.
I will test on my side with your table and see if i'm able to reproduce this bug.

**Comment by Mimetis** [comment]
Here is my test setup

Create the 2 mariadb databases and insert one record on server side:

``` sql
DROP DATABASE IF EXISTS `Client2`;
CREATE DATABASE  IF NOT EXISTS `Client2`;

DROP DATABASE IF EXISTS `Server`;
CREATE DATABASE  IF NOT EXISTS `Server`;

USE Server;

CREATE TABLE test (
guid binary(16) NOT NULL,
Name text NOT NULL,
guidSomething binary(16) DEFAULT NULL,
Value text DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE test
ADD PRIMARY KEY (guid);
COMMIT;

INSERT INTO `test` VALUES (_binary 'cfbda25c-df71','test',_binary 'cfbda25c-df72', 'test');

```

And here is the code that I used to sync, that eventually works:

``` cs
var serverProvider = new MariaDBSyncProvider(DBHelper.GetMariadbDatabaseConnectionString("Server"));
var clientProvider = new MariaDBSyncProvider(DBHelper.GetMariadbDatabaseConnectionString("Client2"));
var setup = new SyncSetup(new string[] { "test" });
var options = new SyncOptions();

await SynchronizeAsync(clientProvider, serverProvider, setup, options);

private static async Task SynchronizeAsync(CoreProvider clientProvider, CoreProvider serverProvider, SyncSetup setup, SyncOptions options)
{
    //var options = new SyncOptions();
    // Using the Progress pattern to handle progession during the synchronization
    var progress = new SynchronousProgress<ProgressArgs>(s =>
    {
        Console.ForegroundColor = ConsoleColor.Green;
        Console.WriteLine($"{s.ProgressPercentage:p}:  \t[{s.Source[..Math.Min(4, s.Source.Length)]}] {s.TypeName}:\t{s.Message}");
        Console.ResetColor();
    });

    // Creating an agent that will handle all the process
    var agent = new SyncAgent(clientProvider, serverProvider, options, setup);

    do
    {
        Console.Clear();
        Console.WriteLine("Sync start");
        try
        {
            var s = await agent.SynchronizeAsync(SyncType.Normal, progress);
            Console.WriteLine(s);
        }
        catch (SyncException e)
        {
            Console.WriteLine(e.ToString());
        }
        catch (Exception e)
        {
            Console.WriteLine("UNKNOW EXCEPTION : " + e.Message);
        }


        Console.WriteLine("Sync Ended. Press a key to start again, or Escapte to end");
    } while (Console.ReadKey().Key != ConsoleKey.Escape);

}

```

**Comment by Varamil** [comment]
Thank you, I'll also try this code when I can access to the database.
I haven't said, but the expected synchronization is between Maria and Sqlite, I'll try both cases to see if any differences.
And error occurs with net core 3.1 (not tested others).

**Comment by Varamil** [comment]
I've tried your test code, and I get the same exception:
```
Sync start
0.00 %:         [fcab] SessionBeginArgs:        Session Begins.
0.00 %:         [Serv] SchemaLoadedArgs:        Schema Loaded For 1 Tables.
Dotmim.Sync.SyncException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'WHERE (
            IFNULL(NULLIF(`old`.`Name`, `new`.`Name`), NULLIF(`new`.`Name`,...' at line 31
 ---> MySqlConnector.MySqlException (0x80004005): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'WHERE (
            IFNULL(NULLIF(`old`.`Name`, `new`.`Name`), NULLIF(`new`.`Name`,...' at line 31
 ---> MySqlConnector.MySqlException (0x80004005): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'WHERE (
            IFNULL(NULLIF(`old`.`Name`, `new`.`Name`), NULLIF(`new`.`Name`,...' at line 31
   at MySqlConnector.Core.ServerSession.ReceiveReplyAsyncAwaited(ValueTask`1 task) in /_/src/MySqlConnector/Core/ServerSession.cs:line 816
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in /_/src/MySqlConnector/Core/ResultSet.cs:line 49
   at MySqlConnector.MySqlDataReader.ActivateResultSet(CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 133
   at MySqlConnector.MySqlDataReader.CreateAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 437
   at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList`1 commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/CommandExecutor.cs:line 60
   at MySqlConnector.MySqlCommand.ExecuteNonQueryAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 264
   at Dotmim.Sync.BaseOrchestrator.InternalCreateTriggerAsync(SyncContext ctx, DbTableBuilder tableBuilder, DbTriggerType triggerType, DbConnection connection, DbTransaction transaction, CancellationToken cancellationToken, IProgress`1 progress)
   at Dotmim.Sync.BaseOrchestrator.InternalCreateTriggersAsync(SyncContext ctx, Boolean overwrite, DbTableBuilder tableBuilder, DbConnection connection, DbTransaction transaction, CancellationToken cancellationToken, IProgress`1 progress)
   at Dotmim.Sync.BaseOrchestrator.InternalProvisionAsync(SyncContext ctx, Boolean overwrite, SyncSet schema, SyncSetup setup, SyncProvision provision, Object scope, DbConnection connection, DbTransaction transaction, CancellationToken cancellationToken, IProgress`1 progress)
   at Dotmim.Sync.RemoteOrchestrator.<>c__DisplayClass3_0.<<EnsureSchemaAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Dotmim.Sync.BaseOrchestrator.RunInTransactionAsync[T](SyncStage stage, Func`4 actionTask, DbConnection connection, DbTransaction transaction, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Dotmim.Sync.BaseOrchestrator.RaiseError(Exception exception)
   at Dotmim.Sync.BaseOrchestrator.RunInTransactionAsync[T](SyncStage stage, Func`4 actionTask, DbConnection connection, DbTransaction transaction, CancellationToken cancellationToken)
   at Dotmim.Sync.BaseOrchestrator.RunInTransactionAsync[T](SyncStage stage, Func`4 actionTask, DbConnection connection, DbTransaction transaction, CancellationToken cancellationToken)
   at Dotmim.Sync.SyncAgent.<>c__DisplayClass53_0.<<SynchronizeAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Dotmim.Sync.SyncAgent.SynchronizeAsync(SyncType syncType, CancellationToken cancellationToken, IProgress`1 progress)
   at TestMaria.Program.SynchronizeAsync(CoreProvider clientProvider, CoreProvider serverProvider, SyncSetup setup, SyncOptions options) in C:\Users\abesnier\source\repos\TestMaria\Program.cs:line 43

``` 
On Client database, the table scope_info has been created with one line, and on test table, one trigger related to scop_info has been created. That's all.

**Comment by Mimetis** [comment]
Which version of MySql are you using ?

**Comment by Varamil** [comment]
The version is the 10.3.29, and MariaDB is hosted on a NAS on which this is the latest version available for the moment.

**Comment by Varamil** [comment]
So I've compiled the last source of dotmim.sync to get the full request that cause the failure :
```sql
CREATE TRIGGER `test_update_trigger` AFTER UPDATE ON `test` FOR EACH ROW 
Begin 
	UPDATE `test_tracking` 
	SET `update_scope_id` = NULL 
		,`timestamp` = ROUND(UNIX_TIMESTAMP(CURRENT_TIMESTAMP(6)) * 10000)
		,`last_change_datetime` = utc_timestamp()
	Where `test_tracking`.`guid` = new.`guid`
	 AND (
	    IFNULL(NULLIF(`old`.`Name`, `new`.`Name`), NULLIF(`new`.`Name`, `old`.`Name`)) IS NOT NULL
	 OR IFNULL(NULLIF(`old`.`guidSomething`, `new`.`guidSomething`), NULLIF(`new`.`guidSomething`, `old`.`guidSomething`)) IS NOT NULL
	 OR IFNULL(NULLIF(`old`.`Value`, `new`.`Value`), NULLIF(`new`.`Value`, `old`.`Value`)) IS NOT NULL
	 ) 
; 
IF (SELECT ROW_COUNT() = 0) THEN 
	INSERT INTO `test_tracking` (
		`guid`
		,`update_scope_id`
		,`timestamp`
		,`sync_row_is_tombstone`
		,`last_change_datetime`
	) 
	SELECT 
		new.`guid`
		,NULL
		,ROUND(UNIX_TIMESTAMP(CURRENT_TIMESTAMP(6)) * 10000)
		,0
		,utc_timestamp()
	 WHERE (
	    IFNULL(NULLIF(`old`.`Name`, `new`.`Name`), NULLIF(`new`.`Name`, `old`.`Name`)) IS NOT NULL
	 OR IFNULL(NULLIF(`old`.`guidSomething`, `new`.`guidSomething`), NULLIF(`new`.`guidSomething`, `old`.`guidSomething`)) IS NOT NULL
	 OR IFNULL(NULLIF(`old`.`Value`, `new`.`Value`), NULLIF(`new`.`Value`, `old`.`Value`)) IS NOT NULL
	 ) 
ON DUPLICATE KEY UPDATE
	`update_scope_id` = NULL, 
	`sync_row_is_tombstone` = 0, 
	`timestamp` = ROUND(UNIX_TIMESTAMP(CURRENT_TIMESTAMP(6)) * 10000), 
	`last_change_datetime` = utc_timestamp()
;
END IF;
End; 
```
And if I execute it on server side I get a failure too. However, after analysis, it seems there is a missing ``FROM `test` `` into the `INSERT INTO [...] SELECT [...]` condition before the `WHERE`. Adding that, the trigger is added without failure.

So, I guess `CreateUpdateTriggerCommand` from `MySqlBuilderTrigger` needs to be updated consequently.

Let me know if you need more info.

**Comment by Mimetis** [comment]
The last version is the version `10.6.5`, and the trigger is working fine.
I've tried with the version `10.3.5`
```
docker run --name mariadb103 -e MYSQL_ROOT_PASSWORD=Password12! -p 3308:3306 -d mariadb:10.3
```
And I've indeed the error raised

![image](https://user-images.githubusercontent.com/4592555/148943430-9c62de6b-bc61-4009-9aa6-6c296a360df8.png)

So far, can you upgrade your server to the last version `10.6.x` ?

Meanwhile, I will see if I can find something to be compatible with `10.3.x`

**Comment by Mimetis** [comment]
Seems that there is a lot of statements used in **DMS** that are not handled by **MariaDB** version `10.3.5` 
Not sure I will be able to make a compatible version
If you are good with sql statement in **MariaDB / MySql** I could need some help :)

**Comment by Varamil** [comment]
Additionally to the missing close `FROM` reported previously, I've found that in Procedure builder each `SELECT ROW_COUNT() LIMIT 1 INTO sync_row_count;` throw an error due to the `LIMIT 1`. Removing it, all procedures are created and the synchronization with the client is done correctly. 
Is `LIMIT 1` useful in some case ? I'm not aware that  `ROW_COUNT()` can returns more than one row, isn't it ?

So, since triggers and procedures are now correctly defines and the synchronization seems to be done without error (initial and after insert/delete/update on client table), is there any "evident" test I should do ? 

Since modification shouldn't affect newer version, would you like I make a pull request ?

**Comment by Mimetis** [comment]
Yes ! 
If you solved all the statement issues with MariaDB < 10.6, it would be super nice to make a PR !
Be careful that everything still runing on MySql
