### ISSUE TITLE
Windows Classic sample - GetTableBuilder error - does not have an implementation

### ISSUE THREAD

**Issue by spj-uk** [Mimetis/Dotmim.Sync#678]
System.TypeLoadException
  HResult=0x80131522
  Message=Method 'GetTableBuilder' in type 'Dotmim.Sync.SqlServer.SqlSyncProvider' from assembly 'Dotmim.Sync.SqlServer, Version=0.9.1.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
  Source=WindowsFormsClassic
  StackTrace:
   at WindowsFormsClassic.Form1.<button1_Click>d__3.MoveNext() in C:\Users\Simon\Downloads\Dotmim.Sync-master\Dotmim.Sync-master\Samples\WindowsFormsClassic\Form1.cs:line 53
   at System.Runtime.CompilerServices.AsyncVoidMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at WindowsFormsClassic.Form1.button1_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at WindowsFormsClassic.Program.Main() in C:\Users\Simon\Downloads\Dotmim.Sync-master\Dotmim.Sync-master\Samples\WindowsFormsClassic\Program.cs:line 19

**Comment by Mimetis** [comment]
Can you try to add the `Dotmim.Sync.Core` package as well ?

**Comment by spj-uk** [comment]
Dotmim.sync.Core is includes - trying to run your windows classic example :)

**Comment by spj-uk** [comment]
Changed to. 0.91 and worked
