### ISSUE TITLE
The type initializer for 'Microsoft.Data.Sqlite.SqliteConnection' threw an exception.

### ISSUE THREAD

**Issue by spj-uk** [Mimetis/Dotmim.Sync#707]
Syncing from SQL Server using webclientorchestrator to sqlite db with password

I get the error in the title when this line runs (line 167)

`var syncResult = await agent.SynchronizeAsync(SyncType.ReinitializeWithUpload, progress);`

Here is the trace

   at Dotmim.Sync.SyncAgent.<>c__DisplayClass53_0.<<SynchronizeAsync>b__0>d.MoveNext() in /home/vsts/work/1/s/Projects/Dotmim.Sync.Core/SyncAgent.cs:line 582
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dotmim.Sync.SyncAgent.<SynchronizeAsync>d__53.MoveNext() in /home/vsts/work/1/s/Projects/Dotmim.Sync.Core/SyncAgent.cs:line 388
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at SearchManager.cDBSync.<SynchroniseIncidentAsync>d__0.MoveNext() in XXX\YYY\cDBSync.cs:line 167

Is a winforms classic .net v4.6.1

NuGet packages inline with the classic windows example 
Dotmim.Sync.Sqlite v0.9.1
Microsoft.Data.Sqlite v6.0.2
Microsoft.Data,Sqlite.Core v6.0.2
SQlitePCLRaw.bundle_e_sqlite3 v2.0.6
SQLitePCLRaw.Core v2.0.7
SQLitePCLRaw.provider.dynamic_cdecl v2.0.4
SQLitePCLRaw.provider.e_sqlite3 v2.0.4
System.Data.Sqlite v1.0.113.6

**Comment by Mimetis** [comment]
Does it work if you are trying to access a **Sqlite** database, using `Microsoft.Data.Sqlite.SqliteConnection` ?

**Comment by Mimetis** [comment]
Just need to know if you are able to use Sqlite without anything else
Check https://docs.microsoft.com/en-us/dotnet/standard/data/sqlite/?tabs=netcore-cli and see if you are able to open and query your local database

**Comment by spj-uk** [comment]
I get a Microsoft.Data.Sqlite.SqliteException: 'SQLite Error 14: 'unable to open database file'.'

This exception was originally thrown at this call stack:
    Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(int, SQLitePCL.sqlite3)
    Microsoft.Data.Sqlite.SqliteConnectionInternal.SqliteConnectionInternal(Microsoft.Data.Sqlite.SqliteConnectionStringBuilder, Microsoft.Data.Sqlite.SqliteConnectionPool)
    Microsoft.Data.Sqlite.SqliteConnectionPool.GetConnection()
    Microsoft.Data.Sqlite.SqliteConnectionFactory.GetConnection(Microsoft.Data.Sqlite.SqliteConnection)
    Microsoft.Data.Sqlite.SqliteConnection.Open()
    WinFormsApp3.Form2.button1_Click(object, System.EventArgs) in Form2.cs
    System.Windows.Forms.Control.OnClick(System.EventArgs)
    System.Windows.Forms.Button.OnClick(System.EventArgs)
    System.Windows.Forms.Button.OnMouseUp(System.Windows.Forms.MouseEventArgs)
    System.Windows.Forms.Control.WmMouseUp(ref System.Windows.Forms.Message, System.Windows.Forms.MouseButtons, int)
    ...

**Comment by Mimetis** [comment]
Seems you have to resolve your issue with SQLite before trying anything else.
This issue is not related to DMS, I guess

**Comment by Mimetis** [comment]
`DMS` is working with `Microsoft.Data.Sqlite`.
