### ISSUE TITLE
Mysql example of AdventureWorks from docs doesn't work

### ISSUE THREAD

**Issue by ScarletKuro** [Mimetis/Dotmim.Sync#732]
database: https://github.com/Mimetis/Dotmim.Sync/blob/master/CreateMySqlAdventureWorks.sql
mysql version: 8.0.22

code
```CSharp
            const string serverConnectionString = "server=localhost;port=3306;database=adventureworks;uid=root;password=root";
            const string clientConnectionString = "server=localhost;port=3306;database=client;uid=root;password=root";
            // First provider on the server side, is using the Sql change tracking feature.
            var serverProvider = new MySqlSyncProvider(serverConnectionString);

            // IF you want to try with a MySql Database, use the [MySqlSyncProvider] instead
            // var serverProvider = new MySqlSyncProvider(serverConnectionString);

            // Second provider on the client side, is the [SqliteSyncProvider] used for SQLite databases
            // relying on triggers and tracking tables to create the sync environment
            var clientProvider = new MySqlSyncProvider(clientConnectionString);


            // Tables involved in the sync process:
            var tables = new string[] {"ProductCategory", "ProductModel", "Product",
                "Address", "Customer", "CustomerAddress", "SalesOrderHeader", "SalesOrderDetail" };

            // Creating an agent that will handle all the process
            var agent = new SyncAgent(clientProvider, serverProvider, tables);

            do
            {
                // Launch the sync process
                var s1 = agent.SynchronizeAsync().GetAwaiter().GetResult();
                // Write results
                Console.WriteLine(s1);

            } while (Console.ReadKey().Key != ConsoleKey.Escape);

            Console.WriteLine("End");
```

Exception:
```
Cannot add or update a child row: a foreign key constraint fails (`client`.`productcategory`, CONSTRAINT `FK_ProductCategory_ProductCategory_ParentProductCa_4tzgf2dnfqr` FOREIGN KEY (`ParentProductCategoryID`) REFERENCES `productcategory` (`ProductCategoryID)

   at Dotmim.Sync.LocalOrchestrator.<ApplyChangesAsync>d__7.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Dotmim.Sync.SyncAgent.<>c__DisplayClass53_0.<<SynchronizeAsync>b__0>d.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Dotmim.Sync.SyncAgent.<SynchronizeAsync>d__53.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at DotmimSync.Test.Program.Main(String[] args) in C:\Users\KuroPC\source\repos\DotmimSync.Test\DotmimSync.Test\Program.cs:line 36
```

**Comment by Mimetis** [comment]
Thanks for the feedback
The issue has been fixed in the last version.

Do not forget to disable check constraints to make it work:

``` cs
var options = new SyncOptions() { DisableConstraintsOnApplyChanges = true };
```
