### ISSUE TITLE
Increasing timeout doesn't work

### ISSUE THREAD

**Issue by BluePalmTree** [Mimetis/Dotmim.Sync#742]
I followed the instruction on [Increasing timeout](https://dotmimsync.readthedocs.io/Timeout.html) but our sync still timeouts after 30 seconds. We use the sync over HTTP. We also updated to version 0.9.4. What's weird is that we dont't get a timout on the inital sync with a couple of million rows but now with ~2700 rows we get a timeout.
I'm also not sure if this is a problem on the clientside or the serverside? We use SqlSyncChangeTrackingProvider on both sides.

## Serverside
**Code**
```c#
var options = new SyncOptions();
options.BatchSize = snapshotBatchSize;

if (!string.IsNullOrWhiteSpace(snapshotDirectory))
{
    options.SnapshotsDirectory = snapshotDirectory;
}

services.AddSyncServer<SqlSyncChangeTrackingProvider>(connectionString, "configScope", configSyncSetup, options);
```

**web.config**
```xml
<configuration>
  <location path="." inheritInChildApplications="false">
    <system.webServer>
      <handlers>
        <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModuleV2" resourceType="Unspecified" />
      </handlers>
      <aspNetCore requestTimeout="00:20:00" processPath="dotnet" arguments=".\Test.dll" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" hostingModel="inprocess" />
    </system.webServer>
  </location>
</configuration>
```
**ConnectionString**
```json
"DefaultConnection": "Server=SQLPOS;Initial Catalog=TestDB;Persist Security Info=False;User ID=XXX;Password=***;MultipleActiveResultSets=True;Encrypt=True;TrustServerCertificate=True;Connection Timeout=90;"
"SyncOptions": {
    "SnapshotDirectory": "C:\\temp\\snapshots",    
    "SnapshotBatchsize": 1000
  },
```

## Clientside
**Code**
```c#
if (_serverOrchestrator == null)
{
     //var handler = new HttpClientHandler { AutomaticDecompression = System.Net.DecompressionMethods.GZip };
     //var client = new HttpClient(handler) { Timeout = TimeSpan.FromMinutes(20) };
      _serverOrchestrator = new WebClientOrchestrator(BuildSyncUri());
      _serverOrchestrator.HttpClient.Timeout = TimeSpan.FromMinutes(20);
}
//----------------
 _agentConfig = new SyncAgent(_clientProvider, _serverOrchestrator, "configScope");
_agentConfig.Options.BatchSize = 2000;
_agentConfig.Options.ConflictResolutionPolicy = Dotmim.Sync.Enumerations.ConflictResolutionPolicy.ServerWins;
```

**ErrorMessage**
```
Test.DataModel.PosDBSync
Error during Config sync

Dotmim.Sync.SyncException: Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding. ---> Microsoft.Data.SqlClient.SqlException: Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding. ---> System.ComponentModel.Win32Exception: Der Wartevorgang wurde abgebrochen
   --- End of inner exception stack trace ---
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__201_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dotmim.Sync.SqlServer.Builders.SqlSyncAdapter.<ExecuteBatchCommandAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dotmim.Sync.BaseOrchestrator.<InternalApplyChangesBatchAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dotmim.Sync.BaseOrchestrator.<InternalApplyTableChangesAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dotmim.Sync.BaseOrchestrator.<InternalApplyChangesAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dotmim.Sync.LocalOrchestrator.<>c__DisplayClass7_0.<<ApplyChangesAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dotmim.Sync.BaseOrchestrator.<RunInTransactionAsync>d__67`1.MoveNext()
   --- End of inner exception stack trace ---
   at Dotmim.Sync.BaseOrchestrator.RaiseError(Exception exception)
   at Dotmim.Sync.BaseOrchestrator.<RunInTransactionAsync>d__67`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Dotmim.Sync.BaseOrchestrator.<RunInTransactionAsync>d__67`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dotmim.Sync.SyncAgent.<>c__DisplayClass53_0.<<SynchronizeAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dotmim.Sync.SyncAgent.<SynchronizeAsync>d__53.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Test.DataModel.PosDBSync.<SyncConfigAsync>d__20.MoveNext()
```
![SyncErrorMessage](https://user-images.githubusercontent.com/74594456/171132365-08912f59-b32d-48c6-9656-c1bb8d2f3a6d.png)

**Comment by BluePalmTree** [comment]
Thanks for the fast answer. Is there a way to log on which row the problem maybe happens?
