### ISSUE TITLE
Not Found exception on subsequent sync

### ISSUE THREAD

**Issue by spj-uk** [Mimetis/Dotmim.Sync#756]
Using WebClientOrcestrator to sync SQL Server to local database using code from the WinForms classic example. The first time it runs through, but if I run it again I get an exception as below.

The progress text:

Session Begins.
Getting Server Scope : ScopeName: DefaultScope
Retry Sending Http Request (1/10.....

.... 10/10. ....
Not Found

This is the stack trace:

   at Dotmim.Sync.Web.Client.HttpRequestHandler.<HandleSyncError>d__15.MoveNext() in /home/vsts/work/1/s/Projects/Dotmim.Sync.Web.Client/HttpRequestHandler.cs:line 264
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dotmim.Sync.Web.Client.HttpRequestHandler.<SendAsync>d__14.MoveNext() in /home/vsts/work/1/s/Projects/Dotmim.Sync.Web.Client/HttpRequestHandler.cs:line 194
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dotmim.Sync.SyncPolicy.<InternalExecuteAsync>d__17`1.MoveNext() in /home/vsts/work/1/s/Projects/Dotmim.Sync.Core/SyncPolicy.cs:line 132
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dotmim.Sync.Web.Client.HttpRequestHandler.<ProcessRequestAsync>d__12.MoveNext() in /home/vsts/work/1/s/Projects/Dotmim.Sync.Web.Client/HttpRequestHandler.cs:line 108
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dotmim.Sync.Web.Client.WebClientOrchestrator.<GetServerScopeAsync>d__34.MoveNext() in /home/vsts/work/1/s/Projects/Dotmim.Sync.Web.Client/WebClientOrchestrator.cs:line 183
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dotmim.Sync.SyncAgent.<>c__DisplayClass53_0.<<SynchronizeAsync>b__0>d.MoveNext() in /home/vsts/work/1/s/Projects/Dotmim.Sync.Core/SyncAgent.cs:line 577
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dotmim.Sync.SyncAgent.<SynchronizeAsync>d__53.MoveNext() in /home/vsts/work/1/s/Projects/Dotmim.Sync.Core/SyncAgent.cs:line 388
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at xxx.yyy.<SynchroniseAsync>d__2.MoveNext() in C:\Development\xxx\yyy\zzz\sync.cs:line 236

Odd as would expect it to behave the same way on each run? Am I missing a trick somewhere?

**Comment by spj-uk** [comment]
Problem in chair not in Dotmim :)
