### ISSUE TITLE
DMS v0.95 Violation of PRIMARY KEY constraint 'PK_scope_info_history'. 

### ISSUE THREAD

**Issue by VagueGit** [Mimetis/Dotmim.Sync#761]
We sync 41 tables between SQL Server via http and SQLite. We have a sync scope for all tables and a sync scope for each table. I was able to sync a new database using 0.95. The app:
Creates and initialise a new server database
Creates a SQLite database on the client and syncs initial data from the server using sync scope All.
The user chooses some options and those are synced back to the server using sync scope All.

That all went well.

I then connected a new client to that server. DMS then began syncing the server data to the new client. We sync from the server to a new client one table at a time so we have a sync scope for each table.

The first table synced correctly using the first sync scope. The exception was thrown attempting to sync the second table with the second sync scope.

The sync agent is instantiated like this
```
SqliteSyncProvider clientProvider = GetSqliteSyncProvider();
WebRemoteOrchestrator webRemoteOrchestrator = GetWebRemoteOrchestrator();
SyncOptions syncOptions = GetSyncOptions();
SyncAgent agent = new SyncAgent(clientProvider, webRemoteOrchestrator, syncOptions);
```
We sync like this
```
syncSetup = new SyncScopes().GetSyncSetup(scopeName);
syncAgent = ConfigureSyncAgent();
syncResult = await syncAgent.SynchronizeAsync(scopeName: scopeName, setup: syncSetup, syncType: syncType, progress: progress);
```
The full exception message is
`Violation of PRIMARY KEY constraint 'PK_scope_info_history'. Cannot insert duplicate key in object 'dbo.scope_info_history'. The duplicate key value is (8047fda2-0899-4d6f-a450-b1f3118044c3).`

The stack trace
```
   at Dotmim.Sync.Web.Client.HttpRequestHandler.<HandleSyncError>d__15.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dotmim.Sync.Web.Client.HttpRequestHandler.<SendAsync>d__14.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Dotmim.Sync.SyncPolicy.<InternalExecuteAsync>d__17`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dotmim.Sync.Web.Client.HttpRequestHandler.<ProcessRequestAsync>d__12.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dotmim.Sync.Web.Client.WebRemoteOrchestrator.<InternalApplyThenGetChangesAsync>d__0.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Dotmim.Sync.Web.Client.WebRemoteOrchestrator.<InternalApplyThenGetChangesAsync>d__0.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dotmim.Sync.SyncAgent.<SynchronizeAsync>d__27.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Wbl.Services.DataSyncService.<SyncAsync>d__25.MoveNext() in C:\Repos\VU\Wbl\Services\DataSyncService.cs:line 456
```
**EDIT 1** duplicate key value (8047fda2-0899-4d6f-a450-b1f3118044c3) is the sync_scope_id of the first of the individual tables synced. It seems the same id was generated for the second table sycned.

**Comment by Mimetis** [comment]
Are you using a différent scope name for each scope ?
Can you check on server side if scope history has à composite pkey ? (scope id and scope name)

**Comment by Mimetis** [comment]
Did you called the upgrade method on the server side ? (if you are using an existing server prevuously on 0.94)

**Comment by VagueGit** [comment]
Each scope uses the table name as the scope name.
The pk for scope_info_history on the server is sync_scope_id
This database is not an upgrade. It was created for DMS 0.95. Both server and local dbs were provisioned by DMS 0.95

**Comment by Mimetis** [comment]
Can you manually set the pkey on history table on scope id and scope name ?

**Comment by Mimetis** [comment]
There is no way you have only one column as primary key in the history table, if you started the sync from scratch with a server database that have never been used with DMS before.

If you look the creation script here, the table is created with 2 columns as pkeys:
https://github.com/Mimetis/Dotmim.Sync/blob/c2cc24f612a30e3d7caa01b2bde01d73c066141c/Projects/Dotmim.Sync.SqlServer/Builders/SqlScopeBuilder.cs#L118

So far, my guess on your situation:
- You are using a server database that was previously provisioned with version <= 0.94. Then you need to call the UpgradeAsync method
- You are using a server database back that was previously provisioned with version <= 0.94 but you did not removed all the scope tables
- You are using a script to create the tables that have the previous version of scopes server tables

Please try to verify your server database, and let met know

**Comment by VagueGit** [comment]
I'd lazily copied a database create script from an existing database ... that's where the old scope history came from.

Apologies for wasting your time. I'm a complete goose
