### ISSUE TITLE
AzureSQL v SQL Server

### ISSUE THREAD

**Issue by champcbg** [Mimetis/Dotmim.Sync#788]
When I execute my provision logic it works correctly on SQL Server.

When i execute the same logic on AzureSQL I get this error

   ```
at Dotmim.Sync.BaseOrchestrator.<>c__DisplayClass84_0.<SetRelations>b__1(DbRelationColumnDefinition kc)
   at System.Linq.Enumerable.SelectIPartitionIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToList()
   at Dotmim.Sync.BaseOrchestrator.SetRelations(List`1 relations, SyncSet schema)
   at Dotmim.Sync.BaseOrchestrator.<InternalGetSchemaAsync>d__79.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Dotmim.Sync.BaseOrchestrator.<InternalGetSchemaAsync>d__79.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dotmim.Sync.RemoteOrchestrator.<InternalGetServerScopeInfoAsync>d__37.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Dotmim.Sync.RemoteOrchestrator.<InternalGetServerScopeInfoAsync>d__37.MoveNext()
```

this is the code that executes for both processes.

  ```
// Create a server orchestrator used to Deprovision everything on the server side
        var connectionString = inspirationDb.Database.GetDbConnection().ConnectionString;
        _remoteOrchestrator = new RemoteOrchestrator(new SqlSyncProvider(connectionString));

        _clientSetup =
            new SyncSetup(InspirationDbContext.NewSyncTables.Union(UserDbContext.NewSyncTables).Union(InsightsDbContext.NewSyncTables))
            {
                StoredProceduresPrefix = DotmimSyncConstants.SyncSprocPrefix,
                StoredProceduresSuffix = "",
                TrackingTablesPrefix = DotmimSyncConstants.SyncTrackingTablePrefix,
                TrackingTablesSuffix = "",
                TriggersPrefix = DotmimSyncConstants.SyncTriggersPrefix,
                TriggersSuffix = "",
                //Version = "4"
                //ScopeName = scopeName
            };

... removed filters and directions ...        

        _progress = new SynchronousProgress<ProgressArgs>(pa =>
        {
            Logger.LogInformation($"{pa.Context.SessionId} - {pa.Context.SyncStage}\t {pa.Message}");

            RecordSyncProgressEvent(pa);
        });

```

**Comment by Mimetis** [comment]
Can you share the error message ?

**Comment by champcbg** [comment]
**Exception Messagea**
e = {"Object reference not set to an instance of an object."}

**Exception Stacktrace**
Dotmim.Sync.SyncException: Object reference not set to an instance of an object.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Dotmim.Sync.BaseOrchestrator.<>c__DisplayClass84_0.<SetRelations>b__1(DbRelationColumnDefinition kc)
   at System.Linq.Enumerable.SelectIPartitionIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToList()
   at Dotmim.Sync.BaseOrchestrator.SetRelations(List`1 relations, SyncSet schema)
   at Dotmim.Sync.BaseOrchestrator.InternalGetSchemaAsync(SyncContext context, SyncSetup setup, DbConnection connection, DbTransaction transaction, CancellationToken cancellationToken, IProgress`1 progress)
   at Dotmim.Sync.BaseOrchestrator.InternalGetSchemaAsync(SyncContext context, SyncSetup setup, DbConnection connection, DbTransaction transaction, CancellationToken cancellationToken, IProgress`1 progress)
   at Dotmim.Sync.RemoteOrchestrator.InternalGetServerScopeInfoAsync(SyncContext context, SyncSetup setup, DbConnection connection, DbTransaction transaction, CancellationToken cancellationToken, IProgress`1 progress)
   at Dotmim.Sync.RemoteOrchestrator.InternalGetServerScopeInfoAsync(SyncContext context, SyncSetup setup, DbConnection connection, DbTransaction transaction, CancellationToken cancellationToken, IProgress`1 progress)
   --- End of inner exception stack trace ---
   at Dotmim.Sync.RemoteOrchestrator.ProvisionAsync(String scopeName, SyncSetup setup, SyncProvision provision, Boolean overwrite, DbConnection connection, DbTransaction transaction, CancellationToken cancellationToken, IProgress`1 progress)
   at SStG.Web.App.Inspiration.Core.Data.InspirationServerAppMigrationProvisioning.ProvisionAsync(String requiredAndroidVersion, String requirediOSVersion) in C:\dev\champcbg\SStG-Platform\SStG.Web.App.Inspiration\Core\Data\InspirationServerAppMigrationProvisioning.cs:line 194

**Exception [JSON]**
{
    "TypeName": "NullReferenceException",
    "SyncStage": 7,
    "Number": 0,
    "DataSource": "tcp:sql-sstg-prod.database.windows.net,1433",
    "InitialCatalog": "sqldb-sstg-platform-TEST",
    "Side": 1,
    "Message": "Object reference not set to an instance of an object.",
    "Data": {},
    "InnerException": {
        "ClassName": "System.NullReferenceException",
        "Message": "Object reference not set to an instance of an object.",
        "Data": {},
        "InnerException": null,
        "HelpURL": null,
        "StackTraceString": "   at Dotmim.Sync.BaseOrchestrator.<>c__DisplayClass84_0.<SetRelations>b__1(DbRelationColumnDefinition kc)rn   at System.Linq.Enumerable.SelectIPartitionIterator`2.MoveNext()rn   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToList()rn   at Dotmim.Sync.BaseOrchestrator.SetRelations(List`1 relations, SyncSet schema)rn   at Dotmim.Sync.BaseOrchestrator.InternalGetSchemaAsync(SyncContext context, SyncSetup setup, DbConnection connection, DbTransaction transaction, CancellationToken cancellationToken, IProgress`1 progress)rn   at Dotmim.Sync.BaseOrchestrator.InternalGetSchemaAsync(SyncContext context, SyncSetup setup, DbConnection connection, DbTransaction transaction, CancellationToken cancellationToken, IProgress`1 progress)rn   at Dotmim.Sync.RemoteOrchestrator.InternalGetServerScopeInfoAsync(SyncContext context, SyncSetup setup, DbConnection connection, DbTransaction transaction, CancellationToken cancellationToken, IProgress`1 progress)rn   at Dotmim.Sync.RemoteOrchestrator.InternalGetServerScopeInfoAsync(SyncContext context, SyncSetup setup, DbConnection connection, DbTransaction transaction, CancellationToken cancellationToken, IProgress`1 progress)",
        "RemoteStackTraceString": null,
        "RemoteStackIndex": 0,
        "ExceptionMethod": null,
        "HResult": -2147467261,
        "Source": "Dotmim.Sync.Core",
        "WatsonBuckets": null
    },
    "HelpLink": null,
    "Source": "Dotmim.Sync.Core",
    "HResult": -2146233088,
    "StackTrace": "   at Dotmim.Sync.RemoteOrchestrator.ProvisionAsync(String scopeName, SyncSetup setup, SyncProvision provision, Boolean overwrite, DbConnection connection, DbTransaction transaction, CancellationToken cancellationToken, IProgress`1 progress)rn   at SStG.Web.App.Inspiration.Core.Data.InspirationServerAppMigrationProvisioning.ProvisionAsync(String requiredAndroidVersion, String requirediOSVersion) in C:devchampcbgSStG-PlatformSStG.Web.App.InspirationCoreDataInspirationServerAppMigrationProvisioning.cs:line 194"
}

**Comment by Mimetis** [comment]
Hum, will be hard to debug this one...

Do you know on which table the problem is occurring?
Are you able to create a simple reproduction example ? 
Will help me a lot to determine what's the problem is .

**Comment by champcbg** [comment]
Not sure what table it is.

It will probably be easier for me to code and try debug, vs trying to create an example.

I can try that in couple of days, for now, I just bacpac'ed the DB over from SQL Server to Azure to continue testing.

There is possibly one more set of migrations to come, I could retry after that.

**Comment by Mimetis** [comment]
OK let me know
