### ISSUE TITLE
GetScopeInfoAsync Internal Server Error

### ISSUE THREAD

**Issue by BluePalmTree** [Mimetis/Dotmim.Sync#850]
Hello,
I try to implement the multiple scopes migration. But when I try to use `RemoteOrchestrator.GetScopeInfoAsync` I get a internal server error.

### Code-Client

``` c#
var scopeMigration = await GetScopeNameAsync(_configScope, agentConfig);
s1 = await agentConfig.SynchronizeAsync(scopeMigration.OldScopeName, parameters, _progress);
_logger.LogInformation(4810, "Sync Config Result: {Result}", s1);

if (scopeMigration.IsNew)
{
	var serverScopeInfo = await agentConfig.RemoteOrchestrator.GetScopeInfoAsync(scopeMigration.NewScopeName);
	var newScopeInfo = await agentConfig.LocalOrchestrator.ProvisionAsync(serverScopeInfo);

	var newScopeInfoClient = await agentConfig.LocalOrchestrator.GetScopeInfoClientAsync(newScopeInfo.Name);
	var oldScopeInfoClient = await agentConfig.LocalOrchestrator.GetScopeInfoClientAsync(scopeMigration.OldScopeName);

	newScopeInfoClient.ShadowScope(oldScopeInfoClient);
	await agentConfig.LocalOrchestrator.SaveScopeInfoClientAsync(newScopeInfoClient);
}
```

### Code-Server

``` c#
/// <summary>
/// This POST handler is mandatory to handle all the sync process
/// </summary>
/// <returns></returns>
[HttpPost]
public async Task Post()
{
	try
	{
		var scopeName = HttpContext.GetScopeName();

		var webserverAgent = webserverAgents.FirstOrDefault(c => c.ScopeName == scopeName);

		await webserverAgent.HandleRequestAsync(HttpContext).ConfigureAwait(false);
	}
	catch (Exception ex)
	{
		_logger.LogError(ex, ex.Message);
		throw;
	}
}
```

### Error
```
2022-10-28 08:32:56.237 +02:00 [ERR] An unhandled exception has occurred while executing the request.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Random.DatabaseSync.Controllers.SyncController.Post()
   at lambda_method4(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
2022-10-28 08:32:56.241 +02:00 [WRN] No exception handler was found, rethrowing original exception.
2022-10-28 08:32:56.241 +02:00 [ERR] Connection ID "18014398511092611197", Request ID "80003881-0000-fa00-b63f-84710c7967bb": An unhandled exception was thrown by the application.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Random.DatabaseSync.Controllers.SyncController.Post()
   at lambda_method4(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.HandleException(HttpContext context, ExceptionDispatchInfo edi)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContextOfT`1.ProcessRequestAsync()
2022-10-28 08:32:56.243 +02:00 [INF] Request finished HTTP/1.1 POST http://10.0.0.92:8004/api/sync/ application/json 86 - 500 - - 22.4363ms
2022-10-28 08:32:56.781 +02:00 [INF] Request starting HTTP/1.1 POST http://10.0.0.92:8004/api/sync/ application/json 86
2022-10-28 08:32:56.781 +02:00 [INF] Executing endpoint 'Random.DatabaseSync.Controllers.SyncController.Post (Random.DatabaseSync)'
2022-10-28 08:32:56.781 +02:00 [INF] Route matched with {action = "Post", controller = "Sync"}. Executing controller action with signature System.Threading.Tasks.Task Post() on controller Random.DatabaseSync.Controllers.SyncController (Random.DatabaseSync).
2022-10-28 08:32:56.781 +02:00 [ERR] Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Random.DatabaseSync.Controllers.SyncController.Post()
2022-10-28 08:32:56.782 +02:00 [INF] Executed action Random.DatabaseSync.Controllers.SyncController.Post (Random.DatabaseSync) in 0.8425ms
2022-10-28 08:32:56.782 +02:00 [INF] Executed endpoint 'Random.DatabaseSync.Controllers.SyncController.Post (Random.DatabaseSync)'
2022-10-28 08:32:56.782 +02:00 [ERR] An unhandled exception has occurred while executing the request.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Random.DatabaseSync.Controllers.SyncController.Post()
   at lambda_method4(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
2022-10-28 08:32:56.783 +02:00 [WRN] No exception handler was found, rethrowing original exception.
2022-10-28 08:32:56.783 +02:00 [ERR] Connection ID "18014398511092611197", Request ID "80003882-0000-fa00-b63f-84710c7967bb": An unhandled exception was thrown by the application.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Random.DatabaseSync.Controllers.SyncController.Post()
   at lambda_method4(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.HandleException(HttpContext context, ExceptionDispatchInfo edi)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContextOfT`1.ProcessRequestAsync()
2022-10-28 08:32:56.784 +02:00 [INF] Request finished HTTP/1.1 POST http://10.0.0.92:8004/api/sync/ application/json 86 - 500 - - 2.9724ms
```

**Comment by Mimetis** [comment]
can you try with the last source code ?

**Comment by BluePalmTree** [comment]
I'm using Version 0.9.7. Should I try a beta version?

**Comment by Mimetis** [comment]
You code seems good.
I remembered fixing a small issue in the master branch
Not sure it's that, but it's worth a try to clone the repository and try directly the source code

**Comment by BluePalmTree** [comment]
I think I found the problem. In the SyncController the webserverAgents don't know of the new scope. Is there a way to refresh the webeserverAgents?

**Comment by Mimetis** [comment]
Ok, I got it.
You've created the scope on the server, but you did not declare the setup (with scopename) in your asp.net web api, right ?

Eventually this line 

``` cs
var webserverAgent = webserverAgents.FirstOrDefault(c => c.ScopeName == scopeName);
```
is throwing the error, I guess.

A first question I have is

Do you have created this new scope in the server database, using another process (like a console app or something else) or the scope is not yet existing on the server ?

If the scope is not existing, somewhere you have to create it, before using it

2 solutions:

Declare the Setup and scopename in your dependency injection processus, from your asp.net core web api
On the first call of a client, the scope will be created on the server (internally it will call the `ProvisionAsync` method):

Let's imagine we have a new scope called "`custScope`":
``` cs
public void ConfigureServices(IServiceCollection services)
{
    services.AddControllers();
    services.AddDistributedMemoryCache();
    services.AddSession(options => options.IdleTimeout = TimeSpan.FromMinutes(30));

    var connectionString = Configuration.GetSection("ConnectionStrings")["SqlConnection"];

    var options = new SyncOptions();

    var tables = new string[] {"ProductCategory", "ProductModel", "Product"};
    services.AddSyncServer<SqlSyncProvider>(connectionString, tables, options);
        
    var tables2 = new string[] { "Address", "Customer", "CustomerAddress", "SalesOrderHeader", "SalesOrderDetail" };
    services.AddSyncServer<SqlSyncProvider>("custScope", connectionString, tables2, options);
}

```

If you can't restart your application, or you want to create the scope before first client call, you can add the scope on the server by calling the ProvisionAsync directly, with a console application for example:

```cs
var serverProvider = new SqlSyncProvider(serverConnectionString);
var remoteOrchestrator = new RemoteOrchestrator(serverProvider);
var setup = new SyncSetup("Address", "Customer", "CustomerAddress", "SalesOrderHeader", "SalesOrderDetail" );
await remoteOrchestrator.ProvisionAsync("custScope", setup)
```
That's being said, with this technic, your asp.net core does not know anything about this new scope created

you can use this kind of code to retrieve and existing scope directly from your web api code:

``` cs
[HttpPost]
public async Task Post()
{
    var scopeName = HttpContext.GetScopeName();
    var serverProvider = new SqlSyncProvider(cString);
    var remoteOrchestrator = new RemoteOrchestrator(serverProvider);
    var scopeInfo = await remoteOrchestrator.GetScopeInfoAsync("custScope").ConfigureAwait(false);
    var webServerAgent = new WebServerAgent(serverProvider, scopeInfo.Setup, 
            options, webServerOptions, scopeInfo.Name);

    await webserverAgent.HandleRequestAsync(HttpContext).ConfigureAwait(false);
}

```

That's being said, it's not optimized, I guess you should cache the setup once you get it from the database 

Make sense ?

**Comment by Mimetis** [comment]
Did you find a correct solution ?

**Comment by BluePalmTree** [comment]
Hi, yes. Creating a custom WebServerAgent did the trick.
The problem is, when we start the Sync app it only knows the v1 Scopes. But we use a console programm to provision new scopes after we changed the database (like in the migration sample). But we don't update the appsettings of the sync programm (where the scopes are definied). 
I also added memory caching to lessen the load.

Thank you for the amazing work :)

**Comment by Mimetis** [comment]
Can you share the code you ve used for the caching ?
Could help other users 👍

**Comment by BluePalmTree** [comment]
Sure.

In the `Startup.cs` you have to add the line:

```c#
services.AddMemoryCache();
```

And this is the code for the controller action:

```c#
public SyncController(IConfiguration configuration,
					  IEnumerable<WebServerAgent> webServerAgents,
					  ILogger<SyncController> logger,
					  IMemoryCache memoryCache)
{
	_configuration = configuration ?? throw new ArgumentNullException(nameof(configuration));
	_logger = logger ?? throw new ArgumentNullException(nameof(logger));
	_memoryCache = memoryCache ?? throw new ArgumentNullException(nameof(memoryCache));

	this.webserverAgents = webServerAgents ?? throw new ArgumentNullException(nameof(webServerAgents));
}

[HttpPost]
public async Task Post()
{
	try
	{
		var scopeName = HttpContext.GetScopeName();

		var webserverAgent = webserverAgents.FirstOrDefault(c => c.ScopeName == scopeName);

		if (webserverAgent == null)
		{
			if (!_memoryCache.TryGetValue(scopeName, out webserverAgent))
			{
				var connectionString = _configuration.GetConnectionString("DefaultConnection");
				var syncOptions = _configuration.GetSection("SyncOptions");
				var snapshotDirectory = syncOptions.GetValue<string>("SnapshotDirectory");
				var snapshotBatchSize = syncOptions.GetValue<int>("SnapshotBatchsize");

				var options = new SyncOptions
				{
					BatchSize = snapshotBatchSize
				};

				if (!string.IsNullOrWhiteSpace(snapshotDirectory))
				{
					options.SnapshotsDirectory = snapshotDirectory;
				}

				var serverProvider = new SqlSyncChangeTrackingProvider(connectionString);
				var remoteOrchestrator = new RemoteOrchestrator(serverProvider);
				var scopeInfo = await remoteOrchestrator.GetScopeInfoAsync(scopeName).ConfigureAwait(false);
				webserverAgent = new WebServerAgent(serverProvider, scopeInfo.Setup, options, null, scopeInfo.Name);

				_memoryCache.Set(scopeName, webserverAgent, new MemoryCacheEntryOptions().SetSlidingExpiration(TimeSpan.FromSeconds(90)));
			}
		}

		await webserverAgent.HandleRequestAsync(HttpContext).ConfigureAwait(false);
	}
	catch (Exception ex)
	{
		_logger.LogError(ex, ex.Message);
		throw;
	}
}
```

**Comment by Mimetis** [comment]
thanks
awesome work !!
