### ISSUE TITLE
MySQL Provider `Read must be called first.`

### ISSUE THREAD

**Issue by jakemdunn** [Mimetis/Dotmim.Sync#851]
Getting an unhandled exception in our setup, we're basically following the setup recommended for syncing preexisting local data on first sync (https://dotmimsync.readthedocs.io/AlreadyExisting.html).

We're also doing filtering and going over a web proxy, which is working a charm the majority of the time. But occasionally, after calling `UpdateUntrackedRowsAsync` after the initial provisioning and sync, the following exception is thrown:

```
      Job Sync.SyncEmitClient threw an unhandled Exception: 
Dotmim.Sync.Web.Client.HttpSyncWebException: Read must be called first.
-----------------------
   at Dotmim.Sync.RemoteOrchestrator.InternalApplyThenGetChangesAsync(ScopeInfoClient cScopeInfoClient, ScopeInfo cScopeInfo, SyncContext context, ClientSyncChanges clientChanges, DbConnection connection, DbTransaction transaction, CancellationToken cancellationToken, IProgress`1 progress)
   at Dotmim.Sync.Web.Server.WebServerAgent.ApplyThenGetChangesAsync2(HttpContext httpContext, HttpMessageSendChangesRequest httpMessage, SessionCache sessionCache, Int32 clientBatchSize, CancellationToken cancellationToken, IProgress`1 progress)
   at Dotmim.Sync.Web.Server.WebServerAgent.HandleRequestAsync(HttpContext httpContext, Action`1 action, CancellationToken cancellationToken, IProgress`1 progress)
-----------------------
-----------------------
INNER EXCEPTION
-----------------------
Read must be called first.
-----------------------
   at MySqlConnector.Core.ResultSet.GetCurrentRow() in /_/src/MySqlConnector/Core/ResultSet.cs:line 358
   at MySqlConnector.MySqlDataReader.GetGuid(Int32 ordinal) in /_/src/MySqlConnector/MySqlDataReader.cs:line 240
   at Dotmim.Sync.BaseOrchestrator.InternalReadScopeInfoClient(DbDataReader reader)
   at Dotmim.Sync.BaseOrchestrator.InternalSaveScopeInfoClientAsync(ScopeInfoClient scopeInfoClient, SyncContext context, DbConnection connection, DbTransaction transaction, CancellationToken cancellationToken, IProgress`1 progress)
   at Dotmim.Sync.BaseOrchestrator.InternalSaveScopeInfoClientAsync(ScopeInfoClient scopeInfoClient, SyncContext context, DbConnection connection, DbTransaction transaction, CancellationToken cancellationToken, IProgress`1 progress)
   at Dotmim.Sync.RemoteOrchestrator.InternalApplyThenGetChangesAsync(ScopeInfoClient cScopeInfoClient, ScopeInfo cScopeInfo, SyncContext context, ClientSyncChanges clientChanges, DbConnection connection, DbTransaction transaction, CancellationToken cancellationToken, IProgress`1 progress)
   at Dotmim.Sync.RemoteOrchestrator.InternalApplyThenGetChangesAsync(ScopeInfoClient cScopeInfoClient, ScopeInfo cScopeInfo, SyncContext context, ClientSyncChanges clientChanges, DbConnection connection, DbTransaction transaction, CancellationToken cancellationToken, IProgress`1 progress)
   at Dotmim.Sync.RemoteOrchestrator.InternalApplyThenGetChangesAsync(ScopeInfoClient cScopeInfoClient, ScopeInfo cScopeInfo, SyncContext context, ClientSyncChanges clientChanges, DbConnection connection, DbTransaction transaction, CancellationToken cancellationToken, IProgress`1 progress)
-----------------------
```

Looking through the stack trace, it appears to be sourced from the following chunk of code (as best as I can tell):

https://github.com/Mimetis/Dotmim.Sync/blob/849210007f2975b401e7df2bd3f026ae49fc82b9/Projects/Dotmim.Sync.Core/Orchestrators/Scopes/BaseOrchestrator.ScopeInfoClients.cs#L234-L238

There is a bit of a discrepancy on that `reader.Read()` vs the other instances in the file as well. There's no conditional check in this location, which is fine if one can assume that there will always be data. Something about my setup, or pushing preexisting data with two rapid syncs, appears to defy that expectation.

If there's some way to capture that error and retry, we could probably sidestep the problem. Long term though, perhaps there should be an `if` or `while` wrapping that `reader.Read()`.

**Comment by jakemdunn** [comment]
....Every time. Every time I finally bite the bullet and file a potential defect, I find the issue in my own code within a matter of minutes:

```
            try {
                _syncStatus.LastSync = await agent.SynchronizeAsync(parameters, progress);
            } catch (Exception exception) {
                _logger.LogCritical(exception.Message);
                _logger.LogCritical(exception.StackTrace);
                _logger.LogCritical(exception.ToString());
                _syncStatus.SyncProcessStatus = SyncProcessStatus.FAILURE;
                return;
            }

            if(firstSync) {
                try {
                    await agent.LocalOrchestrator.UpdateUntrackedRowsAsync();
                    await agent.SynchronizeAsync();
                } catch (Exception exception) {
```

Entirely spaced adding parameters to the second sync. Added them in, doesn't appear to be an issue anymore. Testing it a bit more, but thanks for facilitating my debugging process with this ticket, I suppose.

**Comment by jakemdunn** [comment]
Confirmed with additional testing, that fixed. So, I suppose - if anyone else runs across `Read must be called first.`, check the `SynchronizeAsync` calls if you have multiple, make sure they're using the same parameters
