### ISSUE TITLE
Only in Net48: Dotmim.Sync.SyncException: Cannot write to a closed TextWriter.

### ISSUE THREAD

**Issue by hakakou** [Mimetis/Dotmim.Sync#903]
I have two SQL servers syncing for about 2 year now, both of them using SqlSyncChangeTrackingProvider. I recently upgraded to the latest 0.9.7 and have noticed the following:

I had created a small netstandard2.0 class lib that only references ```Dotmim.Sync.SqlServer.ChangeTracking``` and has a very simple Execute method. Only the default options are used:

```cs
serverProvider = new SqlSyncChangeTrackingProvider(serverConnection);
clientProvider = new SqlSyncChangeTrackingProvider(clientConnection);
var agent = new SyncAgent(clientProvider, serverProvider); 
setup = new SyncSetup(new string[] { "14 tables"... });
await agent.SynchronizeAsync(setup);
```

1) If I use this dll from a NET7 console app, it always works fine.

2) If I use the same dll from a ASP.NET Web app, targeting net 4.8, and using Quartz.Net to invoke the Execute method **AND** at the same time the synchonization is not trivial (I mean more than 100 rows changed, something that would take at least more then 10 secs to complete approximately) then the following error occurs:

Full stack trace:
```
Dotmim.Sync.SyncException: Cannot write to a closed TextWriter. ---> System.ObjectDisposedException: Cannot write to a closed TextWriter.
   at System.IO.__Error.WriterClosed()
   at System.IO.StreamWriter.FlushAsync()
   at Newtonsoft.Json.JsonTextWriter.<CloseBufferAndWriterAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Newtonsoft.Json.JsonTextWriter.<DoCloseAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dotmim.Sync.Serialization.LocalJsonSerializer.<OpenFileAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Dotmim.Sync.BaseOrchestrator.<InternalReadSyncTableChangesAsync>d__136.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Dotmim.Sync.BaseOrchestrator.<InternalGetChangesAsync>d__135.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dotmim.Sync.LocalOrchestrator.<InternalGetChangesAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Dotmim.Sync.LocalOrchestrator.<InternalGetChangesAsync>d__4.MoveNext()
   --- End of inner exception stack trace ---
   at Dotmim.Sync.LocalOrchestrator.<InternalGetChangesAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dotmim.Sync.SyncAgent.<SynchronizeAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Dotmim.Sync.SyncAgent.<SynchronizeAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

```

The sync fails. However if I simply run the same exact code from the NET7 console app it's OK and synchronizations continues fine!

**Comment by Mimetis** [comment]
Can you try with the last source code clone?
I fixed the same kind of bug, from this conversation: https://github.com/Mimetis/Dotmim.Sync/discussions/817 

Just download the code (or clone it) and try the last commit, and let me know if it's resolving your issue.

**Comment by hakakou** [comment]
I just uploaded and tested. Unfortunately I get the same error:

```
Dotmim.Sync.SyncException: Cannot write to a closed TextWriter. ---> System.ObjectDisposedException: Cannot write to a closed TextWriter.
   at System.IO.__Error.WriterClosed()
   at System.IO.StreamWriter.FlushAsync()
   at Newtonsoft.Json.JsonTextWriter.<CloseBufferAndWriterAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Newtonsoft.Json.JsonTextWriter.<DoCloseAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dotmim.Sync.Serialization.LocalJsonSerializer.<OpenFileAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Dotmim.Sync.BaseOrchestrator.<InternalReadSyncTableChangesAsync>d__136.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Dotmim.Sync.BaseOrchestrator.<InternalGetChangesAsync>d__135.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dotmim.Sync.LocalOrchestrator.<InternalGetChangesAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Dotmim.Sync.LocalOrchestrator.<InternalGetChangesAsync>d__4.MoveNext()
   --- End of inner exception stack trace ---
   at Dotmim.Sync.LocalOrchestrator.<InternalGetChangesAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dotmim.Sync.SyncAgent.<SynchronizeAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Dotmim.Sync.SyncAgent.<SynchronizeAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

```

![image](https://user-images.githubusercontent.com/10587642/207361448-36bf134a-f370-42ed-bfad-d63143dfde7a.png)

**Comment by Mimetis** [comment]
Can you share a little github repo sample, reproducing the bug ?

**Comment by Mimetis** [comment]
fixed in the last commit
