### ISSUE TITLE
Error while sync through ASP.NET Authentication Provider with SyncParameter

### ISSUE THREAD

**Issue by maniish** [Mimetis/Dotmim.Sync#907]
Hi,

We are using WebService and Mobile App for sync (SQL Server & SQL Lite). We used code given in the document/help file.

//---- Server Side Code ---- //
```
if (HttpContext.User.Identity.IsAuthenticated)
{
	// OPTIONAL: -------------------------------------------
	// OPTIONAL: Playing with user coming from bearer token
	// OPTIONAL: -------------------------------------------

	// on each request coming from the client, just inject the User Id parameter
	webServerAgent.OnHttpGettingRequest(args =>
	{
		var pUserId = args.Context.Parameters["UserId"];

		if (pUserId == null)
		{
			var userId = this.HttpContext.User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier);
			args.Context.Parameters.Add("UserId", userId);
		}

	});

	// Because we don't want to send back this value, remove it from the response
	webServerAgent.OnHttpSendingResponse(args =>
	{
		if (args.Context.Parameters.Contains("UserId"))
			args.Context.Parameters.Remove("UserId");
	});

	await webServerAgent.HandleRequestAsync(this.HttpContext);
}
else
{
	this.HttpContext.Response.StatusCode = StatusCodes.Status401Unauthorized;
}
```
// -- Client Side Code --- //
```
	var r = await this.syncAgent.SynchronizeAsync("v0", syncType, new SyncParameters(), progress);
}
catch (Exception ex)
{
	SyncProgressionText = ex.Message;
}
```

We get error on server side when trying to sync
```
  Self referencing loop detected with type 'System.Security.Claims.Claim'. Path 'sc.ps[0].v.Subject.Claims'.
  at Dotmim.Sync.Web.Client.HttpRequestHandler.HandleSyncError(HttpResponseMessage response)
   at Dotmim.Sync.Web.Client.HttpRequestHandler.SendAsync(HttpClient client, SyncContext context, String requestUri, HttpStep step, Byte[] data, String ser, IConverter converter, String hashString, String contentType, CancellationToken cancellationToken)
   at Dotmim.Sync.SyncPolicy.<InternalExecuteAsync>d__17`1[[System.Net.Http.HttpResponseMessage, System.Net.Http, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].MoveNext()
   at Dotmim.Sync.Web.Client.HttpRequestHandler.ProcessRequestAsync(HttpClient client, SyncContext context, String baseUri, Byte[] data, HttpStep step, ISerializerFactory serializerFactory, IConverter converter, Int32 batchSize, SyncPolicy policy, CancellationToken cancellationToken, IProgress`1 progress)
   at Dotmim.Sync.Web.Client.WebRemoteOrchestrator.InternalEnsureScopeInfoAsync(SyncContext context, SyncSetup setup, Boolean overwrite, DbConnection connection, DbTransaction transaction, CancellationToken cancellationToken, IProgress`1 progress)
   at Dotmim.Sync.SyncAgent.SynchronizeAsync(String scopeName, SyncSetup setup, SyncType syncType, SyncParameters parameters, CancellationToken cancellationToken, IProgress`1 progress)
```

Please suggest what can be the issue here

**Comment by maniish** [comment]
If I remove below line from server side code, it works fine

```
var pUserId = args.Context.Parameters["UserId"];

if (pUserId == null)
{
	var userId = this.HttpContext.User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier);
	args.Context.Parameters.Add("UserId", userId);
}
```

**Comment by maniish** [comment]
And if I change the lines as below
 ```
webServerAgent.OnHttpGettingRequest(args =>
                {
                    var pUserId = args.Context.Parameters["UserId"];

                    if (pUserId == null)
                    {
                        var userId = this.HttpContext.User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier);
                        args.Context.Parameters.Add("UserId", **userId.Value**);
                    }

                });
```

I get below error
```
SQLite Error 19: 'UNIQUE constraint failed: scope_info_client.sync_scope_id, scope_info_client.sync_scope_name, scope_info_client.sync_scope_hash'.
├─ [v0].[InternalSaveScopeInfoClientAsync].:SQLite Error 19: 'UNIQUE constraint failed: scope_info_client.sync_scope_id, scope_info_client.sync_scope_name, scope_info_client.sync_scope_hash'.
└── SQLite Error 19: 'UNIQUE constraint failed: scope_info_client.sync_scope_id, scope_info_client.sync_scope_name, scope_info_client.sync_scope_hash'.
```

**Comment by Mimetis** [comment]
I think your error is coming from the `Claim` instance you are using.

In the Server Side code, replace

``` cs
if (pUserId == null)
{
	var userId = this.HttpContext.User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier);
	args.Context.Parameters.Add("UserId", userId);
}
```
With
``` cs
if (pUserId == null)
{
	var userId = this.HttpContext.User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier);
	args.Context.Parameters.Add("UserId", userId.Value);
}
```

(Replacing `userId` by `userId.Value`)

Let me know

**Comment by maniish** [comment]
Done the same and it produce other error. Written that error in above comment.

**Comment by maniish** [comment]
I dont think this error should come but it should be because of filter and this UserId columns we are adding in parameters. If I send UserId from clientside, it works fine. It do not work when we inject it using interceptors.

Rows on client:-
```
sync_scope_id	sync_scope_name	sync_scope_hash	sync_scope_parameters	scope_last_sync_timestamp	scope_last_server_sync_timestamp	scope_last_sync_duration	scope_last_sync	sync_scope_errors	sync_scope_properties
8414A324-E645-438E-9981-31284862414B	v0	YRV8q709t1f3m4tvB/5mPNovhlRrBXozaSNIPsvmlC8=	[]	20221220104947234	2013	638071301872798433	2022-12-20 10:49:47.2798433		
8414A324-E645-438E-9981-31284862414B	v0	87roPsAffi1tHZXBQEw72sxCiFHYRjNJ3CvsMzhYTQ4=	[{"pn":"UserId","v":"1"}]	20221220105149061	2016	638071303091103520	2022-12-20 10:51:49.110352	
```	

Rows on Server
```
sync_scope_id	sync_scope_name	sync_scope_hash	sync_scope_parameters	scope_last_sync_timestamp	scope_last_server_sync_timestamp	scope_last_sync_duration	scope_last_sync	sync_scope_errors	sync_scope_properties
8414A324-E645-438E-9981-31284862414B	v0	87roPsAffi1tHZXBQEw72sxCiFHYRjNJ3CvsMzhYTQ4=	[{"pn":"UserId","v":"1"}]	20221220105149061	2016	638071303082965216	2022-12-20 10:51:48.297	NULL	NULL
8414A324-E645-438E-9981-31284862414B	v0	YRV8q709t1f3m4tvB/5mPNovhlRrBXozaSNIPsvmlC8=	[]	20221220104947234	2013	638071301864655209	2022-12-20 10:49:46.467	NULL	NULL
BDBAB68F-8978-41F4-A6D0-7CD6B2544C28	v0	YRV8q709t1f3m4tvB/5mPNovhlRrBXozaSNIPsvmlC8=	[]	20221220073457732	2000	638071184971768709	2022-12-20 07:34:57.177	NULL	NULL
5CFBB2F9-2264-45AC-AAB3-CAEEB4FDCD68	v0	YRV8q709t1f3m4tvB/5mPNovhlRrBXozaSNIPsvmlC8=	[]	20221220081501234	2000	638071209007361276	2022-12-20 08:15:00.737	NULL	NULL
```

**Comment by MaTToX3** [comment]
> ```
> SQLite Error 19: 'UNIQUE constraint failed: scope_info_client.sync_scope_id, scope_info_client.sync_scope_name, scope_info_client.sync_scope_hash'.
> ├─ [v0].[InternalSaveScopeInfoClientAsync].:SQLite Error 19: 'UNIQUE constraint failed: scope_info_client.sync_scope_id, scope_info_client.sync_scope_name, scope_info_client.sync_scope_hash'.
> └── SQLite Error 19: 'UNIQUE constraint failed: scope_info_client.sync_scope_id, scope_info_client.sync_scope_name, scope_info_client.sync_scope_hash'.
> ```

We are running into the same error when setting parameters from backend like so:

```
webServerAgent.OnHttpGettingRequest((args) =>
{
    if (!args.Context.Parameters.InnerCollection.Where(x => x.Name == "ID_User").Any())
    {
        args.Context.Parameters.Add("ID_User", userId);
    }
});
```

Works fine on <= 0.9.5.

**Comment by Mimetis** [comment]
That's weird !!

Are you sure `var userId = _sessionAccessor.Session.User?.UserId;` always returns something ? (ie `userId` is never `null`) 

I need a way to reproduce the error to debug it.
Any idea ?

**Comment by maniish** [comment]
I will soon provide you code to reproduce error.

**Comment by maniish** [comment]
Hello
This is the URL to download the code to reproduce the bug.  [Download Source Here](https://www.file.io/bGnl/download/zdYhwmqPG028)


To Run the sample following are the changes and some notes from my side.
**App Code Changes**
====================
MainPage.xaml.cs
Task<HttpResponseMessage> response = new HttpClient().PostAsync("http://192.168.1.208/api/Users/Authenticate", stringContent);
Here we created app service and publish it on IIS on this IP for authenticate. I got issues with local Authentication.

**Web API Changes**
===============
Connection string in appsettings.json with database created in sql with following table.

Script of Table
CREATE TABLE [dbo].[RelContact](
	[Id] [nvarchar](150) NOT NULL,
	[UserId] [nvarchar](50) NOT NULL,
	[ContactName] [nvarchar](50) NOT NULL,
	[ModifiedDateTime] [datetime] NOT NULL,
 CONSTRAINT [PK_RelContact_1] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

**Issues:-**
-------

Sync Controller has UserId inserted as Sync Parameter. 

WE get crash on line no 117 in SyncViewModel.cs in Mobile App Code.

Let me know if you require further information.

**Comment by Mimetis** [comment]
Had the same bug, but when trying with last commit (I published a new version tag `[0.9.8-beta-0994](https://www.nuget.org/packages/Dotmim.Sync.Core/0.9.8-beta-0994)`) It's working fine
Can u test ?

**Comment by maniish** [comment]
I will update you soon with this. I have another error with sqlite and I will start another thread for the same.

**Comment by maniish** [comment]
It works fine now but another bug

```
webServerAgent.OnHttpGettingRequest(args =>
                    {
                        var pUserId = args.Context.Parameters["UserId"];

                        if (pUserId == null)
                        {
                            //var userId = this.HttpContext.User.Claims.FirstOrDefault(
                            //    x => x.Type == ClaimTypes.NameIdentifier);
                            var userId = this.HttpContext.User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.Name);
                            args.Context.Parameters.Add("UserId", userId?.Value);
                        }

                    });
```

When I put Claim parameter instead of rgs.Context.Parameters.Add("UserId", userId?.Value);, it gives me below error:-
Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)

**Comment by Mimetis** [comment]
I don't know,
what contains `userId?.Value` ?

**Comment by maniish** [comment]
It contains the GUID as UserID which we passed in Claim.

**Comment by Mimetis** [comment]
Did you tried to convert the value to Guid ?

**Comment by Mimetis** [comment]
Any news on this issue @maniish ?
