### ISSUE TITLE
Sequence contains no matching element

### ISSUE THREAD

**Issue by omernaser** [Mimetis/Dotmim.Sync#959]
I have an issue on iOS devices, but it looks like it does not always happen on the real device; it will keep occurring on the iOS simulator. Can you please let me know if this is a known issue or not? I am using Xamarin forms. Please check the below exception. for more details 

Sequence contains no matching element
-----------------------

-----------------------
-----------------------
INNER EXCEPTION
-----------------------
Sequence contains no matching element
-----------------------
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at Dotmim.Sync.Web.Server.WebServerAgent.SendEndDownloadChangesAsync(HttpContext httpContext, HttpMessageGetMoreChangesRequest httpMessage, SessionCache sessionCache, CancellationToken cancellationToken, IProgress`1 progress)
   at Dotmim.Sync.Web.Server.WebServerAgent.HandleRequestAsync(HttpContext httpContext, Action`1 action, CancellationToken cancellationToken, IProgress`1 progress)
-----------------------

**Comment by Mimetis** [comment]
no idea, need more details

**Comment by omernaser** [comment]
this issue happened when my client app has a version different from the server one is has been fixed by updating my server nuget and the client to the latest one
