### ISSUE TITLE
Error during SynchronizeAsync on Android client

### ISSUE THREAD

**Issue by symbiogenesis** [Mimetis/Dotmim.Sync#960]
I'm seeing this error sometimes on the client, when running a normal SynchronizeAsync.

I'm using MAUI, and have only seen this on the Android client so far. Windows client is fine. I'm seeing it in debug mode, so it isn't an AOT bug.

Version: 0.9.8
Server: SQL Server
Client: SQLite on Android

Exception message:

>[InternalApplyChangesAsync]..[InternalApplyChangesAsync]..[InternalApplyTableChangesAsync]..Specified argument was out of the range of valid values. (Parameter 'Can't make a query on primary keys since number of primary keys columns in criteria is not matching the number of primary keys columns in this table')

Stack trace:

>   at Dotmim.Sync.LocalOrchestrator.<>c__DisplayClass0_0.<<InternalApplyChangesAsync>b__3>d.MoveNext()
--- End of stack trace from previous location ---
   at Dotmim.Sync.LocalOrchestrator.<>c__DisplayClass0_0.<<InternalApplyChangesAsync>b__3>d.MoveNext()
--- End of stack trace from previous location ---
   at Dotmim.Sync.SyncPolicy.<InternalExecuteAsync>d__17'1[[System.ValueTuple'3[[Dotmim.Sync.SyncContext, Dotmim.Sync.Core, Version=0.9.8.0, Culture=neutral, PublicKeyToken=null],[Dotmim.Sync.ClientSyncChanges, Dotmim.Sync.Core, Version=0.9.8.0, Culture=neutral, PublicKeyToken=null],[Dotmim.Sync.ScopeInfoClient, Dotmim.Sync.Core, Version=0.9.8.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at Dotmim.Sync.LocalOrchestrator.InternalApplyChangesAsync(ScopeInfo cScopeInfo, ScopeInfoClient cScopeInfoClient, SyncContext context, ServerSyncChanges serverSyncChanges, ClientSyncChanges clientSyncChanges, ConflictResolutionPolicy policy, Boolean snapshotApplied, DbConnection connection, DbTransaction transaction, CancellationToken cancellationToken, IProgress'1 progress)
   at Dotmim.Sync.SyncAgent.SynchronizeAsync(String scopeName, SyncSetup setup, SyncType syncType, SyncParameters parameters, CancellationToken cancellationToken, IProgress'1 progress)
   at Dotmim.Sync.SyncAgent.SynchronizeAsync(String scopeName, SyncSetup setup, SyncType syncType, SyncParameters parameters, CancellationToken cancellationToken, IProgress'1 progress)

What kinds of things might be the cause of this?

**Comment by Mimetis** [comment]
No idea,
Need more info
A walkthrough / sample github repository where you are able to reproduce would help

**Comment by pazunino** [comment]
Hi @symbiogenesis I'm facing same error with your same configuration, maui client with 0.9.8.
I can sync once or twice without issues but after that the error you mentioned arise without any reason.
Have you solved?

**Comment by symbiogenesis** [comment]
tbh, I'm still using 0.9.6

**Comment by symbiogenesis** [comment]
Downgrading will likely fix your issue
