### ISSUE TITLE
Exception after upgrading to latest version

### ISSUE THREAD

**Issue by maniish** [Mimetis/Dotmim.Sync#974]
We get below error when upgrading to latest version. It was working fine in previous version.

[0:]  Hey hey hey ********************************** UNHANDLED EXCEPTION! Details: Dotmim.Sync.SyncException: [InternalApplyChangesAsync]..[InternalSaveScopeInfoClientAsync]..SQLite Error 19: 'UNIQUE constraint failed: scope_info_client.sync_scope_id, scope_info_client.sync_scope_name, scope_info_client.sync_scope_hash'.
 ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'UNIQUE constraint failed: scope_info_client.sync_scope_id, scope_info_client.sync_scope_name, scope_info_client.sync_scope_hash'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Dotmim.Sync.BaseOrchestrator.InternalSaveScopeInfoClientAsync(ScopeInfoClient scopeInfoClient, SyncContext context, DbConnection connection, DbTransaction transaction, CancellationToken cancellationToken, IProgress`1 progress)
   at Dotmim.Sync.BaseOrchestrator.InternalSaveScopeInfoClientAsync(ScopeInfoClient scopeInfoClient, SyncContext context, DbConnection connection, DbTransaction transaction, CancellationToken cancellationToken, IProgress`1 progress)

**Comment by Craige** [comment]
Possibly related to/duplicate of #962.
